services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./redis.template.conf:/usr/local/etc/redis/redis.template.conf
      - redis-data:/data
    networks:
      - shared_network
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["/usr/local/etc/redis/redis.conf"]