@startuml AccountDeletion
title Account deletion

' === Compact Sequence Styling ===
skinparam defaultFontSize 10
skinparam sequence {
    MessageSpacing 15
    ParticipantSpacing 50
}

' === Actor / Participant Styling ===
skinparam actor {
    FontName Arial
    FontSize 12
    BorderColor Black
    BackgroundColor #ADD8E6
    RoundCorner 10
    MinWidth 120
    MinHeight 120
}

skinparam participant {
    FontName Arial
    FontSize 12
    BorderColor Black
    RoundCorner 10
    MinWidth 140
    MinHeight 100
}

' === Participant Colors ===
' Use stereotypes for coloring specific entities
actor User as user #B0E0E6
' actor Driver as driver #F0E68C
' actor Business as business #D3D3D3
participant Klikni as klikni #E6E6FA 
' participant Stripe as stripe #FFDAB9
participant Pantheon as pantheon #FFE4E1


' === Sequence ===
user -> klikni: Request Close Account
opt User has Wallet funds with charge_id
    klikni->klikni: group WalletFunds by charge_id
    par 
        loop Refund single WalletFund group
            klikni -> stripe: Create Refund for charge_id in total group amount
            klikni <-- stripe
            klikni -[#green]> pantheon: Send accounting data
            note right #LightGreen 
                Podatki za pantheon
            end note
            klikni -> klikni: Delete Wallet Funds in group
        end loop    
end par
end opt
@enduml
