@startuml 
title Referral

' === Compact Sequence Styling ===
skinparam defaultFontSize 10
skinparam sequence {
    MessageSpacing 15
    ParticipantSpacing 50
}

' === Actor / Participant Styling ===
skinparam actor {
    FontName Arial
    FontSize 12
    BorderColor Black
    BackgroundColor #ADD8E6
    RoundCorner 10
    MinWidth 120
    MinHeight 120
}

skinparam participant {
    FontName Arial
    FontSize 12
    BorderColor Black
    RoundCorner 10
    MinWidth 140
    MinHeight 100
}

' === Participant Colors ===
' Use stereotypes for coloring specific entities
' actor User as user #B0E0E6
actor ReferredUser as refuser #99c1c6ff
' actor Driver as driver #F0E68C
' actor Business as business #D3D3D3
participant Klikni as klikni #E6E6FA 
' participant Stripe as stripe #FFDAB9
participant Pantheon as pantheon #FFE4E1


' === Sequence ===
refuser -> klikni: Order payment
opt Referring User meets\n referral rewards conditions
    klikni --> klikni: Create credits\nfor referring user
    klikni -[#green]> pantheon: Send accounting data
    note left of pantheon #LightGreen 
    {amount_eur: number
    user_id: string
    customer_id: string}
    end note
end opt
@enduml
