@startuml 
title Taxi Card, Cash, Narocilnica Payments
' === Compact Sequence Styling ===
skinparam defaultFontSize 10
skinparam sequence {
    MessageSpacing 15
    ParticipantSpacing 50
}

' === Actor / Participant Styling ===
skinparam actor {
    FontName Arial
    FontSize 12
    BorderColor Black
    BackgroundColor #ADD8E6
    RoundCorner 10
    MinWidth 120
    MinHeight 120
}

skinparam participant {
    FontName Arial
    FontSize 12
    BorderColor Black
    RoundCorner 10
    MinWidth 140
    MinHeight 100
}

' === Participant Colors ===
' Use stereotypes for coloring specific entities
actor User as user #B0E0E6
actor Driver as driver #F0E68C
participant Klikni as klikni #E6E6FA
participant Stripe as stripe #FFDAB9
participant Pantheon as pantheon #FFE4E1

' === Sequence Example ===
driver -> driver: Get Taximeter Price
driver -> klikni: Get Final payment details
klikni -> klikni: Check and reserve credits & funds
klikni --> driver: Payment details
driver -> klikni: Confirm payment
group Transfer Money to Platform
    group Transfer Credits
        loop for each
            klikni->klikni: delete Credits
        end
        klikni -[#green]> pantheon: send accounting data
        note right #LightGreen
        {
            price: 100EUR
            credits: 15EUR
        }
        end note
    end
    klikni -[#green]> pantheon: send accounting data about CASH
    note right #LightGreen
    {
        price: 100EUR
        credits: 15EUR
    }
    end note
end

group Transfer Money to Driver
    group Transfer Credits
        loop for each
            klikni->stripe: create transfer
            klikni<--stripe
            klikni->klikni: delete Credits
        end
        klikni -[#green]> pantheon: send accounting data
        note right #LightGreen
        {
            price: 100EUR
            credits: 15EUR
        }
        end note
    end

    klikni -[#green]> pantheon: send accounting data about CASH
    note right #LightGreen
    {
        price: 100EUR
        credits: 15EUR
    }
    end note
end

driver <-- klikni: Order Completed

@enduml
