services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:54321:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - shared_network
