import { VEHICLE_TYPE } from '@prisma/client';

import type { User } from '../users/User.js';
import type { TaxiOrder } from '../taxiOrders/TaxiOrder.js';
import type { DeliveryOrder } from '../deliveryOrders/DeliveryOrder.js';
import type { Document } from '../documents/Document.js';
import type { DriverHistoryLocation } from './DriverHistoryLocation.js';
import type { Municipality } from '../regions/Municipality.js';
import type { Vehicle } from '../vehicles/Vehicle.js';
import type { DriverActivityLog } from './DriverActivityLog.js';
import type { TransportModule } from '../transport/TransportModule.js';
import type { File } from '../files/File.js';
import type { DailyMealsModule } from '../dailyMeals/DailyMealsModule.js';
import type { DailyMealSubscription } from '../dailymeal/DailyMealSubscription.js';
import type { Reviewable } from '../reviews/Reviewable.js';
import type { LateEvent } from '../general/LateEvent.js';
import type { TaxiOrderSent } from '../taxiOrders/TaxiOrderSent.js';
import type { DeliveryOrderSent } from '../deliveryOrders/DeliveryOrderSent.js';
import type { VehicleDriver } from './VehicleDriver.js';
import type { DriverMunicipality } from '../regions/DriverMunicipality.js';
import type { DailyMealsDriver } from '../dailyMeals/DailyMealsDriver.js';
import type { UserFavoriteDriver } from '../users/UserFavoriteDriver.js';

// Auto-generated shape by scripts/generate-dtos.js (mode: map). Do not edit manually.

export type Driver = {
	driver_id: string;
	transport_module_id?: string | null;
	online?: boolean | null;
	on_order?: boolean | null;
	working_hours?: unknown | null;
	ride_requirements?: unknown | null;
	created_at: Date;
	updated_at: Date;
	user_id?: string | null;
	user?: User | null;
	vehicles: VehicleDriver[];
	current_vehicle_id?: string | null;
	last_used_vehicle_id?: string | null;
	orders: TaxiOrder[];
	received_orders: TaxiOrderSent[];
	delivery_orders: DeliveryOrder[];
	received_delivery_orders: DeliveryOrderSent[];
	documents: Document[];
	location?: unknown | null;
	delivery_timeline?: unknown | null;
	last_ping_at: Date;
	is_inactive?: boolean | null;
	transfer_requirements?: unknown | null;
	regions: string;
	driver_history_locations: DriverHistoryLocation[];
	handles_taxi_orders?: boolean | null;
	handles_transfer_orders?: boolean | null;
	handles_courier_orders?: boolean | null;
	handles_delivery_orders?: boolean | null;
	taxi_orders_toggled?: boolean | null;
	transfer_orders_toggled?: boolean | null;
	courier_orders_toggled?: boolean | null;
	delivery_orders_toggled?: boolean | null;
	partner_cash_balance?: number | null;
	come_to_work_last_sent_at?: Date | null;
	driver_municipalities: DriverMunicipality[];
	current_vehicle?: Vehicle | null;
	activity_logs: DriverActivityLog[];
	transport_module?: TransportModule | null;
	profile_picture_id?: string | null;
	profile_picture?: File | null;
	daily_meals: DailyMealsDriver[];
	delivers_daily_meals?: boolean | null;
	on_daily_meals?: boolean | null;
	scheduled_meals_route?: unknown | null;
	subscriptions: DailyMealSubscription[];
	vehicle_type?: VEHICLE_TYPE | null;
	reviewable_id?: string | null;
	reviewable?: Reviewable | null;
	late_events: LateEvent[];
	user_favorite_drivers: UserFavoriteDriver[];
};
