// Auto-generated shape by scripts/generate-dtos.js (mode: map). Do not edit manually.

import type { VEHICLE_TYPE, vehicles } from '@prisma/client';

import type { User } from '../users/User.js';
import type { TaxiOrder } from '../taxiOrders/TaxiOrder.js';
import type { DeliveryOrder } from '../deliveryOrders/DeliveryOrder.js';
import type { Document } from '../documents/Document.js';
import type { DriverHistoryLocation } from '../drivers/DriverHistoryLocation.js';
import type { Municipality } from '../regions/Municipality.js';
import type { DriverActivityLog } from '../drivers/DriverActivityLog.js';
import type { TransportModule } from '../transport/TransportModule.js';
import type { File } from '../files/File.js';
import type { DailyMealsModule } from '../dailyMeals/DailyMealsModule.js';
import type { DailyMealSubscription } from '../dailymeal/DailyMealSubscription.js';
import type { Reviewable } from '../reviews/Reviewable.js';
import type { LateEvent } from '../general/LateEvent.js';

export type Driver = {
	driver_id: string;
	transport_module_id?: string | null;
	online?: boolean | null;
	on_order?: boolean | null;
	working_hours?: unknown | null;
	ride_requirements?: unknown | null;
	created_at: string;
	updated_at: string;
	user_id?: string | null;
	user?: User | null;
	vehicles: vehicles[];
	current_vehicle_id?: string | null;
	last_used_vehicle_id?: string | null;
	orders: TaxiOrder[];
	received_orders: TaxiOrder[];
	delivery_orders: DeliveryOrder[];
	received_delivery_orders: DeliveryOrder[];
	documents: Document[];
	location?: unknown | null;
	delivery_timeline?: unknown | null;
	last_ping_at: string;
	is_inactive?: boolean | null;
	transfer_requirements?: unknown | null;
	regions: string;
	driver_history_locations: DriverHistoryLocation[];
	handles_taxi_orders?: boolean | null;
	handles_transfer_orders?: boolean | null;
	handles_courier_orders?: boolean | null;
	handles_delivery_orders?: boolean | null;
	taxi_orders_toggled?: boolean | null;
	transfer_orders_toggled?: boolean | null;
	courier_orders_toggled?: boolean | null;
	delivery_orders_toggled?: boolean | null;
	partner_cash_balance?: number | null;
	come_to_work_last_sent_at?: string | null;
	driver_municipalities: Municipality[];
	current_vehicle?: vehicles | null;
	activity_logs: DriverActivityLog[];
	transport_module?: TransportModule | null;
	profile_picture_id?: string | null;
	profile_picture?: File | null;
	daily_meals: DailyMealsModule[];
	delivers_daily_meals?: boolean | null;
	on_daily_meals?: boolean | null;
	scheduled_meals_route?: unknown | null;
	subscriptions: DailyMealSubscription[];
	vehicle_type?: VEHICLE_TYPE | null;
	reviewable_id?: string | null;
	reviewable?: Reviewable | null;
	late_events: LateEvent[];
	user_favorite_drivers: User[];
};
