import { z } from 'zod';

export const ACCOUNT_ACTIONS_REASONSchema = z.enum(['SUSPICIOUS_BEHAVIOUR','VIOLATION_OF_TERMS','SPAMMING_OR_SCAMMING','HATE_SPEECH_OR_ABUSE','IMPERSONATION','PAYMENT_FRAUD','SELF_DISABLE','APPEAL_APPROVED','MANUAL_REVIEW_CLEAR','SYSTEM_ERROR_CORRECTION','USER_VERIFIED','BUSINESS_VERIFIED','TERMS_ACCEPTED','TEMPORARY_BAN_EXPIRED']);

export type ACCOUNT_ACTIONS_REASONType = `${z.infer<typeof ACCOUNT_ACTIONS_REASONSchema>}`

export default ACCOUNT_ACTIONS_REASONSchema;
