import { z } from 'zod';

export const DELIVERY_ORDER_STATUSSchema = z.enum([
	'PENDING',
	'CUSTOMER_PAYMENT_FAILED',
	'CUSTOMER_PAYMENT_SUCCESSFUL',
	'CUSTOMER_PAYMENT_PENDING',
	'DISPATCHER_CANCELED',
	'ORDER_FINISHED_FAIL',
	'ORDER_FINISHED_SUCCESS',
	'AUTO_REJECTED',
	'DELIVERY_ACCEPTED',
	'DELIVERY_REJECTED',
	'DELIVERY_CANCELED',
	'DELIVERY_PICKED_UP',
	'DELIVERY_IN_DELIVERY',
	'DELIVERY_DELAYED',
	'DELIVERY_ARRIVED',
	'DELIVERY_DELIVERED',
	'DELIVERY_COMPLETED',
	'CUSTOMER_CANCELED',
	'MERCHANT_ACCEPTED',
	'MERCHANT_REJECTED',
	'MERCHANT_CANCELED',
	'MERCHANT_PREPARING',
	'MERCHANT_DELAYED',
	'MERCHANT_READY_FOR_PICKUP',
	'MERCHANT_REFUNDED',
	'MERCHANT_HIGH_DEMAND',
	'CUSTOMER_PICKED_UP',
]);

export type DELIVERY_ORDER_STATUSType = `${z.infer<typeof DELIVERY_ORDER_STATUSSchema>}`;

export default DELIVERY_ORDER_STATUSSchema;
