import { z } from 'zod';

export const DOCUMENT_TYPESchema = z.enum(['NATIONAL_ID','PASSPORT','PROFILE_PICTURE','LOGO','BANNER','DRIVING_LICENSE','TAXI_LICENCE','PASSENGER_TRANSFER_LICENSE','BACKGROUND_CHECK_REPORT','VEHICLE_REGISTRATION','VEHICLE_INSURANCE','VEHICLE_TECHNICAL_INSPECTION','OPERATING_PERMIT','HACCP_CERTIFICATION','BUSINESS_LICENSE','MENU_ITEM_IMAGE','LOST_ITEM','HEALTH_DECLARATION','DAILY_MEALS_MENU','WALLET_TOPUP']);

export type DOCUMENT_TYPEType = `${z.infer<typeof DOCUMENT_TYPESchema>}`

export default DOCUMENT_TYPESchema;
