import { z } from 'zod';

export const RESERVATION_STATUSSchema = z.enum([
	'PENDING',
	'TABLE_RESERVATION_ACCEPTED',
	'TABLE_RESERVATION_REJECTED',
	'TABLE_RESERVATION_CANCELED',
	'TABLE_RESERVATION_COMPLETED',
	'TABLE_RESERVATION_EXPIRED',
]);

export type RESERVATION_STATUSType = `${z.infer<typeof RESERVATION_STATUSSchema>}`;

export default RESERVATION_STATUSSchema;
