import { z } from 'zod';

export const TAXI_ORDER_STATUSSchema = z.enum([
	'PENDING',
	'TAXI_ACCEPTED',
	'TAXI_REJECTED',
	'TAXI_CANCELED',
	'TAXI_WAITING',
	'TAXI_DRIVING',
	'TAXI_ARRIVED',
	'TAXI_COMPLETED',
	'CUSTOMER_CANCELED',
	'TRANSFER_ACCEPTED',
	'TRANSFER_COMPLETED',
	'AWAITING_PAYMENT',
]);

export type TAXI_ORDER_STATUSType = `${z.infer<typeof TAXI_ORDER_STATUSSchema>}`;

export default TAXI_ORDER_STATUSSchema;
