import { z } from 'zod';

export const Weather_dataScalarFieldEnumSchema = z.enum([
	'weather_data_id',
	'time_epoch',
	'time',
	'temp_c',
	'is_day',
	'condition_text',
	'condition_icon',
	'condition_code',
	'wind_kph',
	'wind_degree',
	'wind_dir',
	'pressure_mb',
	'precip_mm',
	'snow_cm',
	'humidity',
	'cloud',
	'feelslike_c',
	'windchill_c',
	'heatindex_c',
	'dewpoint_c',
	'will_it_rain',
	'chance_of_rain',
	'will_it_snow',
	'chance_of_snow',
	'vis_km',
	'gust_kph',
	'uv',
	'icon',
	'created_at',
	'updated_at',
	'municipalities_id',
	'settlement_id',
]);

export default Weather_dataScalarFieldEnumSchema;
