import fs from 'fs';
import path from 'path';
import prisma from '../prisma.js';
import { upsertFileOnS3Helper } from '../../lib/s3.js';
import { DeleteObject, getFileKey } from '../../lib/s3.js';
import CategoriesDao from '../../dao/Categories.js';
import WordDao from '../../dao/Word.js';
import url from 'node:url';
import { CATEGORY_TYPE, FILE_TYPE } from '@prisma/client';
import { TranslationItem } from '../../schemas/dto/Word/word.dto.js';

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Combined languages object with all translations
const languages: Record<string, Record<string, string>> = {
	en: {
		// Merchant categories
		carParts: 'Car parts',
		personalCareAndDrugstore: 'Personal care and drugstore',
		music: 'Music, instruments and movies',
		construction: 'Construction',
		toys: "Toys and children's equipment",
		mobile: 'Mobile devices',
		clothing: 'Clothing, footwear and accessories',
		officeSupplies: 'Office supplies',
		computer: 'Computing',
		sports: 'Sports',
		fotoAndvideo: 'TV, photo, video and smart devices',
		gardenAndWorkshop: 'Garden and workshop',
		allForHome: 'Home and small household appliances',
		animals: 'Animals',
		food: 'Food',
		bioAndSpecialFood: 'Organic and special food',
		dairy: 'Chilled and dairy products',
		bakery: 'Bread, pastries and sweets',
		meatAndFish: 'Meat, meat products and fish',
		saucesAndSpices: 'Sauces and spices',
		baking: 'Baking',
		drinks: 'Drinks',
		supplements: 'Food supplements',
		fruitsAndVegetables: 'Fruits and vegetables',
		pantry: 'Pantry',
		snacks: 'Sweet and salty snacks',
		sportsNutrition: 'Sports nutrition',
		meals: 'Everything for breakfast, snack or lunch',
		frozen: 'Frozen products',
		// Daily meals categories
		gallbladder: 'Gallbladder',
		glutenFree: 'Gluten-free',
		fit: 'Fit',
		vegetarian: 'Vegetarian',
		vegan: 'Vegan',
		diabetes: 'Diabetes',
		diverse: 'Diverse',
		balanced: 'Balanced',
		dietaryPlan: 'Dietary plan',
		// Local categories
		decoration: 'Decoration',
		eggs: 'Eggs',
		heating: 'Heating',
		beauty: 'Beauty',
		honey: 'Honey and beekeeping products',
		meat: 'Meat products',
		oils: 'Oils and fats',
		fish: 'Fish products',
		preservedAndProcessedProducts: 'Preserved and processed products',
		sweets: 'Sweet products',
		garden: 'Garden',
		grains: 'Grains and milling products',
		// Restaurant categories
		fastFood: 'Fast food',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salads',
		soups: 'Soups',
		sandwiches: 'Sandwiches',
		bbq: 'BBQ',
		steak: 'Steak',
		chicken: 'Chicken',
		kebab: 'Kebab',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Seafood',
		risotto: 'Risotto',
		italian: 'Italian',
		mexican: 'Mexican',
		chinese: 'Chinese',
		japanese: 'Japanese',
		thai: 'Thai',
		korean: 'Korean',
		indian: 'Indian',
		arabic: 'Arabic',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Breakfast',
		lunch: 'Lunch',
		gourmetCuisine: 'Fine dining',
		traditional: 'Traditional',
		healthy: 'Healthy',
		snacksExtras: 'Snacks & extras',
		desserts: 'Desserts',
		iceCream: 'Ice cream',
		hotDrinks: 'Coffee & tea',
		pubs: 'Pubs',
		wine: 'Wine',
		cocktail: 'Cocktails',
		kidsMeals: 'Kids meals',
		studentMeals: 'Student meals',
	},
	sl: {
		carParts: 'Avto - deli',
		personalCareAndDrugstore: 'Osebna nega in drogerija',
		music: 'Glasba, glasbila in filmi',
		construction: 'Gradbeništvo',
		toys: 'Igrače in otroška oprema',
		mobile: 'Mobilne naprave',
		clothing: 'Oblačila, obutev in dodatki',
		officeSupplies: 'Pisarniška oprema',
		computer: 'Računalništvo',
		sports: 'Šport',
		fotoAndvideo: 'TV, foto, video in smart naprave',
		gardenAndWorkshop: 'Vrt in delavnica',
		allForHome: 'Vse za dom in mali gospodinjski aparati',
		animals: 'Živali',
		food: 'Živila',
		bioAndSpecialFood: 'Bio in druga posebna hrana',
		dairy: 'Hlajeni in mlečni izdelki',
		bakery: 'Kruh, pecivo in slaščice',
		meatAndFish: 'Meso, mesni izdelki in ribe',
		saucesAndSpices: 'Omake in začimbe',
		baking: 'Peka',
		drinks: 'Pijače',
		supplements: 'Prehranska dopolnila',
		fruitsAndVegetables: 'Sadje in zelenjava',
		pantry: 'Shramba',
		snacks: 'Sladki in slani prigrizki',
		sportsNutrition: 'Športna prehrana',
		meals: 'Vse za zajtrk, malico ali kosilo',
		frozen: 'Zamrznjeni izdelki',
		gallbladder: 'Žolčnik',
		glutenFree: 'Brezglutensko',
		fit: 'Fit',
		vegetarian: 'Vegetarijansko',
		vegan: 'Vegansko',
		diabetes: 'Diabetes',
		diverse: 'Različno',
		balanced: 'Uravnoteženo',
		dietaryPlan: 'Prehranski načrt',
		decoration: 'Dekoracija',
		eggs: 'Jajca',
		heating: 'Kurjava',
		beauty: 'Lepota',
		honey: 'Med in čebelarski izdelki',
		meat: 'Mesni izdelki',
		oils: 'Olja in maščobe',
		fish: 'Ribji izdelki',
		preservedAndProcessedProducts: 'Shranjeni in predelani izdelki',
		sweets: 'Sladki izdelki',
		garden: 'Vrt',
		grains: 'Žita in mlevski izdelki',
		fastFood: 'Hitra hrana',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Solate',
		soups: 'Juhe',
		sandwiches: 'Sendviči',
		bbq: 'Žar',
		steak: 'Zrezek',
		chicken: 'Piščanec',
		kebab: 'Kebab',
		sushi: 'Suši',
		bowl: 'Poke skleda',
		seafood: 'Morska hrana',
		risotto: 'Rižota',
		italian: 'Italijansko',
		mexican: 'Mehiško',
		chinese: 'Kitajsko',
		japanese: 'Japonsko',
		thai: 'Tajsko',
		korean: 'Korejsko',
		indian: 'Indijsko',
		arabic: 'Arabsko',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Zajtrk',
		lunch: 'Kosilo',
		gourmetCuisine: 'Fine jedi',
		traditional: 'Tradicionalno',
		healthy: 'Zdravo',
		snacksExtras: 'Prigrizki & dodatki',
		desserts: 'Sladice',
		iceCream: 'Sladoled',
		hotDrinks: 'Kava & čaj',
		pubs: 'Pubs',
		wine: 'Vino',
		cocktail: 'Koktajli',
		kidsMeals: 'Otroški obroki',
		studentMeals: 'Študentski obroki',
	},
	it: {
		carParts: 'Parti auto',
		personalCareAndDrugstore: 'Cura personale e drogheria',
		music: 'Musica, strumenti e film',
		construction: 'Costruzioni',
		toys: 'Giocattoli e articoli per bambini',
		mobile: 'Dispositivi mobili',
		clothing: 'Abbigliamento, calzature e accessori',
		officeSupplies: 'Forniture per ufficio',
		computer: 'Informatica',
		sports: 'Sport',
		fotoAndvideo: 'TV, foto, video e dispositivi smart',
		gardenAndWorkshop: 'Giardino e officina',
		allForHome: 'Casa e piccoli elettrodomestici',
		animals: 'Animali',
		food: 'Alimenti',
		bioAndSpecialFood: 'Cibi biologici e speciali',
		dairy: 'Prodotti freschi e latticini',
		bakery: 'Pane, pasticcini e dolci',
		meatAndFish: 'Carne, prodotti di carne e pesce',
		saucesAndSpices: 'Salse e spezie',
		baking: 'Pasticceria',
		drinks: 'Bevande',
		supplements: 'Integratori alimentari',
		fruitsAndVegetables: 'Frutta e verdura',
		pantry: 'Dispensa',
		snacks: 'Snack dolci e salati',
		sportsNutrition: 'Nutrizione sportiva',
		meals: 'Tutto per colazione, spuntino o pranzo',
		frozen: 'Prodotti surgelati',
		gallbladder: 'Cistifellea',
		glutenFree: 'Senza glutine',
		fit: 'In forma',
		vegetarian: 'Vegetariano',
		vegan: 'Vegano',
		diabetes: 'Diabete',
		diverse: 'Diverse',
		balanced: 'Equilibrato',
		dietaryPlan: 'Piano alimentare',
		decoration: 'Decorazione',
		eggs: 'Uova',
		heating: 'Riscaldamento',
		beauty: 'Bellezza',
		honey: 'Miele e prodotti apistici',
		meat: 'Prodotti a base di carne',
		oils: 'Oli e grassi',
		fish: 'Prodotti ittici',
		preservedAndProcessedProducts: 'Prodotti conservati e trasformati',
		sweets: 'Dolci',
		garden: 'Giardino',
		grains: 'Cereali e prodotti molitoria',
		fastFood: 'Fast food',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Insalate',
		soups: 'Zuppe',
		sandwiches: 'Panini',
		bbq: 'Barbecue',
		steak: 'Bistecca',
		chicken: 'Pollo',
		kebab: 'Kebab',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Frutti di mare',
		risotto: 'Risotto',
		italian: 'Italiano',
		mexican: 'Messicano',
		chinese: 'Cinese',
		japanese: 'Giapponese',
		thai: 'Thai',
		korean: 'Coreano',
		indian: 'Indiano',
		arabic: 'Arabo',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Colazione',
		lunch: 'Pranzo',
		gourmetCuisine: 'Alta cucina',
		traditional: 'Tradizionale',
		healthy: 'Salutare',
		snacksExtras: 'Spuntini & extra',
		desserts: 'Dolci',
		iceCream: 'Gelato',
		hotDrinks: 'Caffè & tè',
		pubs: 'Pub',
		wine: 'Vino',
		cocktail: 'Cocktail',
		kidsMeals: 'Pasti per bambini',
		studentMeals: 'Pasti per studenti',
	},
	de: {
		carParts: 'Autoteile',
		personalCareAndDrugstore: 'Körperpflege und Drogerie',
		music: 'Musik, Instrumente und Filme',
		construction: 'Bauwesen',
		toys: 'Spielzeug und Kinderbedarf',
		mobile: 'Mobilgeräte',
		clothing: 'Kleidung, Schuhe und Accessoires',
		officeSupplies: 'Bürobedarf',
		computer: 'Informatik',
		sports: 'Sport',
		fotoAndvideo: 'TV, Foto, Video und Smart-Geräte',
		gardenAndWorkshop: 'Garten und Werkstatt',
		allForHome: 'Haushalt und kleine Elektrogeräte',
		animals: 'Tiere',
		food: 'Lebensmittel',
		bioAndSpecialFood: 'Bio- und Spezialnahrung',
		dairy: 'Kühl- und Milchprodukte',
		bakery: 'Brot, Gebäck und Süßwaren',
		meatAndFish: 'Fleisch, Fleischprodukte und Fisch',
		saucesAndSpices: 'Soßen und Gewürze',
		baking: 'Backen',
		drinks: 'Getränke',
		supplements: 'Nahrungsergänzungsmittel',
		fruitsAndVegetables: 'Obst und Gemüse',
		pantry: 'Vorratskammer',
		snacks: 'Süße und salzige Snacks',
		sportsNutrition: 'Sportnahrung',
		meals: 'Alles für Frühstück, Snack oder Mittagessen',
		frozen: 'Tiefkühlprodukte',
		gallbladder: 'Gallenblase',
		glutenFree: 'Glutenfrei',
		fit: 'Fit',
		vegetarian: 'Vegetarisch',
		vegan: 'Vegan',
		diabetes: 'Diabetes',
		diverse: 'Verschiedenes',
		balanced: 'Ausgewogen',
		dietaryPlan: 'Ernährungsplan',
		decoration: 'Dekoration',
		eggs: 'Eier',
		heating: 'Heizung',
		beauty: 'Schönheit',
		honey: 'Honig und Imkereiprodukte',
		meat: 'Fleischprodukte',
		oils: 'Öle und Fette',
		fish: 'Fischprodukte',
		preservedAndProcessedProducts: 'Konservierte und verarbeitete Produkte',
		sweets: 'Süßwaren',
		garden: 'Garten',
		grains: 'Getreide und Mühlprodukte',
		fastFood: 'Schnellimbiss',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salate',
		soups: 'Suppen',
		sandwiches: 'Sandwiches',
		bbq: 'Grill',
		steak: 'Steak',
		chicken: 'Hähnchen',
		kebab: 'Kebab',
		sushi: 'Sushi',
		bowl: 'Poke Bowl',
		seafood: 'Meeresfrüchte',
		risotto: 'Risotto',
		italian: 'Italienisch',
		mexican: 'Mexikanisch',
		chinese: 'Chinesisch',
		japanese: 'Japanisch',
		thai: 'Thailändisch',
		korean: 'Koreanisch',
		indian: 'Indisch',
		arabic: 'Arabisch',
		kosher: 'Koscher',
		halal: 'Halal',
		breakfast: 'Frühstück',
		lunch: 'Mittagessen',
		gourmetCuisine: 'Gourmetküche',
		traditional: 'Traditionell',
		healthy: 'Gesund',
		snacksExtras: 'Snacks & Extras',
		desserts: 'Desserts',
		iceCream: 'Eiscreme',
		hotDrinks: 'Heiße Getränke',
		pubs: 'Kneipen',
		wine: 'Wein',
		cocktail: 'Cocktails',
		kidsMeals: 'Kindergerichte',
		studentMeals: 'Studentenmahlzeiten',
	},
	es: {
		carParts: 'Piezas de coche',
		personalCareAndDrugstore: 'Cuidado personal y droguería',
		music: 'Música, instrumentos y películas',
		construction: 'Construcción',
		toys: 'Juguetes y artículos infantiles',
		mobile: 'Dispositivos móviles',
		clothing: 'Ropa, calzado y accesorios',
		officeSupplies: 'Material de oficina',
		computer: 'Informática',
		sports: 'Deportes',
		fotoAndvideo: 'TV, foto, vídeo y dispositivos inteligentes',
		gardenAndWorkshop: 'Jardín y taller',
		allForHome: 'Hogar y pequeños electrodomésticos',
		animals: 'Animales',
		food: 'Alimentos',
		bioAndSpecialFood: 'Alimentos orgánicos y especiales',
		dairy: 'Productos refrigerados y lácteos',
		bakery: 'Pan, pasteles y dulces',
		meatAndFish: 'Carne, productos cárnicos y pescado',
		saucesAndSpices: 'Salsas y especias',
		baking: 'Repostería',
		drinks: 'Bebidas',
		supplements: 'Suplementos alimenticios',
		fruitsAndVegetables: 'Frutas y verduras',
		pantry: 'Despensa',
		snacks: 'Aperitivos dulces y salados',
		sportsNutrition: 'Nutrición deportiva',
		meals: 'Todo para el desayuno, merienda o almuerzo',
		frozen: 'Productos congelados',
		gallbladder: 'Vesícula biliar',
		glutenFree: 'Sin gluten',
		fit: 'En forma',
		vegetarian: 'Vegetariano',
		vegan: 'Vegano',
		diabetes: 'Diabetes',
		diverse: 'Diverso',
		balanced: 'Equilibrado',
		dietaryPlan: 'Plan dietético',
		decoration: 'Decoración',
		eggs: 'Huevos',
		heating: 'Calefacción',
		beauty: 'Belleza',
		honey: 'Miel y productos apícolas',
		meat: 'Productos cárnicos',
		oils: 'Aceites y grasas',
		fish: 'Productos pesqueros',
		preservedAndProcessedProducts: 'Productos conservados y procesados',
		sweets: 'Dulces',
		garden: 'Jardín',
		grains: 'Cereales y productos de molinería',
		fastFood: 'Comida rápida',
		pizza: 'Pizza',
		burger: 'Hamburguesa',
		salads: 'Ensaladas',
		soups: 'Sopas',
		sandwiches: 'Sándwiches',
		bbq: 'Barbacoa',
		steak: 'Bistec',
		chicken: 'Pollo',
		kebab: 'Kebab',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Mariscos',
		risotto: 'Risotto',
		italian: 'Italiano',
		mexican: 'Mexicano',
		chinese: 'Chino',
		japanese: 'Japonés',
		thai: 'Tailandés',
		korean: 'Coreano',
		indian: 'Indio',
		arabic: 'Árabe',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Desayuno',
		lunch: 'Almuerzo',
		gourmetCuisine: 'Cocina gourmet',
		traditional: 'Tradicional',
		healthy: 'Saludable',
		snacksExtras: 'Aperitivos y extras',
		desserts: 'Postres',
		iceCream: 'Helado',
		hotDrinks: 'Bebidas calientes',
		pubs: 'Pubs',
		wine: 'Vino',
		cocktail: 'Cóctel',
		kidsMeals: 'Comidas para niños',
		studentMeals: 'Comidas para estudiantes',
	},
	sr: {
		carParts: 'Delovi za auto',
		personalCareAndDrugstore: 'Lična nega i drogerija',
		music: 'Muzika, instrumenti i filmovi',
		construction: 'Građevinarstvo',
		toys: 'Igračke i dečija oprema',
		mobile: 'Mobilni uređaji',
		clothing: 'Odeća, obuća i dodaci',
		officeSupplies: 'Kancelarijski pribor',
		computer: 'Računarstvo',
		sports: 'Sport',
		fotoAndvideo: 'TV, foto, video i smart uređaji',
		gardenAndWorkshop: 'Vrt i radionica',
		allForHome: 'Sve za dom i mali kućanski aparati',
		animals: 'Životinje',
		food: 'Živila',
		bioAndSpecialFood: 'Bio i druga posebna hrana',
		dairy: 'Hlađeni i mlečni proizvodi',
		bakery: 'Hleb, peciva i kolači',
		meatAndFish: 'Meso, mesni proizvodi i riba',
		saucesAndSpices: 'Sosovi i začini',
		baking: 'Pekarstvo',
		drinks: 'Pića',
		supplements: 'Prehrambeni dodaci',
		fruitsAndVegetables: 'Voće i povrće',
		pantry: 'Ostava',
		snacks: 'Slatke i slane grickalice',
		sportsNutrition: 'Sportska ishrana',
		meals: 'Sve za doručak, užinu ili ručak',
		frozen: 'Zamrznuti proizvodi',
		gallbladder: 'Žučna kesa',
		glutenFree: 'Bez glutena',
		fit: 'Fit',
		vegetarian: 'Vegetarijanska',
		vegan: 'Veganska',
		diabetes: 'Dijabetes',
		diverse: 'Različito',
		balanced: 'Balansirano',
		dietaryPlan: 'Dijetni plan',
		decoration: 'Dekoracija',
		eggs: 'Jaja',
		heating: 'Grejanje',
		beauty: 'Lepota',
		honey: 'Med i pčelarski proizvodi',
		meat: 'Mesni proizvodi',
		oils: 'Ulja i masti',
		fish: 'Riblji proizvodi',
		preservedAndProcessedProducts: 'Konzervisani i prerađeni proizvodi',
		sweets: 'Slatki proizvodi',
		garden: 'Bašta',
		grains: 'Žita i mleveni proizvodi',
		fastFood: 'Брза храна',
		pizza: 'Пица',
		burger: 'Пљескавица',
		salads: 'Салате',
		soups: 'Супе',
		sandwiches: 'Сендвичи',
		bbq: 'Роштиљ',
		steak: 'Одређени комад меса',
		chicken: 'Пилетина',
		kebab: 'Кебаб',
		sushi: 'Суши',
		bowl: 'Чинија',
		seafood: 'Морска храна',
		risotto: 'Ризото',
		italian: 'Италијанска кухиња',
		mexican: 'Мексичка кухиња',
		chinese: 'Кинеска кухиња',
		japanese: 'Јапанска кухиња',
		thai: 'Таи кухиња',
		korean: 'Корејска кухиња',
		indian: 'Индијска кухиња',
		arabic: 'Арапска кухиња',
		kosher: 'Кошер',
		halal: 'Халал',
		breakfast: 'Доручак',
		lunch: 'Ручак',
		gourmetCuisine: 'Гурманска кухиња',
		traditional: 'Традиционална кухиња',
		healthy: 'Здрава храна',
		snacksExtras: 'Ужине и додаци',
		desserts: 'Десерти',
		iceCream: 'Сладолед',
		hotDrinks: 'Топли напици',
		pubs: 'Пабови',
		wine: 'Вино',
		cocktail: 'Коктел',
		kidsMeals: 'Оброци за децу',
		studentMeals: 'Студентски оброци',
	},
	bs: {
		carParts: 'Dijelovi za auto',
		personalCareAndDrugstore: 'Lična njega i drogerija',
		music: 'Muzika, instrumenti i filmovi',
		construction: 'Građevinarstvo',
		toys: 'Igračke i dječija oprema',
		mobile: 'Mobilni uređaji',
		clothing: 'Odjeća, obuća i dodaci',
		officeSupplies: 'Kancelarijski pribor',
		computer: 'Računarstvo',
		sports: 'Sport',
		fotoAndvideo: 'TV, foto, video i smart uređaji',
		gardenAndWorkshop: 'Vrt i radionica',
		allForHome: 'Sve za dom i mali kućanski aparati',
		animals: 'Životinje',
		food: 'Živila',
		bioAndSpecialFood: 'Bio i druga posebna hrana',
		dairy: 'Hlađeni i mliječni proizvodi',
		bakery: 'Hljeb, peciva i kolači',
		meatAndFish: 'Meso, mesni proizvodi i riba',
		saucesAndSpices: 'Sosovi i začini',
		baking: 'Pekarstvo',
		drinks: 'Pića',
		supplements: 'Prehrambeni dodaci',
		fruitsAndVegetables: 'Voće i povrće',
		pantry: 'Ostava',
		snacks: 'Slatke i slane grickalice',
		sportsNutrition: 'Sportska prehrana',
		meals: 'Sve za doručak, užinu ili ručak',
		frozen: 'Zamrznuti proizvodi',
		gallbladder: 'Žučna kesa',
		glutenFree: 'Bez glutena',
		fit: 'Fit',
		vegetarian: 'Vegetarijanska',
		vegan: 'Veganska',
		diabetes: 'Dijabetes',
		diverse: 'Raznovrsno',
		balanced: 'Uravnoteženo',
		dietaryPlan: 'Dijetni plan',
		decoration: 'Dekoracija',
		eggs: 'Jaja',
		heating: 'Grijanje',
		beauty: 'Ljepota',
		honey: 'Med i pčelarski proizvodi',
		meat: 'Mesni proizvodi',
		oils: 'Ulja i masti',
		fish: 'Ribji proizvodi',
		preservedAndProcessedProducts: 'Konzervirani i prerađeni proizvodi',
		sweets: 'Slatkiši',
		garden: 'Vrt',
		grains: 'Žita and mlinski proizvodi',
		fastFood: 'Brza hrana',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Salate',
		soups: 'Supe',
		sandwiches: 'Sendviči',
		bbq: 'Roštilj',
		steak: 'Steak',
		chicken: 'Piletina',
		kebab: 'Kebab',
		sushi: 'Suši',
		bowl: 'Poke činija',
		seafood: 'Morska hrana',
		risotto: 'Rizoto',
		italian: 'Italijanska kuhinja',
		mexican: 'Meksička kuhinja',
		chinese: 'Kineska kuhinja',
		japanese: 'Japanska kuhinja',
		thai: 'Tajska kuhinja',
		korean: 'Korejska kuhinja',
		indian: 'Indijska kuhinja',
		arabic: 'Arapska kuhinja',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Doručak',
		lunch: 'Ručak',
		gourmetCuisine: 'Gurmanska kuhinja',
		traditional: 'Tradicionalna kuhinja',
		healthy: 'Zdrava hrana',
		snacksExtras: 'Užine i dodaci',
		desserts: 'Deserti',
		iceCream: 'Sladoled',
		hotDrinks: 'Topli napici',
		pubs: 'Pabovi',
		wine: 'Vino',
		cocktail: 'Koktel',
		kidsMeals: 'Obroci za djecu',
		studentMeals: 'Studentski obroci',
	},
	hr: {
		carParts: 'Auto dijelovi',
		personalCareAndDrugstore: 'Osobna njega i drogerija',
		music: 'Glazba, instrumenti i filmovi',
		construction: 'Građevinarstvo',
		toys: 'Igračke i dječja oprema',
		mobile: 'Mobilni uređaji',
		clothing: 'Odjeća, obuća i dodaci',
		officeSupplies: 'Uredski pribor',
		computer: 'Računalstvo',
		sports: 'Sport',
		fotoAndvideo: 'TV, foto, video i smart uređaji',
		gardenAndWorkshop: 'Vrt i radionica',
		allForHome: 'Sve za dom i mali kućanski aparati',
		animals: 'Životinje',
		food: 'Živila',
		bioAndSpecialFood: 'Bio i druga posebna hrana',
		dairy: 'Hlađeni i mliječni proizvodi',
		bakery: 'Kruh, peciva i kolači',
		meatAndFish: 'Meso, mesni proizvodi i riba',
		saucesAndSpices: 'Umaci i začini',
		baking: 'Pekarstvo',
		drinks: 'Pića',
		supplements: 'Prehrambeni dodaci',
		fruitsAndVegetables: 'Voće i povrće',
		pantry: 'Skladište',
		snacks: 'Slatke i slane grickalice',
		sportsNutrition: 'Sportska prehrana',
		meals: 'Sve za doručak, užinu ili ručak',
		frozen: 'Zamrznuti proizvodi',
		gallbladder: 'Žučna kesa',
		glutenFree: 'Bez glutena',
		fit: 'Fit',
		vegetarian: 'Vegetarijanska',
		vegan: 'Veganska',
		diabetes: 'Dijabetes',
		diverse: 'Raznovrsno',
		balanced: 'Uravnoteženo',
		dietaryPlan: 'Dijetni plan',
		decoration: 'Dekoracija',
		eggs: 'Jaja',
		heating: 'Grijanje',
		beauty: 'Ljepota',
		honey: 'Med i pčelarski proizvodi',
		meat: 'Mesni proizvodi',
		oils: 'Ulja i masti',
		fish: 'Ribji proizvodi',
		preservedAndProcessedProducts: 'Konzervirani i prerađeni proizvodi',
		sweets: 'Slatkiši',
		garden: 'Vrt',
		grains: 'Žita i mlinski proizvodi',
		fastFood: 'Brza hrana',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Salate',
		soups: 'Supe',
		sandwiches: 'Sendviči',
		bbq: 'Roštilj',
		steak: 'Steak',
		chicken: 'Piletina',
		kebab: 'Kebab',
		sushi: 'Suši',
		bowl: 'Poke činija',
		seafood: 'Morska hrana',
		risotto: 'Rizoto',
		italian: 'Italijanska kuhinja',
		mexican: 'Meksička kuhinja',
		chinese: 'Kineska kuhinja',
		japanese: 'Japanska kuhinja',
		thai: 'Tajska kuhinja',
		korean: 'Korejska kuhinja',
		indian: 'Indijska kuhinja',
		arabic: 'Arapska kuhinja',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Doručak',
		lunch: 'Ručak',
		gourmetCuisine: 'Gurmanska kuhinja',
		traditional: 'Tradicionalna kuhinja',
		healthy: 'Zdrava hrana',
		snacksExtras: 'Užine i dodaci',
		desserts: 'Deserti',
		iceCream: 'Sladoled',
		hotDrinks: 'Topli napici',
		pubs: 'Pabovi',
		wine: 'Vino',
		cocktail: 'Koktel',
		kidsMeals: 'Obroci za djecu',
		studentMeals: 'Studentski obroci',
	},
	fr: {
		carParts: 'Pièces automobiles',
		personalCareAndDrugstore: 'Soins personnels et droguerie',
		music: 'Musique, instruments et films',
		construction: 'Construction',
		toys: 'Jouets et articles pour enfants',
		mobile: 'Appareils mobiles',
		clothing: 'Vêtements, chaussures et accessoires',
		officeSupplies: 'Fournitures de bureau',
		computer: 'Informatique',
		sports: 'Sports',
		fotoAndvideo: 'TV, photo, vidéo et appareils connectés',
		gardenAndWorkshop: 'Jardin et atelier',
		allForHome: 'Maison et petits appareils électroménagers',
		animals: 'Animaux',
		food: 'Aliments',
		bioAndSpecialFood: 'Aliments bio et spéciaux',
		dairy: 'Produits frais et laitiers',
		bakery: 'Pain, pâtisseries et confiseries',
		meatAndFish: 'Viande, produits carnés et poisson',
		saucesAndSpices: 'Sauces et épices',
		baking: 'Boulangerie',
		drinks: 'Boissons',
		supplements: 'Compléments alimentaires',
		fruitsAndVegetables: 'Fruits et légumes',
		pantry: 'Garde-manger',
		snacks: 'Snacks sucrés et salés',
		sportsNutrition: 'Nutrition sportive',
		meals: 'Tout pour le petit-déjeuner, le goûter ou le déjeuner',
		frozen: 'Produits surgelés',
		gallbladder: 'Vésicule biliaire',
		glutenFree: 'Sans gluten',
		fit: 'En forme',
		vegetarian: 'Végétarien',
		vegan: 'Végétalien',
		diabetes: 'Diabète',
		diverse: 'Diverses',
		balanced: 'Équilibré',
		dietaryPlan: 'Plan alimentaire',
		decoration: 'Décoration',
		eggs: 'Œufs',
		heating: 'Chauffage',
		beauty: 'Beauté',
		honey: 'Miel et produits apicoles',
		meat: 'Produits carnés',
		oils: 'Huiles et graisses',
		fish: 'Produits de la pêche',
		preservedAndProcessedProducts: 'Produits conservés et transformés',
		sweets: 'Sucreries',
		garden: 'Jardin',
		grains: 'Céréales et produits de minoterie',
		fastFood: 'Fast-food',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salades',
		soups: 'Soupes',
		sandwiches: 'Sandwiches',
		bbq: 'Barbecue',
		steak: 'Steak',
		chicken: 'Poulet',
		kebab: 'Kebab',
		sushi: 'Sushi',
		bowl: 'Bol',
		seafood: 'Fruits de mer',
		risotto: 'Risotto',
		italian: 'Italien',
		mexican: 'Mexicain',
		chinese: 'Chinois',
		japanese: 'Japonais',
		thai: 'Thaï',
		korean: 'Coréen',
		indian: 'Indien',
		arabic: 'Arabe',
		kosher: 'Casher',
		halal: 'Halal',
		breakfast: 'Petit déjeuner',
		lunch: 'Déjeuner',
		gourmetCuisine: 'Cuisine gastronomique',
		traditional: 'Traditionnel',
		healthy: 'Sain',
		snacksExtras: 'Snacks et extras',
		desserts: 'Desserts',
		iceCream: 'Glace',
		hotDrinks: 'Boissons chaudes',
		pubs: 'Pubs',
		wine: 'Vin',
		cocktail: 'Cocktail',
		kidsMeals: 'Repas pour enfants',
		studentMeals: 'Repas étudiants',
	},
	ru: {
		carParts: 'Автозапчасти',
		personalCareAndDrugstore: 'Личная гигиена и аптека',
		music: 'Музыка, инструменты и фильмы',
		construction: 'Строительство',
		toys: 'Игрушки и детские товары',
		mobile: 'Мобильные устройства',
		clothing: 'Одежда, обувь и аксессуары',
		officeSupplies: 'Канцелярские принадлежности',
		computer: 'Вычислительная техника',
		sports: 'Спорт',
		fotoAndvideo: 'Телевизоры, фото, видео и смарт-устройства',
		gardenAndWorkshop: 'Сад и мастерская',
		allForHome: 'Дом и мелкая бытовая техника',
		animals: 'Животные',
		food: 'Продукты питания',
		bioAndSpecialFood: 'Био и другие специальные продукты',
		dairy: 'Охлажденные и молочные продукты',
		bakery: 'Хлеб, выпечка и сладости',
		meatAndFish: 'Мясо, мясные продукты и рыба',
		saucesAndSpices: 'Соусы и специи',
		baking: 'Выпечка',
		drinks: 'Напитки',
		supplements: 'Пищевые добавки',
		fruitsAndVegetables: 'Фрукты и овощи',
		pantry: 'Кладовая',
		snacks: 'Сладкие и соленые закуски',
		sportsNutrition: 'Спортивное питание',
		meals: 'Все для завтрака, перекуса или обеда',
		frozen: 'Замороженные продукты',
		gallbladder: 'Поджелудочная железа',
		glutenFree: 'Без глютена',
		fit: 'Фитнес',
		vegetarian: 'Вегетарианец',
		vegan: 'Веган',
		diabetes: 'Диабет',
		diverse: 'Разнообразные',
		balanced: 'Сбалансированная',
		dietaryPlan: 'План питания',
		decoration: 'Декорация',
		eggs: 'Яйца',
		heating: 'Отопление',
		beauty: 'Красота',
		honey: 'Мёд и пчеловодческие продукты',
		meat: 'Мясные продукты',
		oils: 'Масла и жиры',
		fish: 'Рыбные продукты',
		preservedAndProcessedProducts: 'Консервированные и переработанные продукты',
		sweets: 'Сладости',
		garden: 'Сад',
		grains: 'Зерновые и мучные изделия',
		fastFood: 'Фаст-фуд',
		pizza: 'Пицца',
		burger: 'Бургер',
		salads: 'Салаты',
		soups: 'Супы',
		sandwiches: 'Бутерброды',
		bbq: 'Барбекю',
		steak: 'Стейк',
		chicken: 'Курица',
		kebab: 'Кебаб',
		sushi: 'Суши',
		bowl: 'Боул',
		seafood: 'Морепродукты',
		risotto: 'Ризотто',
		italian: 'Итальянская кухня',
		mexican: 'Мексиканская кухня',
		chinese: 'Китайская кухня',
		japanese: 'Японская кухня',
		thai: 'Тайская кухня',
		korean: 'Корейская кухня',
		indian: 'Индийская кухня',
		arabic: 'Арабская кухня',
		kosher: 'Кошерная еда',
		halal: 'Халяль',
		breakfast: 'Завтрак',
		lunch: 'Обед',
		gourmetCuisine: 'Гурманская кухня',
		traditional: 'Традиционная кухня',
		healthy: 'Здоровая еда',
		snacksExtras: 'Закуски и дополнения',
		desserts: 'Десерты',
		iceCream: 'Мороженое',
		hotDrinks: 'Горячие напитки',
		pubs: 'Пабы',
		wine: 'Вино',
		cocktail: 'Коктейль',
		kidsMeals: 'Детские обеды',
		studentMeals: 'Студенческие обеды',
	},
	ua: {
		carParts: 'Автозапчастини',
		personalCareAndDrugstore: 'Особиста гігієна та аптека',
		music: 'Музика, інструменти та фільми',
		construction: 'Будівництво',
		toys: 'Іграшки та дитяче приладдя',
		mobile: 'Мобільні пристрої',
		clothing: 'Одяг, взуття та аксесуари',
		officeSupplies: 'Офісне приладдя',
		computer: 'Обчислювальна техніка',
		sports: 'Спорт',
		fotoAndvideo: 'Телебачення, фото, відео та смарт-пристрої',
		gardenAndWorkshop: 'Сад та майстерня',
		allForHome: 'Дім та дрібна побутова техніка',
		animals: 'Тварини',
		food: 'Продукти харчування',
		bioAndSpecialFood: 'Органічні та спеціальні продукти',
		dairy: 'Охолоджені та молочні продукти',
		bakery: 'Хліб, випічка та солодощі',
		meatAndFish: 'Мʼясо, мʼясні продукти та риба',
		saucesAndSpices: 'Соуси та спеції',
		baking: 'Випічка',
		drinks: 'Напої',
		supplements: 'Харчові добавки',
		fruitsAndVegetables: 'Фрукти та овочі',
		pantry: 'Комора',
		snacks: 'Солодкі та солоні закуски',
		sportsNutrition: 'Спортивне харчування',
		meals: 'Все для сніданку, перекусу або обіду',
		frozen: 'Заморожені продукти',
		gallbladder: 'Жовчний міхур',
		glutenFree: 'Без глютену',
		fit: 'Фітнес',
		vegetarian: 'Вегетаріанська',
		vegan: 'Веганська',
		diabetes: 'Діабет',
		diverse: 'Різноманітна',
		balanced: 'Збалансована',
		dietaryPlan: 'Дієтичний план',
		decoration: 'Декорація',
		eggs: 'Яйця',
		heating: 'Опалення',
		beauty: 'Краса',
		honey: 'Мед та бджолопродукти',
		meat: 'Мʼясні продукти',
		oils: 'Олії та жири',
		fish: 'Рибні продукти',
		preservedAndProcessedProducts: 'Консервовані та перероблені продукти',
		sweets: 'Солодощі',
		garden: 'Сад',
		grains: 'Зернові та борошняні вироби',
		fastFood: 'Фаст-фуд',
		pizza: 'Піца',
		burger: 'Бургер',
		salads: 'Салати',
		soups: 'Супи',
		sandwiches: 'Сендвічі',
		bbq: 'Барбекю',
		steak: 'Стейк',
		chicken: 'Курка',
		kebab: 'Кебаб',
		sushi: 'Суші',
		bowl: 'Поке боул',
		seafood: 'Морепродукти',
		risotto: 'Різотто',
		italian: 'Італійська',
		mexican: 'Мексиканська',
		chinese: 'Китайська',
		japanese: 'Японська',
		thai: 'Тайська',
		korean: 'Корейська',
		indian: 'Індійська',
		arabic: 'Арабська',
		kosher: 'Кошерна',
		halal: 'Халяль',
		breakfast: 'Сніданок',
		lunch: 'Обід',
		gourmetCuisine: 'Вишукана кухня',
		traditional: 'Традиційна',
		healthy: 'Здорова',
		snacksExtras: 'Закуски та додатки',
		desserts: 'Десерти',
		iceCream: 'Морозиво',
		hotDrinks: 'Кава та чай',
		pubs: 'Паби',
		wine: 'Вино',
		cocktail: 'Коктейлі',
		kidsMeals: 'Дитячі страви',
		studentMeals: 'Студентські страви',
	},
};

// Category definitions organized by type
type CategoryDefinition = {
	key: string;
	tag: string;
	source: string;
	name: string;
	translationKey?: string; // For cases where key differs from translation lookup
};

const CATEGORY_CONFIGS: Record<CATEGORY_TYPE, CategoryDefinition[]> = {
	[CATEGORY_TYPE.MERCHANT]: [
		{ key: 'carParts', tag: 'carParts', source: './categoryIcons/merchantIcons/avto_-_deli.png', name: 'carParts' },
		{
			key: 'personalCareAndDrugstore',
			tag: 'personalCareAndDrugstore',
			source: './categoryIcons/merchantIcons/osbnea_nega_in_drogerija.png',
			name: 'personalCareAndDrugstore',
		},
		{
			key: 'music',
			tag: 'music',
			source: './categoryIcons/merchantIcons/glasba_glasbila_in_filmi.png',
			name: 'music',
		},
		{
			key: 'construction',
			tag: 'construction',
			source: './categoryIcons/merchantIcons/gradbenistvo.png',
			name: 'construction',
		},
		{
			key: 'toys',
			tag: 'toys',
			source: './categoryIcons/merchantIcons/igrace_in_otroska_oprema.png',
			name: 'toys',
		},
		{
			key: 'mobile',
			tag: 'mobile',
			source: './categoryIcons/merchantIcons/mobilne_naprave.png',
			name: 'mobile',
		},
		{
			key: 'clothing',
			tag: 'clothing',
			source: './categoryIcons/merchantIcons/oblacila_obutev_in_dodatki.png',
			name: 'clothing',
		},
		{
			key: 'officeSupplies',
			tag: 'officeSupplies',
			source: './categoryIcons/merchantIcons/pisarniska_oprema.png',
			name: 'officeSupplies',
		},
		{
			key: 'computer',
			tag: 'computer',
			source: './categoryIcons/merchantIcons/racunalnistvo.png',
			name: 'computer',
		},
		{ key: 'sports', tag: 'sports', source: './categoryIcons/merchantIcons/sport.png', name: 'sports' },
		{
			key: 'fotoAndvideo',
			tag: 'fotoAndvideo',
			source: './categoryIcons/merchantIcons/tv_foto_video_in_smart_naprave.png',
			name: 'fotoAndvideo',
		},
		{
			key: 'gardenAndWorkshop',
			tag: 'gardenAndWorkshop',
			source: './categoryIcons/merchantIcons/vrt_in_delavnica.png',
			name: 'gardenAndWorkshop',
		},
		{
			key: 'allForHome',
			tag: 'allForHome',
			source: './categoryIcons/merchantIcons/vse_za_dom_in_mali_gospodinjski_aparati.png',
			name: 'allForHome',
		},
		{ key: 'animals', tag: 'animals', source: './categoryIcons/merchantIcons/zivali.png', name: 'animals' },
		{ key: 'food', tag: 'food', source: './categoryIcons/merchantIcons/zivila.png', name: 'food' },
		{
			key: 'bioAndSpecialFood',
			tag: 'bioAndSpecialFood',
			source: './categoryIcons/merchantIcons/foodIcons/bio_in_druga_posebna_hrana.png',
			name: 'bioAndSpecialFood',
		},
		{
			key: 'dairy',
			tag: 'dairy',
			source: './categoryIcons/merchantIcons/foodIcons/hlajeni_in_mlecni_izdelki.png',
			name: 'dairy',
		},
		{
			key: 'bakery',
			tag: 'bakery',
			source: './categoryIcons/merchantIcons/foodIcons/kruh_pecivo_in_slascice.png',
			name: 'bakery',
		},
		{
			key: 'meatAndFish',
			tag: 'meatAndFish',
			source: './categoryIcons/merchantIcons/foodIcons/meso_mesni_izdelki_in_ribe.png',
			name: 'meatAndFish',
		},
		{
			key: 'saucesAndSpices',
			tag: 'saucesAndSpices',
			source: './categoryIcons/merchantIcons/foodIcons/omake_in_zacimbe.png',
			name: 'saucesAndSpices',
		},
		{ key: 'baking', tag: 'baking', source: './categoryIcons/merchantIcons/foodIcons/peka-1.png', name: 'baking' },
		{ key: 'drinks', tag: 'drinks', source: './categoryIcons/merchantIcons/foodIcons/pijace.png', name: 'drinks' },
		{
			key: 'supplements',
			tag: 'supplements',
			source: './categoryIcons/merchantIcons/foodIcons/prehranska_dopolnila.png',
			name: 'supplements',
		},
		{
			key: 'fruitsAndVegetables',
			tag: 'fruitsAndVegetables',
			source: './categoryIcons/merchantIcons/foodIcons/sadje_in_zelenjava.png',
			name: 'fruitsAndVegetables',
		},
		{
			key: 'pantry',
			tag: 'pantry',
			source: './categoryIcons/merchantIcons/foodIcons/shramba-1.png',
			name: 'pantry',
		},
		{
			key: 'snacks',
			tag: 'snacks',
			source: './categoryIcons/merchantIcons/foodIcons/sladki_in_slani_prigrizki.png',
			name: 'snacks',
		},
		{
			key: 'sportsNutrition',
			tag: 'sportsNutrition',
			source: './categoryIcons/merchantIcons/foodIcons/sportna_prehrana.png',
			name: 'sportsNutrition',
		},
		{
			key: 'meals',
			tag: 'meals',
			source: './categoryIcons/merchantIcons/foodIcons/vse_za_zajtrk_malico_ali_kosilo.png',
			name: 'meals',
		},
		{
			key: 'frozen',
			tag: 'frozen',
			source: './categoryIcons/merchantIcons/foodIcons/zamrznjeni_izdelki.png',
			name: 'frozen',
		},
	],
	[CATEGORY_TYPE.CUISINE]: [
		{ key: 'gallbladder', tag: 'gallbladder', source: './icons/liver_icon.png', name: 'Gallbladder' },
		{
			key: 'glutenFree',
			tag: 'gluten-free',
			source: './icons/gluten-free_icon.png',
			name: 'Gluten Free',
			translationKey: 'glutenFree',
		},
		{ key: 'fit', tag: 'fit', source: './icons/icon_food_fit.png', name: 'Fit' },
		{ key: 'vegetarian', tag: 'vegetarian', source: './icons/salads.png', name: 'Vegeterian' },
		{ key: 'diabetes', tag: 'diabetes', source: './icons/diabetes.png', name: 'Diabetes' },
		{ key: 'diverse', tag: 'diverse', source: './icons/healthy-food.png', name: 'Diverse' },
		{ key: 'balanced', tag: 'balanced', source: './icons/balanced-diet.png', name: 'Balanced' },
		{ key: 'vegan', tag: 'vegan', source: './icons/vegan.png', name: 'Vegan' },
		{
			key: 'dietaryPlan',
			tag: 'dietary-plan',
			source: './icons/diet1_icon.png',
			name: 'Dietary Plan',
			translationKey: 'dietaryPlan',
		},
	],
	[CATEGORY_TYPE.LOCAL]: [
		{
			key: 'decoration',
			tag: 'decoration',
			source: './categoryIcons/localIcons/dekoracija-1.png',
			name: 'decoration',
		},
		{ key: 'eggs', tag: 'eggs', source: './categoryIcons/localIcons/jajca-1.png', name: 'eggs' },
		{ key: 'heating', tag: 'heating', source: './categoryIcons/localIcons/kurjava-1.png', name: 'heating' },
		{ key: 'beauty', tag: 'beauty', source: './categoryIcons/localIcons/lepota-1.png', name: 'beauty' },
		{
			key: 'honey',
			tag: 'honey',
			source: './categoryIcons/localIcons/med_in_cebelarski_izdelki.png',
			name: 'honey',
		},
		{ key: 'meat', tag: 'meat', source: './categoryIcons/localIcons/mesni_izdelki.png', name: 'meat' },
		{ key: 'dairy', tag: 'dairy', source: './categoryIcons/localIcons/mlecni_izdelki.png', name: 'dairy' },
		{ key: 'oils', tag: 'oils', source: './categoryIcons/localIcons/olja_in_mascobe.png', name: 'oils' },
		{
			key: 'bakery',
			tag: 'bakery',
			source: './categoryIcons/localIcons/pekovski_izdelki.png',
			name: 'bakery',
		},
		{ key: 'drinks', tag: 'drinks', source: './categoryIcons/localIcons/pijace.png', name: 'drinks' },
		{ key: 'fish', tag: 'fish', source: './categoryIcons/localIcons/ribji_izdelki.png', name: 'fish' },
		{
			key: 'fruitsAndVegetables',
			tag: 'fruitsAndVegetables',
			source: './categoryIcons/localIcons/sadje_in_zelenjava.png',
			name: 'fruitsAndVegetables',
		},
		{
			key: 'preservedAndProcessedProducts',
			tag: 'preservedAndProcessedProducts',
			source: './categoryIcons/localIcons/shranjeni_in_predelani_izdelki.png',
			name: 'preservedAndProcessedProducts',
		},
		{ key: 'sweets', tag: 'sweets', source: './categoryIcons/localIcons/sladki_izdelki.png', name: 'sweets' },
		{ key: 'garden', tag: 'garden', source: './categoryIcons/localIcons/vrt-1.png', name: 'garden' },
		{
			key: 'grains',
			tag: 'grains',
			source: './categoryIcons/localIcons/zita_in_mlevski_izdelki.png',
			name: 'grains',
		},
	],
	[CATEGORY_TYPE.MENU]: [
		{
			key: 'fastFood',
			tag: 'fast-food',
			source: './categoryIcons/restaurantIcons/fast-food-1.png',
			name: 'Fast food',
		},
		{ key: 'pizza', tag: 'pizza', source: './categoryIcons/restaurantIcons/pizza-1.png', name: 'Pizza' },
		{ key: 'burger', tag: 'burger', source: './categoryIcons/restaurantIcons/hamburger-1.png', name: 'Burger' },
		{ key: 'salads', tag: 'salads', source: './categoryIcons/restaurantIcons/salad.png', name: 'Salads' },
		{ key: 'soups', tag: 'soups', source: './categoryIcons/restaurantIcons/soup-1.png', name: 'Soups' },
		{
			key: 'vegetarian',
			tag: 'vegetarian',
			source: './categoryIcons/restaurantIcons/vegetarian-1.png',
			name: 'Vegetarian',
		},
		{ key: 'vegan', tag: 'vegan', source: './categoryIcons/restaurantIcons/vegan-1.png', name: 'Vegan' },
		{ key: 'bakery', tag: 'bakery', source: './categoryIcons/restaurantIcons/bakery-1.png', name: 'Bakeries' },
		{
			key: 'sandwiches',
			tag: 'sandwiches',
			source: './categoryIcons/restaurantIcons/sandwich.png',
			name: 'Sandwiches',
		},
		{ key: 'bbq', tag: 'bbq', source: './categoryIcons/restaurantIcons/bbq-1.png', name: 'BBQ' },
		{ key: 'steak', tag: 'steak', source: './categoryIcons/restaurantIcons/steak-1.png', name: 'Steak' },
		{
			key: 'chicken',
			tag: 'chicken',
			source: './categoryIcons/restaurantIcons/chicken-1.png',
			name: 'Chicken',
		},
		{ key: 'kebab', tag: 'kebab', source: './categoryIcons/restaurantIcons/kebab.png', name: 'Kebab' },
		{ key: 'fish', tag: 'fish', source: './categoryIcons/restaurantIcons/fish-1.png', name: 'Fish' },
		{ key: 'sushi', tag: 'sushi', source: './categoryIcons/restaurantIcons/sushi-1.png', name: 'Sushi' },
		{ key: 'bowl', tag: 'bowl', source: './categoryIcons/restaurantIcons/bowl-1.png', name: 'Poke bowl' },
		{
			key: 'seafood',
			tag: 'seafood',
			source: './categoryIcons/restaurantIcons/seafood-1.png',
			name: 'Seafood',
		},
		{
			key: 'risotto',
			tag: 'risotto',
			source: './categoryIcons/restaurantIcons/risotto-1.png',
			name: 'Risotto',
		},
		{
			key: 'italian',
			tag: 'italian',
			source: './categoryIcons/restaurantIcons/italian-1.png',
			name: 'Italian',
		},
		{
			key: 'mexican',
			tag: 'mexican',
			source: './categoryIcons/restaurantIcons/mexican-1.png',
			name: 'Mexican',
		},
		{
			key: 'chinese',
			tag: 'chinese',
			source: './categoryIcons/restaurantIcons/chinese-1.png',
			name: 'Chinese',
		},
		{
			key: 'japanese',
			tag: 'japanese',
			source: './categoryIcons/restaurantIcons/japanese-1.png',
			name: 'Japanese',
		},
		{ key: 'thai', tag: 'thai', source: './categoryIcons/restaurantIcons/thai-1.png', name: 'Thai' },
		{ key: 'korean', tag: 'korean', source: './categoryIcons/restaurantIcons/korean-1.png', name: 'Korean' },
		{ key: 'indian', tag: 'indian', source: './categoryIcons/restaurantIcons/indian-1.png', name: 'Indian' },
		{ key: 'arabic', tag: 'arabic', source: './categoryIcons/restaurantIcons/arabic-1.png', name: 'Arabic' },
		{ key: 'kosher', tag: 'kosher', source: './categoryIcons/restaurantIcons/kosher-1.png', name: 'Kosher' },
		{ key: 'halal', tag: 'halal', source: './categoryIcons/restaurantIcons/halal-1.png', name: 'Halal' },
		{
			key: 'breakfast',
			tag: 'breakfast',
			source: './categoryIcons/restaurantIcons/breakfast-1.png',
			name: 'Breakfast',
		},
		{ key: 'lunch', tag: 'lunch', source: './categoryIcons/restaurantIcons/lunch-1.png', name: 'Lunch' },
		{
			key: 'gourmetCuisine',
			tag: 'gourmet-cuisine',
			source: './categoryIcons/restaurantIcons/gourmet.png',
			name: 'Fine dining',
		},
		{
			key: 'traditional',
			tag: 'traditional',
			source: './categoryIcons/restaurantIcons/traditional-1.png',
			name: 'Traditional',
		},
		{
			key: 'healthy',
			tag: 'healthy',
			source: './categoryIcons/restaurantIcons/healthy-1.png',
			name: 'Healthy',
		},
		{
			key: 'snacksExtras',
			tag: 'extras',
			source: './categoryIcons/restaurantIcons/snacks.png',
			name: 'Snacks & extras',
		},
		{
			key: 'desserts',
			tag: 'desserts',
			source: './categoryIcons/restaurantIcons/desserts-1.png',
			name: 'Desserts',
		},
		{
			key: 'iceCream',
			tag: 'ice-cream',
			source: './categoryIcons/restaurantIcons/ice_cream.png',
			name: 'Ice cream',
		},
		{
			key: 'hotDrinks',
			tag: 'hot-drinks',
			source: './categoryIcons/restaurantIcons/hot_drinks.png',
			name: 'Coffee & Tea',
		},
		{ key: 'pubs', tag: 'pubs', source: './categoryIcons/restaurantIcons/pub-1.png', name: 'Pubs' },
		{ key: 'wine', tag: 'wine', source: './categoryIcons/restaurantIcons/wine-1.png', name: 'Wine' },
		{
			key: 'cocktail',
			tag: 'cocktail',
			source: './categoryIcons/restaurantIcons/cocktail-1.png',
			name: 'Cocktails',
		},
		{
			key: 'drinks',
			tag: 'soft-drinks',
			source: './categoryIcons/restaurantIcons/soft_drinks.png',
			name: 'Soft drinks',
		},
		{
			key: 'kidsMeals',
			tag: 'kids-meals',
			source: './categoryIcons/restaurantIcons/kids_meal.png',
			name: 'Kids meals',
		},
		{
			key: 'studentMeals',
			tag: 'student-meals',
			source: './categoryIcons/restaurantIcons/student_meal.png',
			name: 'Student meals',
		},
	],
};

async function seedCategory(
	categoryDef: CategoryDefinition,
	categoryType: CATEGORY_TYPE,
	translationKey?: string
): Promise<void> {
	const lookupKey = translationKey || categoryDef.translationKey || categoryDef.key || categoryDef.tag;
	const translations: TranslationItem[] = [];
	for (const lang in languages) {
		const translation = languages[lang]?.[lookupKey];
		if (translation) {
			translations.push({
				language: lang as 'en' | 'sl' | 'de' | 'fr' | 'it' | 'es' | 'hr' | 'ru' | 'bs' | 'sr' | 'ua',
				translation: translation,
			});
		}
	}

	const imagePath = path.resolve(__dirname, categoryDef.source);
	let base64: string | null = null;
	try {
		if (fs.existsSync(imagePath)) {
			const imageBuffer = fs.readFileSync(imagePath);
			base64 = `data:image/png;base64,${imageBuffer.toString('base64')}`;
		} else {
			console.warn(`File not found: ${imagePath}`);
		}
	} catch (error) {
		console.error(`Error processing ${imagePath}:`, error);
	}

	const categoryObj = {
		categoryData: {
			name: categoryDef.name,
			description: categoryDef.name,
			category_type: categoryType,
			tag: categoryDef.tag,
		},
		translations: translations,
		iconFileData: {
			file_type: FILE_TYPE.IMAGE,
			mime_type: 'image/png',
			base64: base64 || '',
		},
		parent_categories_id: null,
		subcategories: [],
	};

	try {
		let categoryExists = await prisma.categories.findUnique({
			where: {
				tag_category_type: {
					tag: categoryObj.categoryData.tag,
					category_type: categoryObj.categoryData.category_type,
				},
			},
			include: {
				icon: true,
			},
		});

		let category_id = categoryExists?.categories_id;
		if (categoryExists) {
			if (categoryExists.icon) {
				const key = getFileKey(categoryExists.icon.file_id, categoryExists.icon.mime_type);
				await DeleteObject(key);
			}
			const cat = await CategoriesDao.updateCategory(
				category_id!,
				categoryObj.categoryData,
				categoryObj.translations,
				categoryObj.subcategories,
				categoryObj.parent_categories_id,
				categoryObj.iconFileData
			);
			category_id = cat.categories_id;
			if (categoryObj.iconFileData && cat.icon) {
				const { file_type, mime_type, base64 } = categoryObj.iconFileData;
				await upsertFileOnS3Helper('', cat.icon, file_type, mime_type, base64);
			}
			console.log(`Category ${cat.categories_id} updated.`);
		} else {
			const cat = await CategoriesDao.createCategory(
				categoryObj.categoryData,
				categoryObj.translations,
				categoryObj.subcategories,
				[],
				categoryObj.parent_categories_id,
				categoryObj.iconFileData
			);
			category_id = cat.categories_id;
			if (categoryObj.iconFileData && cat.icon) {
				const { file_type, mime_type, base64 } = categoryObj.iconFileData;
				await upsertFileOnS3Helper('', cat.icon, file_type, mime_type, base64);
			}
			console.log(`Category ${cat.categories_id} created.`);
		}

		// Create or update word
		const wordObj = {
			wordData: {
				word: categoryObj.categoryData.name,
				categories_id: category_id!,
			},
			translations: translations,
		};
		let wordExists = await prisma.words.findUnique({
			where: {
				word: wordObj.wordData.word,
			},
		});
		if (wordExists) {
			await prisma.words.update({
				where: {
					word: wordObj.wordData.word,
				},
				data: {
					category: {
						connect: {
							categories_id: category_id!,
						},
					},
				},
			});
			console.log(`Word ${wordExists.word} already exists.`);
		} else {
			const word = await WordDao.createWord(
				wordObj.wordData.word,
				wordObj.wordData.categories_id,
				wordObj.translations
			);
			console.log(`Word ${word.word_id} created.`);
		}
	} catch (error) {
		console.log('Error creating category and word:', error);
	}
}

async function seedCategories() {
	console.log('Seeding all categories...');

	// Seed each category type
	for (const categoryType of Object.values(CATEGORY_TYPE)) {
		const categories = CATEGORY_CONFIGS[categoryType];
		if (!categories) continue;

		console.log(`\nSeeding ${categoryType} categories...`);
		for (const categoryDef of categories) {
			console.log(`Seeding category: ${categoryDef.tag}`);
			await seedCategory(categoryDef, categoryType, categoryDef.translationKey);
		}
	}

	console.log('\nAll categories seeded.');
}

export default seedCategories;
