import fs from 'fs';
import path from 'path';
import prisma from '../prisma.js';
import { upsertFileOnS3Helper } from '../../controllers/FilesController.js';
import CategoriesDao from '../../dao/Categories.js';
import WordDao from '../../dao/Word.js';
import url from 'node:url';
const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
let languages = {
	en: {
		fastFood: 'Fast food',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salads',
		soups: 'Soups',
		vegetarian: 'Vegetarian',
		vegan: 'Vegan',
		bakery: 'Bakeries',
		sandwiches: 'Sandwiches',
		bbq: 'BBQ',
		steak: 'Steak',
		chicken: 'Chicken',
		kebab: 'Kebab',
		fish: 'Fish',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Seafood',
		risotto: 'Risotto',
		italian: 'Italian',
		mexican: 'Mexican',
		chinese: 'Chinese',
		japanese: 'Japanese',
		thai: 'Thai',
		korean: 'Korean',
		indian: 'Indian',
		arabic: 'Arabic',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Breakfast',
		lunch: 'Lunch',
		gourmetCuisine: 'Fine dining',
		traditional: 'Traditional',
		healthy: 'Healthy',
		snacksExtras: 'Snacks & extras',
		desserts: 'Desserts',
		iceCream: 'Ice cream',
		hotDrinks: 'Coffee & tea',
		pubs: 'Pubs',
		wine: 'Wine',
		cocktail: 'Cocktails',
		drinks: 'Soft drinks',
		kidsMeals: 'Kids meals',
		studentMeals: 'Student meals',
	},
	sl: {
		fastFood: 'Hitra hrana',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Solate',
		soups: 'Juhe',
		vegetarian: 'Vegetarijansko',
		vegan: 'Vegansko',
		bakery: 'Pekarne',
		sandwiches: 'Sendviči',
		bbq: 'Žar',
		steak: 'Zrezek',
		chicken: 'Piščanec',
		kebab: 'Kebab',
		fish: 'Riba',
		sushi: 'Suši',
		bowl: 'Poke skleda',
		seafood: 'Morska hrana',
		risotto: 'Rižota',
		italian: 'Italijansko',
		mexican: 'Mehiško',
		chinese: 'Kitajsko',
		japanese: 'Japonsko',
		thai: 'Tajsko',
		korean: 'Korejsko',
		indian: 'Indijsko',
		arabic: 'Arabsko',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Zajtrk',
		lunch: 'Kosilo',
		gourmetCuisine: 'Fine jedi',
		traditional: 'Tradicionalno',
		healthy: 'Zdravo',
		snacksExtras: 'Prigrizki & dodatki',
		desserts: 'Sladice',
		iceCream: 'Sladoled',
		hotDrinks: 'Kava & čaj',
		pubs: 'Pubs',
		wine: 'Vino',
		cocktail: 'Koktajli',
		drinks: 'Brezalkoholne pijače',
		kidsMeals: 'Otroški obroki',
		studentMeals: 'Študentski obroki',
	},
	it: {
		fastFood: 'Fast food',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Insalate',
		soups: 'Zuppe',
		vegetarian: 'Vegetariano',
		vegan: 'Vegano',
		bakery: 'Panetterie',
		sandwiches: 'Panini',
		bbq: 'Barbecue',
		steak: 'Bistecca',
		chicken: 'Pollo',
		kebab: 'Kebab',
		fish: 'Pesce',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Frutti di mare',
		risotto: 'Risotto',
		italian: 'Italiano',
		mexican: 'Messicano',
		chinese: 'Cinese',
		japanese: 'Giapponese',
		thai: 'Thai',
		korean: 'Coreano',
		indian: 'Indiano',
		arabic: 'Arabo',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Colazione',
		lunch: 'Pranzo',
		gourmetCuisine: 'Alta cucina',
		traditional: 'Tradizionale',
		healthy: 'Salutare',
		snacksExtras: 'Spuntini & extra',
		desserts: 'Dolci',
		iceCream: 'Gelato',
		hotDrinks: 'Caffè & tè',
		pubs: 'Pub',
		wine: 'Vino',
		cocktail: 'Cocktail',
		drinks: 'Bevande analcoliche',
		kidsMeals: 'Pasti per bambini',
		studentMeals: 'Pasti per studenti',
	},
	de: {
		fastFood: 'Schnellimbiss',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salate',
		soups: 'Suppen',
		vegetarian: 'Vegetarisch',
		vegan: 'Vegan',
		bakery: 'Bäckerei',
		sandwiches: 'Sandwiches',
		bbq: 'Grill',
		steak: 'Steak',
		chicken: 'Hähnchen',
		kebab: 'Kebab',
		fish: 'Fisch',
		sushi: 'Sushi',
		bowl: 'Poke Bowl',
		seafood: 'Meeresfrüchte',
		risotto: 'Risotto',
		italian: 'Italienisch',
		mexican: 'Mexikanisch',
		chinese: 'Chinesisch',
		japanese: 'Japanisch',
		thai: 'Thailändisch',
		korean: 'Koreanisch',
		indian: 'Indisch',
		arabic: 'Arabisch',
		kosher: 'Koscher',
		halal: 'Halal',
		breakfast: 'Frühstück',
		lunch: 'Mittagessen',
		gourmetCuisine: 'Gourmetküche',
		traditional: 'Traditionell',
		healthy: 'Gesund',
		snacksExtras: 'Snacks & Extras',
		desserts: 'Desserts',
		iceCream: 'Eiscreme',
		hotDrinks: 'Heiße Getränke',
		pubs: 'Kneipen',
		wine: 'Wein',
		cocktail: 'Cocktails',
		drinks: 'Alkoholfreie Getränke',
		kidsMeals: 'Kindergerichte',
		studentMeals: 'Studentenmahlzeiten',
	},
	es: {
		fastFood: 'Comida rápida',
		pizza: 'Pizza',
		burger: 'Hamburguesa',
		salads: 'Ensaladas',
		soups: 'Sopas',
		vegetarian: 'Vegetariano',
		vegan: 'Vegano',
		bakery: 'Panadería',
		sandwiches: 'Sándwiches',
		bbq: 'Barbacoa',
		steak: 'Bistec',
		chicken: 'Pollo',
		kebab: 'Kebab',
		fish: 'Pescado',
		sushi: 'Sushi',
		bowl: 'Poke bowl',
		seafood: 'Mariscos',
		risotto: 'Risotto',
		italian: 'Italiano',
		mexican: 'Mexicano',
		chinese: 'Chino',
		japanese: 'Japonés',
		thai: 'Tailandés',
		korean: 'Coreano',
		indian: 'Indio',
		arabic: 'Árabe',
		kosher: 'Kosher',
		halal: 'Halal',
		breakfast: 'Desayuno',
		lunch: 'Almuerzo',
		gourmetCuisine: 'Cocina gourmet',
		traditional: 'Tradicional',
		healthy: 'Saludable',
		snacksExtras: 'Aperitivos y extras',
		desserts: 'Postres',
		iceCream: 'Helado',
		hotDrinks: 'Bebidas calientes',
		pubs: 'Pubs',
		wine: 'Vino',
		cocktail: 'Cóctel',
		drinks: 'Bebidas',
		kidsMeals: 'Comidas para niños',
		studentMeals: 'Comidas para estudiantes',
	},
	sr: {
		fastFood: 'Брза храна',
		pizza: 'Пица',
		burger: 'Пљескавица',
		salads: 'Салате',
		soups: 'Супе',
		vegetarian: 'Вегетаријанска храна',
		vegan: 'Веганска храна',
		bakery: 'Пекара',
		sandwiches: 'Сендвичи',
		bbq: 'Роштиљ',
		steak: 'Одређени комад меса',
		chicken: 'Пилетина',
		kebab: 'Кебаб',
		fish: 'Риба',
		sushi: 'Суши',
		bowl: 'Чинија',
		seafood: 'Морска храна',
		risotto: 'Ризото',
		italian: 'Италијанска кухиња',
		mexican: 'Мексичка кухиња',
		chinese: 'Кинеска кухиња',
		japanese: 'Јапанска кухиња',
		thai: 'Таи кухиња',
		korean: 'Корејска кухиња',
		indian: 'Индијска кухиња',
		arabic: 'Арапска кухиња',
		kosher: 'Кошер',
		halal: 'Халал',
		breakfast: 'Доручак',
		lunch: 'Ручак',
		gourmetCuisine: 'Гурманска кухиња',
		traditional: 'Традиционална кухиња',
		healthy: 'Здрава храна',
		snacksExtras: 'Ужине и додаци',
		desserts: 'Десерти',
		iceCream: 'Сладолед',
		hotDrinks: 'Топли напици',
		pubs: 'Пабови',
		wine: 'Вино',
		cocktail: 'Коктел',
		drinks: 'Напици',
		kidsMeals: 'Оброци за децу',
		studentMeals: 'Студентски оброци',
	},
	bs: {
		fastFood: 'Brza hrana',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Salate',
		soups: 'Supe',
		vegetarian: 'Vegetarijanska hrana',
		vegan: 'Veganska hrana',
		bakery: 'Pekara',
		sandwiches: 'Sendviči',
		bbq: 'Roštilj',
		steak: 'Steak',
		chicken: 'Piletina',
		kebab: 'Kebab',
		fish: 'Riba',
		sushi: 'Suši',
		bowl: 'Poke činija',
		seafood: 'Morska hrana',
		risotto: 'Rizoto',
		italian: 'Italijanska kuhinja',
		mexican: 'Meksička kuhinja',
		chinese: 'Kineska kuhinja',
		japanese: 'Japanska kuhinja',
		thai: 'Tajska kuhinja',
		korean: 'Korejska kuhinja',
		indian: 'Indijska kuhinja',
		arabic: 'Arapska kuhinja',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Doručak',
		lunch: 'Ručak',
		gourmetCuisine: 'Gurmanska kuhinja',
		traditional: 'Tradicionalna kuhinja',
		healthy: 'Zdrava hrana',
		snacksExtras: 'Užine i dodaci',
		desserts: 'Deserti',
		iceCream: 'Sladoled',
		hotDrinks: 'Topli napici',
		pubs: 'Pabovi',
		wine: 'Vino',
		cocktail: 'Koktel',
		drinks: 'Pića',
		kidsMeals: 'Obroci za djecu',
		studentMeals: 'Studentski obroci',
	},
	hr: {
		fastFood: 'Brza hrana',
		pizza: 'Pizza',
		burger: 'Hamburger',
		salads: 'Salate',
		soups: 'Supe',
		vegetarian: 'Vegetarijanska hrana',
		vegan: 'Veganska hrana',
		bakery: 'Pekara',
		sandwiches: 'Sendviči',
		bbq: 'Roštilj',
		steak: 'Steak',
		chicken: 'Piletina',
		kebab: 'Kebab',
		fish: 'Riba',
		sushi: 'Suši',
		bowl: 'Poke činija',
		seafood: 'Morska hrana',
		risotto: 'Rizoto',
		italian: 'Italijanska kuhinja',
		mexican: 'Meksička kuhinja',
		chinese: 'Kineska kuhinja',
		japanese: 'Japanska kuhinja',
		thai: 'Tajska kuhinja',
		korean: 'Korejska kuhinja',
		indian: 'Indijska kuhinja',
		arabic: 'Arapska kuhinja',
		kosher: 'Košer',
		halal: 'Halal',
		breakfast: 'Doručak',
		lunch: 'Ručak',
		gourmetCuisine: 'Gurmanska kuhinja',
		traditional: 'Tradicionalna kuhinja',
		healthy: 'Zdrava hrana',
		snacksExtras: 'Užine i dodaci',
		desserts: 'Deserti',
		iceCream: 'Sladoled',
		hotDrinks: 'Topli napici',
		pubs: 'Pabovi',
		wine: 'Vino',
		cocktail: 'Koktel',
		drinks: 'Pića',
		kidsMeals: 'Obroci za djecu',
		studentMeals: 'Studentski obroci',
	},
	fr: {
		fastFood: 'Fast-food',
		pizza: 'Pizza',
		burger: 'Burger',
		salads: 'Salades',
		soups: 'Soupes',
		vegetarian: 'Végétarien',
		vegan: 'Végétalien',
		bakery: 'Boulangerie',
		sandwiches: 'Sandwiches',
		bbq: 'Barbecue',
		steak: 'Steak',
		chicken: 'Poulet',
		kebab: 'Kebab',
		fish: 'Poisson',
		sushi: 'Sushi',
		bowl: 'Bol',
		seafood: 'Fruits de mer',
		risotto: 'Risotto',
		italian: 'Italien',
		mexican: 'Mexicain',
		chinese: 'Chinois',
		japanese: 'Japonais',
		thai: 'Thaï',
		korean: 'Coréen',
		indian: 'Indien',
		arabic: 'Arabe',
		kosher: 'Casher',
		halal: 'Halal',
		breakfast: 'Petit déjeuner',
		lunch: 'Déjeuner',
		gourmetCuisine: 'Cuisine gastronomique',
		traditional: 'Traditionnel',
		healthy: 'Sain',
		snacksExtras: 'Snacks et extras',
		desserts: 'Desserts',
		iceCream: 'Glace',
		hotDrinks: 'Boissons chaudes',
		pubs: 'Pubs',
		wine: 'Vin',
		cocktail: 'Cocktail',
		drinks: 'Boissons',
		kidsMeals: 'Repas pour enfants',
		studentMeals: 'Repas étudiants',
	},
	ru: {
		fastFood: 'Фаст-фуд',
		pizza: 'Пицца',
		burger: 'Бургер',
		salads: 'Салаты',
		soups: 'Супы',
		vegetarian: 'Вегетарианская еда',
		vegan: 'Веганская еда',
		bakery: 'Булочная',
		sandwiches: 'Бутерброды',
		bbq: 'Барбекю',
		steak: 'Стейк',
		chicken: 'Курица',
		kebab: 'Кебаб',
		fish: 'Рыба',
		sushi: 'Суши',
		bowl: 'Боул',
		seafood: 'Морепродукты',
		risotto: 'Ризотто',
		italian: 'Итальянская кухня',
		mexican: 'Мексиканская кухня',
		chinese: 'Китайская кухня',
		japanese: 'Японская кухня',
		thai: 'Тайская кухня',
		korean: 'Корейская кухня',
		indian: 'Индийская кухня',
		arabic: 'Арабская кухня',
		kosher: 'Кошерная еда',
		halal: 'Халяль',
		breakfast: 'Завтрак',
		lunch: 'Обед',
		gourmetCuisine: 'Гурманская кухня',
		traditional: 'Традиционная кухня',
		healthy: 'Здоровая еда',
		snacksExtras: 'Закуски и дополнения',
		desserts: 'Десерты',
		iceCream: 'Мороженое',
		hotDrinks: 'Горячие напитки',
		pubs: 'Пабы',
		wine: 'Вино',
		cocktail: 'Коктейль',
		drinks: 'Напитки',
		kidsMeals: 'Детские обеды',
		studentMeals: 'Студенческие обеды',
	},
};
let CATEGORIES_FULL = {
	fastFood: { key: 'fastFood', tag: 'fast-food', source: './icons/fast-food.png', name: 'Fast food' },
	pizza: { key: 'pizza', tag: 'pizza', source: './icons/pizza.png', name: 'Pizza' },
	burger: { key: 'burger', tag: 'burger', source: './icons/burger.png', name: 'Burger' },
	salads: { key: 'salads', tag: 'salads', source: './icons/salads.png', name: 'Salads' },
	soups: { key: 'soups', tag: 'soups', source: './icons/ladle.png', name: 'Soups' },
	vegetarian: { key: 'vegetarian', tag: 'vegetarian', source: './icons/vegetarian.png', name: 'Vegetarian' },
	vegan: { key: 'vegan', tag: 'vegan', source: './icons/vegan-2.png', name: 'Vegan' },
	bakery: { key: 'bakery', tag: 'bakery', source: './icons/bakery.png', name: 'Bakeries' },
	sandwiches: { key: 'sandwiches', tag: 'sandwiches', source: './icons/sandwich.png', name: 'Sandwiches' },
	bbq: { key: 'bbq', tag: 'bbq', source: './icons/bbq.png', name: 'BBQ' },
	steak: { key: 'steak', tag: 'steak', source: './icons/meat.png', name: 'Steak' },
	chicken: { key: 'chicken', tag: 'chicken', source: './icons/chicken.png', name: 'Chicken' },
	kebab: { key: 'kebab', tag: 'kebab', source: './icons/kebab.png', name: 'Kebab' },
	fish: { key: 'fish', tag: 'fish', source: './icons/fish.png', name: 'Fish' },
	sushi: { key: 'sushi', tag: 'sushi', source: './icons/sushi.png', name: 'Sushi' },
	bowl: { key: 'bowl', tag: 'bowl', source: './icons/poke-bowl.png', name: 'Poke bowl' },
	seafood: { key: 'seafood', tag: 'seafood', source: './icons/seafood.png', name: 'Seafood' },
	risotto: { key: 'risotto', tag: 'risotto', source: './icons/risotto.png', name: 'Risotto' },
	italian: { key: 'italian', tag: 'italian', source: './icons/italian.png', name: 'Italian' },
	mexican: { key: 'mexican', tag: 'mexican', source: './icons/mexican.png', name: 'Mexican' },
	chinese: { key: 'chinese', tag: 'chinese', source: './icons/chinese.png', name: 'Chinese' },
	japanese: { key: 'japanese', tag: 'japanese', source: './icons/japanese-food.png', name: 'Japanese' },
	thai: { key: 'thai', tag: 'thai', source: './icons/thai.png', name: 'Thai' },
	korean: { key: 'korean', tag: 'korean', source: './icons/korean.png', name: 'Korean' },
	indian: { key: 'indian', tag: 'indian', source: './icons/indian.png', name: 'Indian' },
	arabic: { key: 'arabic', tag: 'arabic', source: './icons/arabic.png', name: 'Arabic' },
	kosher: { key: 'kosher', tag: 'kosher', source: './icons/kosher.png', name: 'Kosher' },
	halal: { key: 'halal', tag: 'halal', source: './icons/halal.png', name: 'Halal' },
	breakfast: { key: 'breakfast', tag: 'breakfast', source: './icons/breakfast.png', name: 'Breakfast' },
	lunch: { key: 'lunch', tag: 'lunch', source: './icons/dish.png', name: 'Lunch' },
	gourmetCuisine: {
		key: 'gourmetCuisine',
		tag: 'gourmet-cuisine',
		source: './icons/fine-dining.png',
		name: 'Fine dining',
	},
	traditional: { key: 'traditional', tag: 'traditional', source: './icons/traditional.png', name: 'Traditional' },
	healthy: { key: 'healthy', tag: 'healthy', source: './icons/healthy-food.png', name: 'Healthy' },
	snacksExtras: { key: 'snacksExtras', tag: 'extras', source: './icons/snacks_extras.png', name: 'Snacks & extras' },
	desserts: { key: 'desserts', tag: 'desserts', source: './icons/dessert.png', name: 'Desserts' },
	iceCream: { key: 'iceCream', tag: 'ice-cream', source: './icons/ice-cream.png', name: 'Ice cream' },
	hotDrinks: { key: 'hotDrinks', tag: 'hot-drinks', source: './icons/hot-drinks.png', name: 'Coffee & Tea' },
	pubs: { key: 'pubs', tag: 'pubs', source: './icons/pub.png', name: 'Pubs' },
	wine: { key: 'wine', tag: 'wine', source: './icons/wine.png', name: 'Wine' },
	cocktail: { key: 'cocktail', tag: 'cocktail', source: './icons/cocktail.png', name: 'Cocktails' },
	drinks: { key: 'drinks', tag: 'soft-drinks', source: './icons/drinks.png', name: 'Soft drinks' },
	kidsMeals: { key: 'kidsMeals', tag: 'kids-meals', source: './icons/kids-meals.png', name: 'Kids meals' },
	studentMeals: {
		key: 'studentMeals',
		tag: 'student-meals',
		source: './icons/icon-student.png',
		name: 'Student meals',
	},
};
async function seedCategories() {
	console.log('Seeding categories...');
	for (let key in CATEGORIES_FULL) {
		console.log(`Seeding category: ${key}`);
		let category = CATEGORIES_FULL[key];
		let translations = [];
		for (let lang in languages) {
			translations.push({
				language: lang,
				translation: languages[lang][key],
			});
		}
		const imagePath = path.resolve(__dirname, category.source);
		let base64 = null;
		try {
			if (fs.existsSync(imagePath)) {
				const imageBuffer = fs.readFileSync(imagePath);
				base64 = `data:image/png;base64,${imageBuffer.toString('base64')}`;
			} else {
				console.warn(`File not found: ${imagePath}`);
			}
		} catch (error) {
			console.error(`Error processing ${imagePath}:`, error);
		}
		let categoryObj = {
			categoryData: {
				name: category.name,
				description: category.name,
				category_type: 'MENU',
				tag: category.tag,
			},
			translations: translations,
			iconFileData: {
				file_type: 'IMAGE',
				mime_type: 'image/png',
				base64: base64,
			},
			parent_categories_id: null,
			subcategories: [],
		};
		try {
			let categoryExists = await prisma.categories.findUnique({
				where: {
					tag_category_type: {
						tag: categoryObj.categoryData.tag,
						category_type: categoryObj.categoryData.category_type,
					},
				},
				include: {
					icon: true,
				},
			});
			let category_id = categoryExists?.categories_id;
			if (categoryExists) {
				console.log(`Category ${categoryExists.tag} already exists.`);
			} else {
				const cat = await CategoriesDao.createCategory(
					categoryObj.categoryData,
					categoryObj.translations,
					categoryObj.subcategories,
					[],
					categoryObj.parent_categories_id,
					categoryObj.iconFileData
				);
				category_id = cat.categories_id;
				if (categoryObj.iconFileData) {
					const { file_type, mime_type, base64 } = categoryObj.iconFileData;
					await upsertFileOnS3Helper(null, cat.icon, file_type, mime_type, base64);
				}
				console.log(`Category ${cat.categories_id} created.`);
			}
			let wordObj = {
				wordData: {
					word: categoryObj.categoryData.name,
					categories_id: category_id,
				},
				translations: translations,
			};
			let wordExists = await prisma.words.findUnique({
				where: {
					word: wordObj.wordData.word,
				},
			});
			if (wordExists) {
				let updatedWord = await prisma.words.update({
					where: {
						word: wordObj.wordData.word,
					},
					data: {
						category: {
							connect: {
								categories_id: category_id,
							},
						},
					},
				});
				console.log(`word ${wordExists.tag} already exists.`);
			} else {
				const word = await WordDao.createWord(
					wordObj.wordData.word,
					wordObj.wordData.categories_id,
					wordObj.translations
				);
				console.log(`Word ${word.word_id} created.`);
			}
		} catch (error) {
			console.log('Error creating category and word:', error);
		}
	}
	console.log('Categories seeded.');
}
export default seedCategories;
