-- CreateEnum
CREATE TYPE "BLOG_POST_STATUS" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

-- AlterTable
ALTER TABLE "blog_posts" ADD COLUMN     "status" "BLOG_POST_STATUS" NOT NULL DEFAULT 'PUBLISHED';
