http.host: '0.0.0.0'
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: '${ELASTIC_USERNAME}'
xpack.monitoring.elasticsearch.password: '${ELASTIC_PASSWORD}'
xpack.monitoring.elasticsearch.hosts: ['http://klikni_elasticsearch:9200']
