/**
 * Mock Prisma client for integration tests
 * Provides sample data for testing DAO → Mapper → Zod validation flow
 */

export const mockPrismaData = {
	business: {
		business_id: '550e8400-e29b-41d4-a716-446655440001',
		address_id: '550e8400-e29b-41d4-a716-446655440002',
		is_business_unit: false,
		business_group_name: null,
		tax_id: 'SI12345678',
		registration_id: '1234567',
		email: 'test@business.com',
		telephone: '12345678',
		telephone_code: '+386',
		website_url: 'https://testbusiness.com',
		working_hours: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		parent_business_id: null,
		stripe_account_id: null,
		stripe_customer_id: null,
		word_buy_stripe_subscription_id: null,
		first_activated_at: new Date('2024-01-01'),
		active: true,
		sales_representative_id: null,
		types: ['FOOD_DRINKS' as const],
		business_details_id: '550e8400-e29b-41d4-a716-446655440003',
		business_details: {
			business_details_id: '550e8400-e29b-41d4-a716-446655440003',
			business_id: '550e8400-e29b-41d4-a716-446655440001',
			name: 'Test Business',
			description: 'Test business description',
			logo_id: null,
			banner_id: null,
			logo: null,
			banner: null,
			created_at: new Date('2024-01-01'),
			updated_at: new Date('2024-01-01'),
		},
		address: {
			address_id: '550e8400-e29b-41d4-a716-446655440002',
			street: 'Test Street',
			house_number: '123',
			city: 'Ljubljana',
			postal: '1000',
			country: 'Slovenia',
			latitude: 46.0569,
			longitude: 14.5058,
			created_at: new Date('2024-01-01'),
			updated_at: new Date('2024-01-01'),
		},
		business_users: [],
	},

	user: {
		user_id: '550e8400-e29b-41d4-a716-446655440010',
		first_name: 'John',
		last_name: 'Doe',
		password: '$2b$10$mockHashedPassword',
		email: 'test@user.com',
		telephone: '40123456',
		telephone_code: '+386',
		date_of_birth: new Date('1990-01-15'),
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		user_role: 'PERSONAL' as const,
		phone_verified: true,
		notification_preferences: null,
		taxi_preferences: null,
		spicy_preferences: null,
		transfer_preferences: null,
		radio_preferences: null,
		allergies_preferences: null,
		delivery_push_notification_preferences: null,
		transfer_push_notification_preferences: null,
		taxi_push_notification_preferences: null,
		profile_picture_id: null,
		reviewable_id: null,
		review_complete: true,
		one_signal_id: null,
		stripe_customer_id: null,
		wallet_balance: 0,
		subscribed_to_daily_meals: false,
		daily_meal_preferences: null,
		details: null,
		spoken_languages: null,
		daily_meal_day_preferences: [],
		disabled: false,
		active: true,
		language: 'en',
		apple_id: null,
		google_id: null,
		referral_code: 'ABC123',
		activated_at: null,
		deactivated_at: null,
		deactivated: false,
		business_teams_id: null,
		allow_marketing_push_notifications: false,
		allow_ads_personalization: false,
		allow_newsletter: false,
		user_favorite_service_links: [],
		profile_picture: null,
		driver: null,
	},

	businessUser: {
		business_users_id: '550e8400-e29b-41d4-a716-446655440020',
		business_id: '550e8400-e29b-41d4-a716-446655440001',
		user_id: '550e8400-e29b-41d4-a716-446655440010',
		online: false,
		company_role: 'DIRECTOR' as const,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		operating_address_id: null,
		users: {
			user_id: '550e8400-e29b-41d4-a716-446655440010',
			first_name: 'Jane',
			last_name: 'Smith',
			email: 'jane@business.com',
		},
		operating_address: null,
		allowance: null,
	},
	// Auto-generated mock data (2025-11-21T10:56:40.178Z)
	actiondefault: {
		action_id: '550e8400-e29b-41d4-a716-446655440030',
		module: 'RESERVATION' as const,
		name: 'Test Action',
		icon: null,
		description: null,
		display_name: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	addondefault: {
		addon_id: '550e8400-e29b-41d4-a716-446655440031',
		module: 'RESERVATION' as const,
		name: 'Premium Support',
		price_cents: 1000,
		stripe_price_id: 'price_test123',
		stripe_product_id: 'prod_test123',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	addon: {
		addon_id: '550e8400-e29b-41d4-a716-446655440032',
		module: 'RESERVATION' as const,
		name: 'Extra Feature',
		price_cents: 500,
		stripe_price_id: 'price_test456',
		stripe_product_id: 'prod_test456',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessaddon: {
		addon_id: '550e8400-e29b-41d4-a716-446655440033',
		module: 'FOOD_DRINKS' as const,
		name: 'Business Addon',
		price_cents: 2000,
		stripe_price_id: 'price_test789',
		stripe_product_id: 'prod_test789',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	addressdefault: {
		address_id: '550e8400-e29b-41d4-a716-446655440040',
		street: 'Main Street',
		house_number: '42',
		city: 'Ljubljana',
		country: 'Slovenia',
		postal: '1000',
		latitude: 46.0569,
		longitude: 14.5058,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessbyid: {
		name: 'Test name',
		description: 'Test Business description',
		logo: 'mock_logo_value',
		banner: 'mock_banner_value',
		business_id: 'mock-businessbyid-business_id-001',
		tax_id: 'mock-businessbyid-tax_id-001',
		registration_id: 'mock-businessbyid-registration_id-001',
		email: 'test@businessbyid.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		website_url: 'https://example.com/website_url',
		working_hours: 'mock_working_hours_value',
		daily_meal_drivers: 'mock_daily_meal_drivers_value',
		id: 'mock-businessbyid-001',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		maximum_daily_meals_subscribers: 'mock_maximum_daily_meals_subscribers_value',
		daily_meals_days: 'mock_daily_meals_days_value',
		daily_users_sorting_type: 'mock_daily_users_sorting_type_value',
		daily_users_sorted: 'mock_daily_users_sorted_value',
		daily_meals_delivery_mapping: 'mock_daily_meals_delivery_mapping_value',
		crm_module_id: 'mock-businessbyid-crm_module_id-001',
		purchase_order_limit_amount: 100,
		business_clients: 'mock_business_clients_value',
	},

	any: {
		name: 'Test name',
		description: 'Test Business description',
		logo: 'mock_logo_value',
		banner: 'mock_banner_value',
		business_id: 'mock-any-business_id-001',
		tax_id: 'mock-any-tax_id-001',
		registration_id: 'mock-any-registration_id-001',
		email: 'test@any.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		website_url: 'https://example.com/website_url',
		working_hours: 'mock_working_hours_value',
		daily_meal_drivers: 'mock_daily_meal_drivers_value',
		id: 'mock-any-001',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		maximum_daily_meals_subscribers: 'mock_maximum_daily_meals_subscribers_value',
		daily_meals_days: 'mock_daily_meals_days_value',
		daily_users_sorting_type: 'mock_daily_users_sorting_type_value',
		daily_users_sorted: 'mock_daily_users_sorted_value',
		daily_meals_delivery_mapping: 'mock_daily_meals_delivery_mapping_value',
		crm_module_id: 'mock-any-crm_module_id-001',
		purchase_order_limit_amount: 100,
		business_clients: 'mock_business_clients_value',
	},

	businessclientdefault: {
		business_clients_id: '550e8400-e29b-41d4-a716-446655440120',
		crm_module_id: '550e8400-e29b-41d4-a716-446655440121',
		first_name: 'Bob',
		last_name: 'Client',
		email: 'bob@client.com',
		telephone: '40987654',
		telephone_code: '+386',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessclientdetail: {
		business_clients_id: '550e8400-e29b-41d4-a716-446655440122',
		crm_module_id: '550e8400-e29b-41d4-a716-446655440121',
		first_name: 'Carol',
		last_name: 'Detail',
		email: 'carol@detail.com',
		telephone: '40111222',
		telephone_code: '+386',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessteamdefault: {
		business_teams_id: '550e8400-e29b-41d4-a716-446655440100',
		team_name: 'Sales Team',
		business_id: '550e8400-e29b-41d4-a716-446655440001',
		limit_per_person: 1000.0,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessteam: {
		business_teams_id: '550e8400-e29b-41d4-a716-446655440101',
		team_name: 'Support Team',
		business_id: '550e8400-e29b-41d4-a716-446655440001',
		limit_per_person: 500.0,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	businessuserdefault: {
		business_users_id: '550e8400-e29b-41d4-a716-446655440110',
		business_id: '550e8400-e29b-41d4-a716-446655440001',
		user_id: '550e8400-e29b-41d4-a716-446655440010',
		company_role: 'EMPLOYEE' as const,
		online: false,
		operating_address_id: null,
		users: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	category: {
		categories_id: '550e8400-e29b-41d4-a716-446655440070',
		name: 'Food Category',
		tag: 'FOOD',
		category_type: 'MENU' as const,
		file_id: null,
		description: 'Test Category description',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	unknown: null, // Generic placeholder - override with specific data as needed

	dailymealcategory: {
		daily_meal_category_price_id: 'mock-dailymealcategory-daily_meal_category_price_id-001',
		daily_meal_category_id: 'mock-dailymealcategory-daily_meal_category_id-001',
		price: 100,
		valid_from: 'mock_valid_from_value',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		id: 'mock-dailymealcategory-001',
		business_id: 'mock-dailymealcategory-business_id-001',
		category_id: 'mock-dailymealcategory-category_id-001',
		start_date: 'mock_start_date_value',
		active: true,
		daily_meals_id: 'mock-dailymealcategory-daily_meals_id-001',
		category: 'mock_category_value',
		daily_meals_module: 'mock_daily_meals_module_value',
		daily_meal_category_prices_id: 'mock-dailymealcategory-daily_meal_category_prices_id-001',
	},

	dailymealinstance: {
		id: 'mock-dailymealinstance-001',
		subscription_id: 'mock-dailymealinstance-subscription_id-001',
		subscription_customer_id: 'mock-dailymealinstance-subscription_customer_id-001',
		menu_category_id: 'mock-dailymealinstance-menu_category_id-001',
		status: 'mock_status_value',
		daily_meal_category_price_id: 'mock-dailymealinstance-daily_meal_category_price_id-001',
		subscription: 'mock_subscription_value',
		customer: 'mock_customer_value',
		menu_category: 'mock_menu_category_value',
		daily_meal_category_price: 100,
	},

	document: {
		document_id: '550e8400-e29b-41d4-a716-446655440050',
		business_id: null,
		driver_id: null,
		vehicle_id: null,
		document_type: 'DRIVERS_LICENSE' as const,
		additional_info: null,
		expiration_date: new Date('2025-12-31'),
		issue_date: new Date('2020-01-01'),
		public: false,
		transaction_id: null,
		order_id: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	file: {
		file_id: '550e8400-e29b-41d4-a716-446655440060',
		url: 'https://example.com/test-image.jpg',
		file_type: 'IMAGE' as const,
		public: true,
		mime_type: 'image/jpeg',
		document_id: null,
		user_id: null,
		driver_id: null,
		lost_item_id: null,
		delivery_order_id: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	fooddrinks: {
		food_drinks_id: 'mock-fooddrinks-food_drinks_id-001',
		business_id: 'mock-fooddrinks-business_id-001',
		enabled: true,
		online: 'mock_online_value',
		overwhelmed: 'mock_overwhelmed_value',
		minimum_order: 'mock_minimum_order_value',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		id: 'mock-fooddrinks-001',
	},

	// Simplified placeholders - override with actual data when needed
	businesspremise: {},
	menuitempayload: {
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
	menupayload: {
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
	dailymealmenupayload: {
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
	menucategory: {
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
	payment: {
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
	scoringpoints: {},

	bookingbaseprismaresult: {
		booking_id: 'mock-bookingbaseprismaresult-booking_id-001',
		customer_id: 'mock-bookingbaseprismaresult-customer_id-001',
		reservation_module_id: 'mock-bookingbaseprismaresult-reservation_module_id-001',
		location_id: 'mock-bookingbaseprismaresult-location_id-001',
		status: 'mock_status_value',
		service_id: 'mock-bookingbaseprismaresult-service_id-001',
		comment: 'mock_comment_value',
		price_cents: 100,
		discount_percent: 1,
		discount_amount: 100,
	},

	bookingbase: {
		booking_id: 'mock-bookingbase-booking_id-001',
		customer_id: 'mock-bookingbase-customer_id-001',
		reservation_module_id: 'mock-bookingbase-reservation_module_id-001',
		location_id: 'mock-bookingbase-location_id-001',
		status: 'mock_status_value',
		service_id: 'mock-bookingbase-service_id-001',
		comment: 'mock_comment_value',
		price_cents: 100,
		discount_percent: 1,
		discount_amount: 100,
	},

	booking: {
		booking_id: 'mock-booking-booking_id-001',
		customer_id: 'mock-booking-customer_id-001',
		reservation_module_id: 'mock-booking-reservation_module_id-001',
		location_id: 'mock-booking-location_id-001',
		status: 'mock_status_value',
		service_id: 'mock-booking-service_id-001',
		comment: 'mock_comment_value',
		price_cents: 100,
		discount_percent: 1,
		discount_amount: 100,
	},

	bookingcoursessimple: {
		booking_id: 'mock-bookingcoursessimple-booking_id-001',
		customer_id: 'mock-bookingcoursessimple-customer_id-001',
		reservation_module_id: 'mock-bookingcoursessimple-reservation_module_id-001',
		location_id: 'mock-bookingcoursessimple-location_id-001',
		status: 'mock_status_value',
		service_id: 'mock-bookingcoursessimple-service_id-001',
		comment: 'mock_comment_value',
		price_cents: 100,
		discount_percent: 1,
		discount_amount: 100,
	},

	bookingcoursetimebase: {
		booking_course_time_id: 'mock-bookingcoursetimebase-booking_course_time_id-001',
		reservation_module_id: 'mock-bookingcoursetimebase-reservation_module_id-001',
		booking_id: 'mock-bookingcoursetimebase-booking_id-001',
		booking: 'mock_booking_value',
		status: 'mock_status_value',
		reservation_module: 'mock_reservation_module_value',
		business_id: 'mock-bookingcoursetimebase-business_id-001',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		id: 'mock-bookingcoursetimebase-001',
	},

	bookinghistorylogbase: {
		booking_history_id: 'mock-bookinghistorylogbase-booking_history_id-001',
		booking_id: 'mock-bookinghistorylogbase-booking_id-001',
		status: 'mock_status_value',
		comment: 'mock_comment_value',
		type: 'mock_type_value',
		title: 'mock_title_value',
		description: 'Test booking-history-log description',
		user_id: 'mock-bookinghistorylogbase-user_id-001',
		booking: 'mock_booking_value',
		created_at: new Date('2024-01-01'),
	},

	bookingslotbase: {
		booking_slot_id: 'mock-bookingslotbase-booking_slot_id-001',
		schedule_slot_id: 'mock-bookingslotbase-schedule_slot_id-001',
		schedule_slot: 'mock_schedule_slot_value',
		id: 'mock-bookingslotbase-001',
	},

	customerbase: {
		customer_id: 'mock-customerbase-customer_id-001',
		reservation_module_id: 'mock-customerbase-reservation_module_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@customerbase.com',
		telephone: '+38640123456',
		code: 'mock_code_value',
		user_id: 'mock-customerbase-user_id-001',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	employeebase: {
		employee_id: 'mock-employeebase-employee_id-001',
		reservation_module_id: 'mock-employeebase-reservation_module_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@employeebase.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		business_users_id: 'mock-employeebase-business_users_id-001',
		deleted_at: null,
		business_user: 'mock_business_user_value',
	},

	employee: {
		employee_id: 'mock-employee-employee_id-001',
		reservation_module_id: 'mock-employee-reservation_module_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@employee.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		business_users_id: 'mock-employee-business_users_id-001',
		deleted_at: null,
		business_user: 'mock_business_user_value',
	},

	locationbase: {
		location_id: 'mock-locationbase-location_id-001',
		reservation_module_id: 'mock-locationbase-reservation_module_id-001',
		name: 'Test name',
		address_id: 'mock-locationbase-address_id-001',
		phone: '+38640123456',
		color: 'mock_color_value',
		accepts_online: 'mock_accepts_online_value',
		closed_on_holidays: 'mock_closed_on_holidays_value',
		working_days: 'mock_working_days_value',
		address: 'mock_address_value',
	},

	location: {
		location_id: 'mock-location-location_id-001',
		reservation_module_id: 'mock-location-reservation_module_id-001',
		name: 'Test name',
		address_id: 'mock-location-address_id-001',
		phone: '+38640123456',
		color: 'mock_color_value',
		accepts_online: 'mock_accepts_online_value',
		closed_on_holidays: 'mock_closed_on_holidays_value',
		working_days: 'mock_working_days_value',
		address: 'mock_address_value',
	},

	notificationeventbase: {
		notification_event_id: 'mock-notificationeventbase-notification_event_id-001',
		key: 'mock_key_value',
		name: 'Test name',
		description: 'Test notification-event description',
		id: 'mock-notificationeventbase-001',
	},

	notificationmappingbase: {
		notification_mapping_id: 'mock-notificationmappingbase-notification_mapping_id-001',
		reservation_module_id: 'mock-notificationmappingbase-reservation_module_id-001',
		notification_event_id: 'mock-notificationmappingbase-notification_event_id-001',
		notification_template_version_id: 'mock-notificationmappingbase-notification_template_version_id-001',
		conditions: 'mock_conditions_value',
		is_active: true,
		created_at: new Date('2024-01-01'),
		id: 'mock-notificationmappingbase-001',
	},

	notificationmessagebase: {
		notification_message_id: 'mock-notificationmessagebase-notification_message_id-001',
		reservation_module_id: 'mock-notificationmessagebase-reservation_module_id-001',
		notification_event_id: 'mock-notificationmessagebase-notification_event_id-001',
		channel: 'mock_channel_value',
		notification_template_id: 'mock-notificationmessagebase-notification_template_id-001',
		template_version: 'mock_template_version_value',
		to_address: 'mock_to_address_value',
		subject: 'mock_subject_value',
		body_text: 'mock_body_text_value',
		body_html: 'mock_body_html_value',
	},

	notificationtemplatebase: {
		notification_template_id: 'mock-notificationtemplatebase-notification_template_id-001',
		reservation_module_id: 'mock-notificationtemplatebase-reservation_module_id-001',
		key: 'mock_key_value',
		name: 'Test name',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		id: 'mock-notificationtemplatebase-001',
	},

	reservationmodulebase: {
		reservation_module_id: 'mock-reservationmodulebase-reservation_module_id-001',
		business_id: 'mock-reservationmodulebase-business_id-001',
		public_link_hash: 'https://example.com/public_link_hash',
		action_bundle_id: 'mock-reservationmodulebase-action_bundle_id-001',
		stripe_subscription_schedule_id: 'mock-reservationmodulebase-stripe_subscription_schedule_id-001',
		hours_before_reschedule: 'mock_hours_before_reschedule_value',
		hours_before_cancel: 'mock_hours_before_cancel_value',
		publicly_visible: 'mock_publicly_visible_value',
		id: 'mock-reservationmodulebase-001',
	},

	schedulebase: {
		schedule_id: 'mock-schedulebase-schedule_id-001',
		location_id: 'mock-schedulebase-location_id-001',
		name: 'Test name',
		color: 'mock_color_value',
		location: 'mock_location_value',
		id: 'mock-schedulebase-001',
	},

	scheduleemployeebase: {
		schedule_employee_id: 'mock-scheduleemployeebase-schedule_employee_id-001',
		schedule_id: 'mock-scheduleemployeebase-schedule_id-001',
		employee_id: 'mock-scheduleemployeebase-employee_id-001',
		id: 'mock-scheduleemployeebase-001',
	},

	scheduleslotbase: {
		schedule_slot_id: 'mock-scheduleslotbase-schedule_slot_id-001',
		schedule_id: 'mock-scheduleslotbase-schedule_id-001',
		schedule_employee_id: 'mock-scheduleslotbase-schedule_employee_id-001',
		employee_id: 'mock-scheduleslotbase-employee_id-001',
		id: 'mock-scheduleslotbase-001',
	},

	scheduleslotexceptionbase: {
		schedule_slot_exception_id: 'mock-scheduleslotexceptionbase-schedule_slot_exception_id-001',
		schedule_slot_id: 'mock-scheduleslotexceptionbase-schedule_slot_id-001',
		reason: 'mock_reason_value',
		type: 'mock_type_value',
		id: 'mock-scheduleslotexceptionbase-001',
	},

	servicebase: {
		service_id: 'mock-servicebase-service_id-001',
		reservation_module_id: 'mock-servicebase-reservation_module_id-001',
		service_category_id: 'mock-servicebase-service_category_id-001',
		name: 'Test name',
		description: 'Test service description',
		image_url: 'https://example.com/image_url',
		price_cents: 100,
		discount_percent: 1,
		discount_amount: 100,
		duration_minutes: 'mock_duration_minutes_value',
	},

	serviceassignmentbase: {
		service_id: 'mock-serviceassignmentbase-service_id-001',
		employee_id: 'mock-serviceassignmentbase-employee_id-001',
		id: 'mock-serviceassignmentbase-001',
	},

	servicecategorybase: {
		service_category_id: 'mock-servicecategorybase-service_category_id-001',
		reservation_module_id: 'mock-servicecategorybase-reservation_module_id-001',
		name: 'Test name',
		parent_id: 'mock-servicecategorybase-parent_id-001',
		color: 'mock_color_value',
		id: 'mock-servicecategorybase-001',
	},

	servicelocationbase: {
		service_location_id: '550e8400-e29b-41d4-a716-446655440190',
		location_id: '550e8400-e29b-41d4-a716-446655440191',
		service_id: '550e8400-e29b-41d4-a716-446655440192',
	},

	transportmodule: {
		transport_module_id: 'mock-transportmodule-transport_module_id-001',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
		id: 'mock-transportmodule-001',
	},

	useraddress: {
		user_id: 'mock-useraddress-user_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@useraddress.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		date_of_birth: 'mock_date_of_birth_value',
		user_role: 'mock_user_role_value',
		phone_verified: '+38640123456',
		notification_preferences: 'mock_notification_preferences_value',
		addresses: 'mock_addresses_value',
		driver: 'mock_driver_value',
		driver_id: 'mock-useraddress-driver_id-001',
		ride_requirements: 'mock_ride_requirements_value',
		taxi_orders_toggled: 'mock_taxi_orders_toggled_value',
		transfer_orders_toggled: 'mock_transfer_orders_toggled_value',
		delivery_orders_toggled: 'mock_delivery_orders_toggled_value',
		courier_orders_toggled: 'mock_courier_orders_toggled_value',
		transport_module_id: 'mock-useraddress-transport_module_id-001',
		last_used_vehicle_id: 'mock-useraddress-last_used_vehicle_id-001',
		child_users: 'mock_child_users_value',
		parent_user: 'mock_parent_user_value',
		group_user_id: 'mock-useraddress-group_user_id-001',
		child_user_id: 'mock-useraddress-child_user_id-001',
		parent_user_id: 'mock-useraddress-parent_user_id-001',
		enabled: true,
	},

	userlogin: {
		user_id: '550e8400-e29b-41d4-a716-446655440000',
		first_name: 'John',
		last_name: 'Doe',
		email: 'john.doe@example.com',
		telephone: '40123456',
		telephone_code: '+386',
		date_of_birth: new Date('1990-01-15'),
		user_role: 'USER',
		phone_verified: true,
		notification_preferences: null,
		taxi_preferences: null,
		spicy_preferences: null,
		transfer_preferences: null,
		radio_preferences: null,
		allergies_preferences: null,
		delivery_push_notification_preferences: null,
		transfer_push_notification_preferences: null,
		taxi_push_notification_preferences: null,
		profile_picture_id: null,
		reviewable_id: null,
		review_complete: false,
		one_signal_id: null,
		stripe_customer_id: null,
		wallet_balance: 0,
		subscribed_to_daily_meals: false,
		language: 'en',
		details: null,
		referral_code: 'JOHNDOE123',
		allow_marketing_push_notifications: true,
		allow_ads_personalization: false,
		allow_newsletter: true,
		active: true,
		disabled: false,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-06-01'),
		// Relations for login
		addresses: [],
		driver: null,
		child_users: [],
		parent_user: null,
		referrals_made: [],
		referral: null,
		user_roles: [
			{
				user_roles_id: '660e8400-e29b-41d4-a716-446655440001',
				role: 'PERSONAL' as const,
				primary: true,
			},
		],
		business_users: [],
		user_favorite_businesses: [],
		user_favorite_drivers: [],
		profile_picture: null,
	},

	useraddressesandconnectionscreation: {
		user_id: 'mock-useraddressesandconnectionscreation-user_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@useraddressesandconnectionscreation.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		date_of_birth: 'mock_date_of_birth_value',
		user_role: 'mock_user_role_value',
		phone_verified: '+38640123456',
		notification_preferences: 'mock_notification_preferences_value',
		addresses: 'mock_addresses_value',
		driver: 'mock_driver_value',
		driver_id: 'mock-useraddressesandconnectionscreation-driver_id-001',
		ride_requirements: 'mock_ride_requirements_value',
		taxi_orders_toggled: 'mock_taxi_orders_toggled_value',
		transfer_orders_toggled: 'mock_transfer_orders_toggled_value',
		delivery_orders_toggled: 'mock_delivery_orders_toggled_value',
		courier_orders_toggled: 'mock_courier_orders_toggled_value',
		transport_module_id: 'mock-useraddressesandconnectionscreation-transport_module_id-001',
		last_used_vehicle_id: 'mock-useraddressesandconnectionscreation-last_used_vehicle_id-001',
		child_users: 'mock_child_users_value',
		parent_user: 'mock_parent_user_value',
		group_user_id: 'mock-useraddressesandconnectionscreation-group_user_id-001',
		child_user_id: 'mock-useraddressesandconnectionscreation-child_user_id-001',
		parent_user_id: 'mock-useraddressesandconnectionscreation-parent_user_id-001',
		enabled: true,
	},

	useraddressdefault: {
		user_id: 'mock-useraddressdefault-user_id-001',
		address_id: 'mock-useraddressdefault-address_id-001',
		primary: 'mock_primary_value',
		details: 'mock_details_value',
		type: 'mock_type_value',
		id: 'mock-useraddressdefault-001',
	},

	favoritedriverdetail: {
		user_id: 'mock-favoritedriverdetail-user_id-001',
		first_name: 'Test first name',
		last_name: 'Test last name',
		email: 'test@favoritedriverdetail.com',
		telephone: '+38640123456',
		telephone_code: '+38640123456',
		date_of_birth: 'mock_date_of_birth_value',
		user_role: 'mock_user_role_value',
		phone_verified: '+38640123456',
		notification_preferences: 'mock_notification_preferences_value',
	},
	// Auto-generated mock data (2025-11-21T10:58:27.755Z)
	customer: {
		customer_id: '550e8400-e29b-41d4-a716-446655440080',
		reservation_module_id: '550e8400-e29b-41d4-a716-446655440081',
		first_name: 'Alice',
		last_name: 'Customer',
		email: 'alice@customer.com',
		telephone: '40123456',
		telephone_code: '+386',
		code: 'CUST01',
		user_id: null,
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},

	subscription: {
		action_bundle_id: '550e8400-e29b-41d4-a716-446655440090',
		module: 'RESERVATION' as const,
		name: 'Premium Plan',
		description: 'Premium subscription plan',
		price_cents: 2999,
		interval: 'MONTHLY' as const,
		stripe_price_id: 'price_premium123',
		stripe_product_id: 'prod_premium123',
		created_at: new Date('2024-01-01'),
		updated_at: new Date('2024-01-01'),
	},
};

/**
 * Create a mock Prisma client that returns predefined data
 */
export function createMockPrisma() {
	return {
		business: {
			findFirst: jest.fn().mockResolvedValue(mockPrismaData.business),
			findUnique: jest.fn().mockResolvedValue(mockPrismaData.business),
			findMany: jest.fn().mockResolvedValue([mockPrismaData.business]),
		},
		users: {
			findFirst: jest.fn().mockResolvedValue(mockPrismaData.user),
			findUnique: jest.fn().mockResolvedValue(mockPrismaData.user),
			findMany: jest.fn().mockResolvedValue([mockPrismaData.user]),
		},
		business_users: {
			findFirst: jest.fn().mockResolvedValue(mockPrismaData.businessUser),
			findUnique: jest.fn().mockResolvedValue(mockPrismaData.businessUser),
			findMany: jest.fn().mockResolvedValue([mockPrismaData.businessUser]),
		},
		$disconnect: jest.fn().mockResolvedValue(undefined),
	} as any;
}
