
services:
  klikni_elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: "8.17.1"
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms1g -Xmx2g  # ✅ set min and max heap size
    ports:
      - "127.0.0.1:9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          cpus: "0.6"  # Limit Elasticsearch to use a maximum of 50% of one CPU core
          memory: 2g  # ✅ hard limit at Docker level
        reservations:
          cpus: "0.2"  # Reserve 20% of one CPU core for Elasticsearch
          memory: 1g
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: kibana
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: "http://klikni_elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "${KIBANA_USERNAME}"
      ELASTICSEARCH_PASSWORD: "${KIBANA_PASSWORD}"
      SERVER_BASEPATH: "/kibana"
      SERVER_REWRITEBASEPATH: "true"
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - shared_network
    depends_on:
      - klikni_elasticsearch
      - init
    env_file:
      - ../.env
    volumes:
      - shared-init-status:/init-status
      - ./kibana/wait-for-init.sh:/wait-for-init.sh:ro
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    entrypoint: ["/bin/sh", "/wait-for-init.sh"]
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.1
    container_name: filebeat
    user: root
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${FILEBEAT_USERNAME}
      - ELASTICSEARCH_PASSWORD=${FILEBEAT_PASSWORD}
    volumes:
      - ./filebeat/filebeat.template.yml:/usr/share/filebeat/filebeat.template.yml:ro
      - ./filebeat/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./filebeat/modules.d/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml:ro
      - ./pm2-logs:/pm2-logs:ro
      - /var/log/nginx:/nginx-logs:ro
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["-e", "--strict.perms=false", "-d", "*"]
    networks:
      - shared_network
  init:
    image: bash:5.1
    volumes:
      - ./elasticsearch/scripts/init.sh:/init.sh:ro
      - shared-init-status:/init-status
    env_file:
      - ../.env
    depends_on:
      - klikni_elasticsearch
    entrypoint: ["sh", "-c", "rm -f /init-status/init-complete.lock && apk add --no-cache bash curl && bash /init.sh"]
    networks:
      - shared_network
      
  filebeat_setup:
    image: docker.elastic.co/beats/filebeat:8.17.1
    container_name: filebeat_setup
    user: root
    depends_on:
      - klikni_elasticsearch
      - kibana
    env_file:
      - ../.env
    volumes:
      - ./filebeat/filebeat.template.yml:/usr/share/filebeat/filebeat.template.yml:ro
      - ./filebeat/modules.d/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml:ro
      - ./filebeat/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./filebeat/wait-for-it.sh:/usr/local/bin/wait-for-it.sh:ro
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "kibana", "5601", "--", "/usr/local/bin/entrypoint.sh"]
    command: ["setup", "--dashboards", "-e"]
    networks:
      - shared_network
  # apm-server:
  #   image: docker.elastic.co/apm/apm-server:8.17.1
  #   container_name: apm-server
  #   env_file:
  #     - ../.env
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://klikni_elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
  #     - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
  #     - KIBANA_HOST=http://kibana:5601
  #   ports:
  #     - "8200:8200"  # Default APM Server port
  #   networks:
  #     - shared_network
  #   depends_on:
  #     - klikni_elasticsearch
  #   volumes:
  #     - ./apm/apm-server.template.yml:/usr/share/apm-server/apm-server.template.yml:ro
  #     - ./apm/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
  #     - shared-init-status:/init-status
  #   entrypoint: ["/usr/local/bin/entrypoint.sh"]
  #   command: ["-e", "--strict.perms=false", "-d", "*"]
networks:
  shared_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  shared-init-status:  # ✅ Add this line