#Volumes
volumes:
  dbdata:
    driver: local

services:
  klikni_elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: "8.17.1"
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts7
    environment:
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "127.0.0.1:9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - shared_network
    deploy:
      resources:
        limits:
          cpus: "0.6"  # Limit Elasticsearch to use a maximum of 50% of one CPU core
        reservations:
          cpus: "0.2"  # Reserve 20% of one CPU core for Elasticsearch
  # elasticsearch-init:
  #   image: curlimages/curl:latest
  #   depends_on:
  #     - klikni_elasticsearch
  #   restart: "no"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock 
  #     - ./elasticsearch/scripts/init.sh:/usr/local/bin/init.sh
  #   command: ["/bin/sh", "-c", "sh /usr/local/bin/init.sh"]
  #   environment:
  #     - ELASTIC_USERNAME=${ELASTIC_USERNAME}
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  #   networks:
  #     - shared_network

networks:
  shared_network:
    driver: bridge
