import express from 'express';

import TaxiOrderController from '../../controllers/TaxiOrderController.js';
import { createOrderSchema } from '../../joi/taxiOrderSchemas.js';
import joi from '../../middleware/joi.js';
const router = express.Router();
router.get('/', TaxiOrderController.getTaxiOrders);
router.get('/today', TaxiOrderController.getTaxiOrdersToday);
router.get('/order/:order_id', TaxiOrderController.getOrder);
router.get('/order/:order_id/available-drivers', TaxiOrderController.getDriversForOrder);
router.post('/orders/pagination/', TaxiOrderController.getTaxiOrdersWithPagination);
router.get('/orders/completed/:driver_id', TaxiOrderController.getCompletedTaxiOrders);
router.get('/orders/completed/user/:user_id', TaxiOrderController.getCompletedTaxiOrdersByUserId);
router.get('/orders/completed/business/:business_id', TaxiOrderController.getCompletedTaxiOrdersByBusinessId);
router.get('/orders/rejected/:driver_id', TaxiOrderController.getRejectedTaxiOrders);
router.get('/orders/canceled/:driver_id', TaxiOrderController.getCanceledTaxiOrders);
router.get('/orders/canceled/user/:user_id', TaxiOrderController.getCanceledTaxiOrdersByUserId);
router.get('/orders/active/driver/:driver_id', TaxiOrderController.getActiveTaxiOrdersByDriverId);
router.get('/orders/active/me/:type', TaxiOrderController.getMyActiveTaxiOrders);
router.get('/orders/active/business_user/:type', TaxiOrderController.getActiveTaxiOrdersForBusinessUser);
router.get('/orders/active/:user_id/:type', TaxiOrderController.getActiveTaxiOrders);
router.get('/orders/driver/:driver_id', TaxiOrderController.getTaxiOrdersByDriverId);
router.post('/transfer_price', TaxiOrderController.requestTransferOrderPrice);
router.post('/order', joi(createOrderSchema), TaxiOrderController.createOrder);
router.get('/orders/scheduled_orders', TaxiOrderController.getScheduledOrders);
router.get('/orders/scheduled_orders/driver/:driver_id', TaxiOrderController.getAcceptedScheduledOrders);
router.get('/orders/scheduled_orders/user/:user_id', TaxiOrderController.getScheduledOrdersByUserId);
router.post('/dispatch-order', joi(createOrderSchema), TaxiOrderController.createDispatchOrder);
router.post('/order/status', TaxiOrderController.updateOrderStatus);
router.post('/order/route', TaxiOrderController.updateTaxiOrderRoute);
router.post('/order/preferences', TaxiOrderController.updateTaxiOrderPreferences);
router.post('/order/pickup_location', TaxiOrderController.updateTaxiOrderPickupLocation);
router.post('/order/delivery_location', TaxiOrderController.updateTaxiOrderDeliveryLocation);
router.post('/order/complete_route', TaxiOrderController.updateCompleteTaxiRoute);
router.post('/order/accept', TaxiOrderController.acceptOrder);
router.post('/order/complete', TaxiOrderController.completeOrder);
router.post('/order/cancel', TaxiOrderController.cancelOrder);
router.post('/order/timeline', TaxiOrderController.updateTaxiOrderTimeline);
router.post('/order/payment', TaxiOrderController.updateTaxiOrderPayment);
router.post('/order/append_driver', TaxiOrderController.appendTaxiDriver);
router.post('/order/reject', TaxiOrderController.rejectOrder);
router.post('/grouped_order/cancel', TaxiOrderController.cancelGroupedOrderByParentId);
router.post('/grouped_order/reject', TaxiOrderController.rejectGroupedOrderByParentId);
router.post('/calculate_transfer_price', TaxiOrderController.calculateTransferPrice);
export default router;
