const USER_ROLE = {
    ADMIN: 'ADMIN',
    BUSINESS_OWNER: 'BUSINESS_OWNER',
    BUSINESS_MANAGER: 'BUSINESS_MANAGER',
    BUSINESS_CARETAKER: 'BUSINESS_CARETAKER',
    BUSINESS_USER: 'BUSINESS_USER',
    PERSONAL: 'PERSONAL',
    DRIVER: 'DRIVER',
    DELIVERY_DRIVER: 'DELIVERY_DRIVER'
}

const TokenType = {
    EMAIL: "EMAIL",
    PHONE_VERIFICATION: "PHONE_VERIFICATION",
    API: "API",
    PASSWORD_RESET: "PASSWORD_RESET"
};

const BUSINESS_TYPE = {
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT",
    BUSINESS: "BUSINESS",
    DISPATCHER: "DISPATCHER",
};

const MERCHANT_TYPE = {
    RESTAURANT: "RESTAURANT",
    BAR: "BAR",
    MARKET: "MARKET",
    STORE: "STORE"
};

const BUSINESS_CATEGORY = {
    TAXI: "TAXI",
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT"
};

const FILE_TYPE = {
    IMAGE: "IMAGE",
    DOCUMENT: "DOCUMENT"
};

const DOCUMENT_TYPE = {
    // USER
    NATIONAL_ID: 'NATIONAL_ID',
    PASSPORT: 'PASSPORT',
    PROFILE_PICTURE: 'PROFILE_PICTURE',

    // PARTNER / DRIVER
    LOGO: 'LOGO',
    BANNER: 'BANNER',
    DRIVING_LICENSE: 'DRIVING_LICENSE',
    TAXI_LICENCE: 'TAXI_LICENCE',
    PASSENGER_TRANSFER_LICENSE: 'PASSENGER_TRANSFER_LICENSE',
    BACKGROUND_CHECK_REPORT: 'BACKGROUND_CHECK_REPORT',
    HEALTH_DECLARATION: 'HEALTH_DECLARATION',

    // VEHICLE
    VEHICLE_REGISTRATION: 'VEHICLE_REGISTRATION',
    VEHICLE_INSURANCE: 'VEHICLE_INSURANCE',
    VEHICLE_TECHNICAL_INSPECTION: 'VEHICLE_TECHNICAL_INSPECTION',

    // MERCHANT
    OPERATING_PERMIT: 'OPERATING_PERMIT',
    HACCP_CERTIFICATION: 'HACCP_CERTIFICATION',
    BUSINESS_LICENSE: 'BUSINESS_LICENSE',

    // MENU_ITEM
    MENU_ITEM_IMAGE: 'MENU_ITEM_IMAGE',

    WALLET_TOPUP: 'WALLET_TOPUP',
};

const TAXI_ORDER_STATUS = {
    PENDING: "PENDING",
    TAXI_ACCEPTED: "TAXI_ACCEPTED",
    TAXI_REJECTED: "TAXI_REJECTED",
    TAXI_CANCELED: "TAXI_CANCELED",
    CUSTOMER_CANCELED: "CUSTOMER_CANCELED",
    TAXI_WAITING: "TAXI_WAITING",
    TAXI_DRIVING: "TAXI_DRIVING",
    TAXI_ARRIVED: "TAXI_ARRIVED",
    TAXI_COMPLETED: "TAXI_COMPLETED",
};

const TRANSFER_ORDER_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'TRANSFER_ACCEPTED',
    COMPLETED: 'TRANSFER_COMPLETED',
}

const DELIVERY_ORDER_STATUS = {
    PENDING: "PENDING",
    DELIVERY_ACCEPTED: "DELIVERY_ACCEPTED",
    DELIVERY_REJECTED: "DELIVERY_REJECTED",
    DELIVERY_CANCELED: "DELIVERY_CANCELED",
    DELIVERY_PICKED_UP: "DELIVERY_PICKED_UP",
    DELIVERY_IN_DELIVERY: "DELIVERY_IN_DELIVERY",
    DELIVERY_DELAYED: "DELIVERY_DELAYED",
    DELIVERY_ARRIVED: "DELIVERY_ARRIVED",
    DELIVERY_DELIVERED: "DELIVERY_DELIVERED",
    DELIVERY_COMPLETED: "DELIVERY_COMPLETED",
    CUSTOMER_CANCELED: "CUSTOMER_CANCELED",
    MERCHANT_ACCEPTED: "MERCHANT_ACCEPTED",
    MERCHANT_REJECTED: "MERCHANT_REJECTED",
    MERCHANT_CANCELED: "MERCHANT_CANCELED",
    MERCHANT_PREPARING: "MERCHANT_PREPARING",
    MERCHANT_DELAYED: "MERCHANT_DELAYED",
    MERCHANT_READY_FOR_PICKUP: "MERCHANT_READY_FOR_PICKUP",
    MERCHANT_REFUNDED: "MERCHANT_REFUNDED",
    MERCHANT_HIGH_DEMAND: "MERCHANT_HIGH_DEMAND",
    CUSTOMER_PAYMENT_FAILED: "CUSTOMER_PAYMENT_FAILED",
    CUSTOMER_PAYMENT_SUCCESSFUL: "CUSTOMER_PAYMENT_SUCCESSFUL",
    CUSTOMER_PAYMENT_PENDING: "CUSTOMER_PAYMENT_PENDING"
};

const VEHICLE_CATEGORY = {
    STANDARD: "STANDARD",
    PREMIUM: "PREMIUM"
};

const VEHICLE_CLASS = {
    SEDAN: "SEDAN",
    CARAVAN: "CARAVAN",
    SUV: "SUV",
    MINIVAN: "MINIVAN",
    VAN: "VAN",
    MINIBUS: "MINIBUS",
    BUS: "BUS",
    CARGO_VAN: 'CARGO_VAN',
    PRIVATE_DRIVER: 'PRIVATE_DRIVER',
    ANY: 'ANY'
};
const VEHICLE_CAPACITY = {
    [VEHICLE_CLASS.SEDAN]: 3,
    [VEHICLE_CLASS.CARAVAN]: 3,
    [VEHICLE_CLASS.SUV]: 4,
    [VEHICLE_CLASS.MINIVAN]: 6,
    [VEHICLE_CLASS.VAN]: 6,
    [VEHICLE_CLASS.CARGO_VAN]: 2,
    [VEHICLE_CLASS.MINIBUS]: 18,
    [VEHICLE_CLASS.BUS]: 30,
    [VEHICLE_CLASS.PRIVATE_DRIVER]: 3
};
const GENDER = {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER"
};

const COMPANY_ROLE = {
    DIRECTOR: "DIRECTOR",
    MANAGER: "MANAGER",
    REPRESENTATIVE_OF_SALES: "REPRESENTATIVE_OF_SALES",
    HEAD_OF_PROCUREMENT: "HEAD_OF_PROCUREMENT"
}

const ORDER_TYPE = {
    TAXI: 'TAXI',
    TRANSFER_PRIVATE: 'TRANSFER_PRIVATE',
    TRANSFER_SHUTTLE: 'TRANSFER_SHUTTLE',
    VEHICLE_TRANSFER: 'VEHICLE_TRANSFER',
    VEHICLE_TRANSFER_COMBO: 'VEHICLE_TRANSFER_COMBO',
    DELIVERY: 'DELIVERY',
}

const RESTAURANT_FEE = 0.25;
const DRIVE_FEE = 0.1;

const PARENT_USER_TYPE = {
    PERSONAL: 'PERSONAL',
    BUSINESS: 'BUSINESS'
}

const CARGO_TRANSFER_FEE = {
    CARGO_FEE: 20,
    ADDITIONAL_WORKER_FEE: 20
}

module.exports = {
    TokenType,
    USER_ROLE,
    BUSINESS_TYPE,
    MERCHANT_TYPE,
    BUSINESS_CATEGORY,
    FILE_TYPE,
    DOCUMENT_TYPE,
    TAXI_ORDER_STATUS,
    DELIVERY_ORDER_STATUS,
    VEHICLE_CATEGORY,
    VEHICLE_CLASS,
    GENDER,
    COMPANY_ROLE,
    VEHICLE_CAPACITY,
    TRANSFER_ORDER_STATUS,
    ORDER_TYPE,
    RESTAURANT_FEE,
    CARGO_TRANSFER_FEE,
    DRIVE_FEE
};