const USER_ROLES = {
    ADMIN: "ADMIN",
    BUSINESS_OWNER: "BUSINESS_OWNER",
    BUSINESS_CARETAKER: "BUSINESS_CARETAKER",
    PERSONAL: "PERSONAL",
    DRIVER: "DRIVER",
    DELIVERY_DRIVER: "DELIVERY_DRIVER"
};

const TokenType = {
    EMAIL: "EMAIL",
    PHONE_VERIFICATION: "PHONE_VERIFICATION",
    API: "API",
    PASSWORD_RESET: "PASSWORD_RESET"
};

const BUSINESS_TYPE = {
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT"
};

const MERCHANT_TYPE = {
    RESTAURANT: "RESTAURANT",
    BAR: "BAR",
    MARKET: "MARKET",
    STORE: "STORE"
};

const BUSINESS_CATEGORY = {
    TAXI: "TAXI",
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT"
};

const FILE_TYPE = {
    IMAGE: "IMAGE",
    DOCUMENT: "DOCUMENT"
};

const DOCUMENT_TYPE = {
    NATIONAL_ID: "NATIONAL_ID",
    PASSPORT: "PASSPORT",
    PROFILE_PICTURE: "PROFILE_PICTURE",
    LOGO: "LOGO",
    BANNER: "BANNER",
    DRIVING_LICENSE: "DRIVING_LICENSE",
    TAXI_LICENCE: "TAXI_LICENCE",
    PASSENGER_TRANSFER_LICENSE: "PASSENGER_TRANSFER_LICENSE",
    BACKGROUND_CHECK_REPORT: "BACKGROUND_CHECK_REPORT",
    VEHICLE_REGISTRATION: "VEHICLE_REGISTRATION",
    VEHICLE_INSURANCE: "VEHICLE_INSURANCE",
    VEHICLE_TECHNICAL_INSPECTION: "VEHICLE_TECHNICAL_INSPECTION",
    OPERATING_PERMIT: "OPERATING_PERMIT",
    HACCP_CERTIFICATION: "HACCP_CERTIFICATION",
    BUSINESS_LICENSE: "BUSINESS_LICENSE"
};

const TAXI_ORDER_STATUS = {
    PENDING: "PENDING",
    TAXI_ACCEPTED: "TAXI_ACCEPTED",
    TAXI_REJECTED: "TAXI_REJECTED",
    TAXI_CANCELED: "TAXI_CANCELED",
    TAXI_WAITING: "TAXI_WAITING",
    TAXI_DRIVING: "TAXI_DRIVING",
    TAXI_ARRIVED: "TAXI_ARRIVED",
    TAXI_COMPLETED: "TAXI_COMPLETED",
    CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED"
};

const DELIVERY_ORDER_STATUS = {
    PENDING: "PENDING",
    DELIVERY_ACCEPTED: "DELIVERY_ACCEPTED",
    DELIVERY_REJECTED: "DELIVERY_REJECTED",
    DELIVERY_CANCELED: "DELIVERY_CANCELED",
    DELIVERY_PICKED_UP: "DELIVERY_PICKED_UP",
    DELIVERY_IN_DELIVERY: "DELIVERY_IN_DELIVERY",
    DELIVERY_DELAYED: "DELIVERY_DELAYED",
    DELIVERY_ARRIVED: "DELIVERY_ARRIVED",
    DELIVERY_DELIVERED: "DELIVERY_DELIVERED",
    DELIVERY_COMPLETED: "DELIVERY_COMPLETED",
    CUSTOMER_CANCELLED: "CUSTOMER_CANCELLED",
    MERCHANT_ACCEPTED: "MERCHANT_ACCEPTED",
    MERCHANT_REJECTED: "MERCHANT_REJECTED",
    MERCHANT_CANCELED: "MERCHANT_CANCELED",
    MERCHANT_PREPARING: "MERCHANT_PREPARING",
    MERCHANT_DELAYED: "MERCHANT_DELAYED",
    MERCHANT_READY_FOR_PICKUP: "MERCHANT_READY_FOR_PICKUP",
    MERCHANT_REFUNDED: "MERCHANT_REFUNDED",
    MERCHANT_HIGH_DEMAND: "MERCHANT_HIGH_DEMAND"
};

const VEHICLE_CATEGORY = {
    STANDARD: "STANDARD",
    PREMIUM: "PREMIUM"
};

const VEHICLE_CLASS = {
    SEDAN: "SEDAN",
    CARAVAN: "CARAVAN",
    SUV: "SUV",
    MINIVAN: "MINIVAN",
    VAN: "VAN",
    MINIBUS: "MINIBUS",
    BUS: "BUS"
};

const GENDER = {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER"
};

const COMPANY_ROLE = {
    DIRECTOR: "DIRECTOR",
    MANAGER: "MANAGER",
    REPRESENTATIVE_OF_SALES: "REPRESENTATIVE_OF_SALES",
    HEAD_OF_PROCUREMENT: "HEAD_OF_PROCUREMENT"
}


module.exports = {
    TokenType,
    USER_ROLES,
    BUSINESS_TYPE,
    MERCHANT_TYPE,
    BUSINESS_CATEGORY,
    FILE_TYPE,
    DOCUMENT_TYPE,
    TAXI_ORDER_STATUS,
    DELIVERY_ORDER_STATUS,
    VEHICLE_CATEGORY,
    VEHICLE_CLASS,
    GENDER,
    COMPANY_ROLE
};