const USER_ROLE = {
    ADMIN: 'ADMIN',
    BUSINESS_OWNER: 'BUSINESS_OWNER',
    BUSINESS_MANAGER: 'BUSINESS_MANAGER',
    BUSINESS_CARETAKER: 'BUSINESS_CARETAKER',
    BUSINESS_USER: 'BUSINESS_USER',
    PERSONAL: 'PERSONAL',
    DRIVER: 'DRIVER',
    DELIVERY_DRIVER: 'DELIVERY_DRIVER'
}

const TokenType = {
    EMAIL: "EMAIL",
    PHONE_VERIFICATION: "PHONE_VERIFICATION",
    API: "API",
    PASSWORD_RESET: "PASSWORD_RESET"
};

const BUSINESS_TYPE = {
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT",
    BUSINESS: "BUSINESS",
    DISPATCHER: "DISPATCHER",
};

const MERCHANT_TYPE = {
    RESTAURANT: "RESTAURANT",
    BAR: "BAR",
    MARKET: "MARKET",
    STORE: "STORE"
};

const BUSINESS_CATEGORY = {
    TAXI: "TAXI",
    TRANSFER: "TRANSFER",
    MERCHANT: "MERCHANT"
};

const SERVICE_TYPE = {
    TAXI: 'TAXI',
    DELIVERY: 'DELIVERY',
    TRANSFER: 'TRANSFER',
    ANY:'ANY',
    OTHER: 'OTHER'
}

const FILE_TYPE = {
    IMAGE: "IMAGE",
    DOCUMENT: "DOCUMENT"
};

const DOCUMENT_TYPE = {
    // USER
    NATIONAL_ID: 'NATIONAL_ID',
    PASSPORT: 'PASSPORT',
    PROFILE_PICTURE: 'PROFILE_PICTURE',

    // PARTNER / DRIVER
    LOGO: 'LOGO',
    BANNER: 'BANNER',
    DRIVING_LICENSE: 'DRIVING_LICENSE',
    TAXI_LICENCE: 'TAXI_LICENCE',
    PASSENGER_TRANSFER_LICENSE: 'PASSENGER_TRANSFER_LICENSE',
    BACKGROUND_CHECK_REPORT: 'BACKGROUND_CHECK_REPORT',
    HEALTH_DECLARATION: 'HEALTH_DECLARATION',

    // VEHICLE
    VEHICLE_REGISTRATION: 'VEHICLE_REGISTRATION',
    VEHICLE_INSURANCE: 'VEHICLE_INSURANCE',
    VEHICLE_TECHNICAL_INSPECTION: 'VEHICLE_TECHNICAL_INSPECTION',

    // MERCHANT
    OPERATING_PERMIT: 'OPERATING_PERMIT',
    HACCP_CERTIFICATION: 'HACCP_CERTIFICATION',
    BUSINESS_LICENSE: 'BUSINESS_LICENSE',

    // MENU_ITEM
    MENU_ITEM_IMAGE: 'MENU_ITEM_IMAGE',

    WALLET_TOPUP: 'WALLET_TOPUP',
};

const TAXI_ORDER_STATUS = {
    PENDING: "PENDING",
    TAXI_ACCEPTED: "TAXI_ACCEPTED",
    TAXI_REJECTED: "TAXI_REJECTED",
    TAXI_CANCELED: "TAXI_CANCELED",
    CUSTOMER_CANCELED: "CUSTOMER_CANCELED",
    TAXI_WAITING: "TAXI_WAITING",
    TAXI_DRIVING: "TAXI_DRIVING",
    TAXI_ARRIVED: "TAXI_ARRIVED",
    TAXI_COMPLETED: "TAXI_COMPLETED",
};

const TRANSFER_ORDER_STATUS = {
    PENDING: 'PENDING',
    ACCEPTED: 'TRANSFER_ACCEPTED',
    COMPLETED: 'TRANSFER_COMPLETED',
}

const DELIVERY_ORDER_STATUS = {
    DELIVERY_ACCEPTED: "DELIVERY_ACCEPTED",
    DELIVERY_REJECTED: "DELIVERY_REJECTED",
    DELIVERY_CANCELED: "DELIVERY_CANCELED",
    DELIVERY_PICKED_UP: "DELIVERY_PICKED_UP",
    DELIVERY_IN_DELIVERY: "DELIVERY_IN_DELIVERY",
    DELIVERY_DELAYED: "DELIVERY_DELAYED",
    DELIVERY_ARRIVED: "DELIVERY_ARRIVED",
    DELIVERY_DELIVERED: "DELIVERY_DELIVERED",
    DELIVERY_COMPLETED: "DELIVERY_COMPLETED",

    MERCHANT_ACCEPTED: "MERCHANT_ACCEPTED",
    MERCHANT_REJECTED: "MERCHANT_REJECTED",
    // MERCHANT_CANCELED: "MERCHANT_CANCELED",
    MERCHANT_PREPARING: "MERCHANT_PREPARING",
    MERCHANT_DELAYED: "MERCHANT_DELAYED",
    MERCHANT_READY_FOR_PICKUP: "MERCHANT_READY_FOR_PICKUP",
    // MERCHANT_REFUNDED: "MERCHANT_REFUNDED",
    // MERCHANT_HIGH_DEMAND: "MERCHANT_HIGH_DEMAND",

    CUSTOMER_PAYMENT_FAILED: "CUSTOMER_PAYMENT_FAILED",
    CUSTOMER_PAYMENT_SUCCESSFUL: "CUSTOMER_PAYMENT_SUCCESSFUL",
    // CUSTOMER_PAYMENT_PENDING: "CUSTOMER_PAYMENT_PENDING",
    // CUSTOMER_CANCELED: "CUSTOMER_CANCELED",
    CUSTOMER_PICKED_UP: "CUSTOMER_PICKED_UP",

    PENDING: "PENDING",
    DISPATCHER_CANCELED: "DISPATCHER_CANCELED",
    DISPATCHER_REVOKED: "DISPATCHER_REVOKED",
    AUTO_REJECTED: "AUTO_REJECTED",
    FAIL: "ORDER_FINISHED_FAIL",
    SUCCESS: "ORDER_FINISHED_SUCCESS",
};

const DELIVERY_ORDER_END_STATES = [
    DELIVERY_ORDER_STATUS.FAIL,
    DELIVERY_ORDER_STATUS.SUCCESS,
]

const DELIVERY_COST_CALCULATION = {
    MINIMUM_COST: 3.5,
    COST_PER_500: 0.5
}

const VEHICLE_CATEGORY = {
    STANDARD: "STANDARD",
    PREMIUM: "PREMIUM"
};

const VEHICLE_CLASS = {
    SEDAN: "SEDAN",
    CARAVAN: "CARAVAN",
    SUV: "SUV",
    MINIVAN: "MINIVAN",
    VAN: "VAN",
    MINIBUS: "MINIBUS",
    BUS: "BUS",
    CARGO_VAN: 'CARGO_VAN',
    PRIVATE_DRIVER: 'PRIVATE_DRIVER',
    ANY: 'ANY'
};
const VEHICLE_CAPACITY = {
    [VEHICLE_CLASS.ANY]: 4,
    [VEHICLE_CLASS.SEDAN]: 3,
    [VEHICLE_CLASS.CARAVAN]: 3,
    [VEHICLE_CLASS.SUV]: 4,
    [VEHICLE_CLASS.MINIVAN]: 6,
    [VEHICLE_CLASS.VAN]: 6,
    [VEHICLE_CLASS.CARGO_VAN]: 2,
    [VEHICLE_CLASS.MINIBUS]: 18,
    [VEHICLE_CLASS.BUS]: 30,
    [VEHICLE_CLASS.PRIVATE_DRIVER]: 3
};
const GENDER = {
    MALE: "MALE",
    FEMALE: "FEMALE",
    OTHER: "OTHER"
};

const COMPANY_ROLE = {
    DIRECTOR: "DIRECTOR",
    MANAGER: "MANAGER",
    REPRESENTATIVE_OF_SALES: "REPRESENTATIVE_OF_SALES",
    HEAD_OF_PROCUREMENT: "HEAD_OF_PROCUREMENT"
}

const ORDER_TYPE = {
    TAXI: 'TAXI',
    TRANSFER_PRIVATE: 'TRANSFER_PRIVATE',
    TRANSFER_SHUTTLE: 'TRANSFER_SHUTTLE',
    VEHICLE_TRANSFER: 'VEHICLE_TRANSFER',
    VEHICLE_TRANSFER_COMBO: 'VEHICLE_TRANSFER_COMBO',
    DELIVERY: 'DELIVERY',
}

const ORDER_SUBTYPE = {
    CREATED_BY_USER: 'CREATED_BY_USER',
    CREATED_BY_DISPATCHER: 'CREATED_BY_DISPATCHER',
    CREATED_BY_BUSINESS: 'CREATED_BY_BUSINESS',
}

const CREDITS = {
    REFERRAL: 500, //in cents
    CASHBACK_CONVERSION_TAXI: 200, //wheels
    CASHBACK_CONVERSION_DELIVERY: 200, //baskets
    CASHBACK_THRESHOLD_TAXI: 10, //€
    CASHBACK_THRESHOLD_DELIVERY: 10, //€
    REFERRAL_THRESHOLD: 10, //amount of orders before reward
    MINIMUM_ORDER_AMOUNT: 5,
}

const FUNDS_TYPE = {
    FUNDS: "FUNDS",
    CREDITS_ANY: "CREDITS_ANY",
    CREDITS_TAXI: "CREDITS_TAXI",
    CREDITS_TRANSFER: "CREDITS_TRANSFER",
    CREDITS_DELIVERY: "CREDITS_DELIVERY",
}

const SERVICE_TYPE_TO_FUNDS_TYPE = {
    TAXI: FUNDS_TYPE.CREDITS_TAXI,
    DELIVERY: FUNDS_TYPE.CREDITS_DELIVERY,
    TRANSFER: FUNDS_TYPE.CREDITS_TRANSFER,
    ANY: FUNDS_TYPE.CREDITS_ANY,
}

const CASHBACK_SOURCE = {
    REFERRAL: 'REFERRAL',
    ORDER: 'ORDER',
    CONVERSION: 'CONVERSION',
    PROMOTIONAL: 'PROMOTIONAL',
    SYSTEM_GRANT: 'SYSTEM_GRANT',
}

const CASHBACK_STATUS = {
    PENDING: 'PENDING',
    EXPIRED: 'EXPIRED',
    CONVERTED: 'CONVERTED'
}

const CREDIT_STATUS =  {
    ACTIVE: 'ACTIVE',
    USED: 'USED',
    EXPIRED: 'EXPIRED',
}

const CASHBACK_TYPE = {
    TAXI: 'TAXI',
    DELIVERY: 'DELIVERY',
    TRANSFER: 'TRANSFER',
}

const SCORING_POINTS_REASON = {
    REJECTED: "REJECTED",
    CANCELED: "CANCELED",
    AUTO_REJECTED: "AUTO_REJECTED",
    LARGE_DELAY: "LARGE_DELAY",
    LATE: "LATE",
    INSUFFICIENT_DATA: "INSUFFICIENT_DATA"
};

const AUTOREJECT_THRESHOLD_MINUTES = 8

const RESTAURANT_FEE = 0.25;
const DRIVE_FEE = 0.1;

const PARENT_USER_TYPE = {
    PERSONAL: 'PERSONAL',
    BUSINESS: 'BUSINESS'
}

const CARGO_TRANSFER_FEE = {
    CARGO_FEE: 20,
    ADDITIONAL_WORKER_FEE: 20
}
const PRICE_SURGE_MULTIPLIERS = {
    MAX: 1.7,
    WEATHER: {
        LIGHT: 1.1,
        MODERATE: 1.2,
        HEAVY: 1.3,
    }
}

export const TAX = {
    SLO: 0.22
};

export const COST_PER_KM = {
    STANDARD: 1.09,
    PREMIUM: 1.5,
    TRANSFER_BONUS: 1.3,
}

export const COST_PER_MIN = {
    STANDARD: 0.2,
    PREMIUM: 0.2,
}

export const TAXI_STARTING_FEE = {
    STANDARD: 1.95,
    PREMIUM: 2.00,
}

module.exports = {
    TokenType,
    USER_ROLE,
    SERVICE_TYPE,
    BUSINESS_TYPE,
    MERCHANT_TYPE,
    BUSINESS_CATEGORY,
    FILE_TYPE,
    DOCUMENT_TYPE,
    TAXI_ORDER_STATUS,
    DELIVERY_ORDER_STATUS,
    DELIVERY_ORDER_END_STATES,
    VEHICLE_CATEGORY,
    VEHICLE_CLASS,
    GENDER,
    COMPANY_ROLE,
    VEHICLE_CAPACITY,
    TRANSFER_ORDER_STATUS,
    ORDER_TYPE,
    ORDER_SUBTYPE,
    RESTAURANT_FEE,
    CARGO_TRANSFER_FEE,
    DRIVE_FEE,
    CREDITS,
    FUNDS_TYPE,
    SERVICE_TYPE_TO_FUNDS_TYPE,
    CASHBACK_SOURCE,
    CASHBACK_STATUS,
    CREDIT_STATUS,
    CASHBACK_TYPE,
    PARENT_USER_TYPE,
    AUTOREJECT_THRESHOLD_MINUTES,
    SCORING_POINTS_REASON,
    DELIVERY_COST_CALCULATION,
    PRICE_SURGE_MULTIPLIERS
};