openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/finances/:finance_id:
    delete:
      tags:
        - Finance
      summary: Delete finance record
      description: Deletes a finance record by its ID.
      operationId: deleteFinances
      parameters:
        - name: finance_id
          in: path
          description: The ID of the finance record to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Finance record deleted successfully
        '400':
          description: Error deleting finance record
components: {}
