openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/drivers/earnings/all:
    get:
      tags:
        - Drivers
      summary: Get earnings for all drivers
      description: Retrieves the earnings of all drivers within a specified date range.
      operationId: getAllDriversEarnings
      parameters:
        - name: start_date
          in: path
          description: 'The start date for the earnings period (format: YYYY-MM-DD)'
          required: true
          schema:
            type: string
        - name: end_date
          in: path
          description: 'The end date for the earnings period (format: YYYY-MM-DD)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation, returns all drivers' earnings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Earnings'
        '400':
          description: Error retrieving all drivers' earnings
components: {}
