openapi: 3.0.3
info:
  title: get /api/users/:user_id/wallet
  version: 1.0.0
paths:
  /api/users/:user_id/wallet:
    get:
      tags:
        - Users
      summary: Get wallet balance from wallet_funds.
      description: >-
        This endpoint is used to check available wallet balance for a particular
        user.
      operationId: getPaymentSheetCredentials
      responses:
        '200':
          description: '{wallet_balance:float}'
        '400':
          description: Error checking wallet balances
