openapi: 3.0.3
info:
  title: get /api/vehicles/driver/:driver_id/class/:vehicleClass
  version: 1.0.0
paths:
  /api/vehicles/driver/:driver_id/class/:vehicleClass:
    get:
      tags:
        - Vehicles
      summary: Get vehicles of a certain driver by class
      description: >-
        Retrieves a list of vehicles of a specific class assigned to a specific
        driver.
      parameters:
        - name: driverId
          in: path
          description: The ID of the driver
          required: true
          schema:
            type: string
        - name: vehicleClass
          in: path
          description: The class of the vehicles to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '500':
          description: Error fetching vehicles
