openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/users/:user_id:
    get:
      tags:
        - Users
      summary: Get a user by ID
      description: Retrieves detailed information about a specific user by their ID.
      operationId: getUserById
      parameters:
        - name: user_id
          in: path
          description: The ID of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation, returns detailed user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error retrieving user information
        '404':
          description: User not found
components: {}
