openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/users/me/payment-sheet:
    get:
      tags:
        - Users
      summary: Get payment sheet credentials for a user
      description: >-
        This endpoint is used to get Stripe payment sheet credentials for a
        particular user.
      operationId: getPaymentSheetCredentials
      responses:
        '200':
          description: '{StripePaymentSheetCredentials}'
        '400':
          description: Error obtaining payment sheet credentials
components: {}
