openapi: 3.0.3
info:
  title: get /api/users/me
  version: 1.0.0
paths:
  /api/users/me:
    get:
      tags:
        - Users
      summary: Retrieve authenticated user's information
      description: Retrieve the details of the authenticated user by their ID.
      security:
        - 'bearerAuth:': []
      operationId: retrieveUserInformation
      responses:
        '200':
          description: Successful operation, returns user info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error obtaining user information.
          content:
            application/json:
              schema:
                type: object
