openapi: 3.0.3
info:
  title: get /api/users/:user_id/family_wallet
  version: 1.0.0
paths:
  /api/users/:user_id/family_wallet:
    get:
      tags:
        - Users
      summary: >-
        Get family wallet type and minimum between allowance and actual family
        wallet balance.
      description: >-
        This endpoint is used to check wallet balance and type for a particular
        user.
      operationId: getPaymentSheetCredentials
      responses:
        '200':
          description: '{family_wallet_balance:float,family_wallet_type:string}'
        '400':
          description: Error checking wallet balances
