openapi: 3.0.3
info:
  title: get /api/drivers/orders
  version: 1.0.0
paths:
  /api/drivers/orders:
    get:
      tags:
        - Drivers
      summary: Send already sent pending or accepted orders to a driver
      description: >-
        Retrieves a list of orders for a specific driver by their user ID and
        sends them to the driver via socket emission.
      operationId: sendAcceptedOrdersToDriver
      responses:
        '200':
          description: Successful operation, orders sent to the driver
        '400':
          description: Error retrieving orders
        '404':
          description: Driver not found
