openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/drivers/ride_requirements:
    patch:
      tags:
        - Drivers
      summary: Updates the driver's ride requirements
      description: This endpoint is used to update the current user's ride requirements.
      operationId: updateDriverRideRequirements
      requestBody:
        description: The new ride requirements of the driver.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDriverRideRequirementsRequest'
        required: true
      responses:
        '200':
          description: >-
            Ride requirements updated successfully. Returns the updated driver's
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error updating user information.
components: {}
