openapi: 3.0.3
info:
  title: patch /api/drivers/edit
  version: 1.0.0
paths:
  /api/drivers/edit:
    patch:
      tags:
        - Drivers
      summary: Edit a driver
      description: Edits the data of specific driver.
      operationId: editDriver
      parameters:
        - name: driver_id
          in: path
          description: The ID of the driver to edit
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DriverEdit'
        required: true
      responses:
        '200':
          description: Driver edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        '400':
          description: Error updating driver
