openapi: 3.0.3
info:
  title: patch /api/users/:user_id/wallet
  version: 1.0.0
paths:
  /api/users/:user_id/wallet:
    patch:
      tags:
        - Users
      summary: Update wallet balance for a user.
      description: >-
        This endpoint is used to update the wallet balance for a particular
        user.
      operationId: updateWalletBalance
      parameters:
        - name: user_id
          in: path
          description: The ID of the user whose wallet balance is to be updated.
          required: true
          schema:
            type: string
      requestBody:
        description: The new wallet balance
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: Wallet balance updated successfully.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Error updating wallet balance.
