openapi: 3.0.3
info:
  title: patch /api/business/business-unit
  version: 1.0.0
paths:
  /api/business/business-unit:
    patch:
      tags:
        - Businesses
      summary: Updates the business unit status
      description: >-
        This endpoint is used to update whether a business is considered a
        business unit.
      operationId: updateIsBusinessUnit
      requestBody:
        description: The new business unit status
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIsBusinessUnitRequest'
        required: true
      responses:
        '200':
          description: >-
            Business unit status updated successfully. Returns the updated
            business details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        '400':
          description: Error updating business information.
