openapi: 3.0.3
info:
  title: patch /api/business/edit
  version: 1.0.0
paths:
  /api/business/edit:
    patch:
      tags:
        - Business
      summary: Edit business details
      description: >-
        This endpoint is used to update multiple details of a business,
        including address, delivery address, finances, and other specific data.
      operationId: editBusiness
      requestBody:
        description: The data to update for the business.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditBusinessRequest'
        required: true
      responses:
        '200':
          description: Business updated successfully. Returns the updated business details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        '400':
          description: Error updating business information.
