openapi: 3.0.3
info:
  title: patch /api/business/workingHours
  version: 1.0.0
paths:
  /api/business/workingHours:
    patch:
      tags:
        - Business
      summary: Updates a business's working hours
      description: This endpoint is used to update a business's working hours.
      operationId: updateBusinessWorkingHours
      parameters:
        - name: business_id
          in: path
          description: The ID of the business to update
          required: true
          schema:
            type: string
      requestBody:
        description: The new working hours for the business
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBusinessWorkingHoursRequest'
        required: true
      responses:
        '200':
          description: >-
            Working hours updated successfully. Returns the updated business
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        '400':
          description: Error updating business information.
