openapi: 3.0.3
info:
  title: patch /api/drivers/ride_requirements
  version: 1.0.0
paths:
  /api/drivers/ride_requirements:
    patch:
      tags:
        - Drivers
      summary: Updates the driver's ride requirements
      description: This endpoint is used to update the current user's ride requirements.
      operationId: updateDriverRideRequirements
      requestBody:
        description: The new ride requirements of the driver.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDriverRideRequirementsRequest'
        required: true
      responses:
        '200':
          description: >-
            Ride requirements updated successfully. Returns the updated driver's
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error updating user information.
