openapi: 3.0.3
info:
  title: patch /api/business/type
  version: 1.0.0
paths:
  /api/business/type:
    patch:
      tags:
        - Business
      summary: Updates a business's type
      description: This endpoint is used to update a business's type.
      operationId: updateBusinessType
      requestBody:
        description: The new type for the business
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBusinessTypeRequest'
        required: true
      responses:
        '200':
          description: Type updated successfully. Returns the updated business details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        '400':
          description: Error updating business information.
