openapi: 3.0.3
info:
  title: post /api/delivery/orders/order/pickup_time
  version: 1.0.0
paths:
  /api/delivery/orders/order/pickup_time:
    post:
      tags:
        - Delivery
      summary: Update a delivery order's pickup time.
      description: Updates pickup time of the delivery order
      operationId: updateOrderPickupTime
      requestBody:
        description: >-
          Request body must include 'order_id' to identify the order and
          'status' to specify the new status.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOrderPickupTimeRequest'
        required: true
      responses:
        '200':
          description: >-
            Successful operation. Returns the updated order in the response
            body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryOrder'
        '500':
          description: >-
            Server error. Returns error message if any exception is encountered
            during execution.
