openapi: 3.0.3
info:
  title: post /api/delivery/orders/daily_meals
  version: 1.0.0
paths:
  /api/delivery/orders/daily_meals:
    post:
      tags:
        - Delivery
      summary: Create daily meals.
      description: >-
        This creates the daily meals for the subscribed users. Returns list of
        orders if successful.
      operationId: createDailyMeals
      responses:
        '200':
          description: >-
            Successful operation. Returns the newly created daily meals in the
            response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryOrder'
        '500':
          description: >-
            Server error. Returns error message "Something went wrong..." if any
            exception is encountered during execution.
