openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/business/scheduled_users/sorting/type:
    post:
      tags:
        - Business
      summary: Add sorting type for scheduled users
      description: This endpoint is used to add the sorting type for scheduled users.
      operationId: addScheduledUserSortingType
      requestBody:
        description: The sorting type (manual or automatic).
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddScheduledUserSortingTypeRequest'
        required: true
      responses:
        '200':
          description: Sorting type added successfully.
        '400':
          description: Error adding sorting type.
components: {}
