openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/documents/create/user/:user_id:
    post:
      tags:
        - Documents
      summary: Create a document for a user
      description: Creates a new document and links it to a specific user.
      operationId: createUserDocument
      parameters:
        - name: user_id
          in: path
          description: The ID of the user
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentCreationRequest'
        required: true
      responses:
        '201':
          description: Document created and linked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Error creating or linking the document
components: {}
