openapi: 3.0.3
info:
  title: post /api/finances/create
  version: 1.0.0
paths:
  /api/finances/create:
    post:
      tags:
        - Finance
      summary: Add new finance record
      description: Adds a new finance record to the database.
      operationId: addFinances
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Finance'
        required: true
      responses:
        '201':
          description: Finance record added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Finance'
        '400':
          description: Error adding finance record
