openapi: 3.0.3
info:
  title: post /api/taxi/order/accept
  version: 1.0.0
paths:
  /api/taxi/order/accept:
    post:
      tags:
        - Taxi
      summary: Accept a taxi order.
      description: >-
        Accepts taxi order with the provided details from the request body.
        Returns the accepted order if successful.
      operationId: acceptOrder
      requestBody:
        description: Request body must include necessary order details.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxiOrderRequest'
        required: true
      responses:
        '200':
          description: >-
            Successful operation. Returns the accepted order in the response
            body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxiOrder'
        '500':
          description: >-
            Server error. Returns error message "Something went wrong..." if any
            exception is encountered during execution.
