openapi: 3.0.3
info:
  title: post /api/drivers/create
  version: 1.0.0
paths:
  /api/drivers/create:
    post:
      tags:
        - Drivers
      summary: Create a new driver
      description: Adds a new driver to the database.
      operationId: createNewDriver
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Driver'
        required: true
      responses:
        '201':
          description: Driver created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        '400':
          description: Error creating driver
