openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/business/delivery-address/add:
    post:
      tags:
        - Business
      summary: Add a delivery address to a business
      description: Adds a delivery address to a specific business.
      operationId: addDeliveryAddress
      parameters:
        - name: business_id
          in: path
          description: The ID of the business
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
        required: true
      responses:
        '200':
          description: Delivery address added successfully
        '400':
          description: Error adding delivery address
components: {}
