openapi: 3.0.3
info:
  title: post /api/business/scheduled_users/sorting
  version: 1.0.0
paths:
  /api/business/scheduled_users/sorting:
    post:
      tags:
        - Business
      summary: Manually sort scheduled users
      description: This endpoint is used to manually sort scheduled users.
      operationId: manualSortScheduledUsers
      requestBody:
        description: The list of sorted user IDs.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualSortScheduledUsersRequest'
        required: true
      responses:
        '200':
          description: Users sorted successfully.
        '400':
          description: Error sorting users.
