openapi: 3.0.3
info:
  title: post /api/drivers/come_to_work
  version: 1.0.0
paths:
  /api/drivers/come_to_work:
    post:
      tags:
        - Drivers
      summary: Send notifications for drivers to come to work
      description: >-
        This endpoint allows sending a "come to work" notifications to all
        drivers who are currently offline.
      operationId: comeToWorkDrivers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Object'
        required: true
      responses:
        '200':
          description: Notification sent out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        '400':
          description: Problem sending notification
        '404':
          description: Problem sending notification
