openapi: 3.0.3
info:
  title: ''
  version: ''
  description: >
    This is a simple CRUD API application made with Express and documented with
    Swagger
  termsOfService: http://swagger.io/terms/
  contact:
    email: bourdakos1@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-github: https://github.com/bee-travels
paths:
  /api/business/scheduled_users/sorting:
    post:
      tags:
        - Business
      summary: Manually sort scheduled users
      description: This endpoint is used to manually sort scheduled users.
      operationId: manualSortScheduledUsers
      requestBody:
        description: The list of sorted user IDs.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualSortScheduledUsersRequest'
        required: true
      responses:
        '200':
          description: Users sorted successfully.
        '400':
          description: Error sorting users.
components: {}
