openapi: 3.0.3
info:
  title: post /api/delivery/orders/order/delivery_time
  version: 1.0.0
paths:
  /api/delivery/orders/order/delivery_time:
    post:
      tags:
        - Delivery
      summary: Update a delivery order's delivery time.
      description: Updates delivery time of the delivery order
      operationId: updateOrderDeliveryTime
      requestBody:
        description: >-
          Request body must include 'order_id' and 'delivery_time' to set the
          delivery time.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOrderDeliveryTimeRequest'
        required: true
      responses:
        '200':
          description: >-
            Successful operation. Returns the updated order in the response
            body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryOrder'
        '500':
          description: >-
            Server error. Returns error message if any exception is encountered
            during execution.
