openapi: 3.0.3
info:
  title: post /api/taxi/order/payment
  version: 1.0.0
paths:
  /api/taxi/order/payment:
    post:
      tags:
        - Taxi
      summary: Update a taxi order's payment details.
      description: Updates the payment details of the order.
      operationId: updateTaxiOrderPayment
      requestBody:
        description: Request body must include 'order_id', and the new 'route' details.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaxiOrderPaymentRequest'
        required: true
      responses:
        '200':
          description: >-
            Successful operation. Returns the updated order with the new payment
            details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxiOrder'
        '500':
          description: >-
            Server error. Returns error message if any exception is encountered
            during execution.
