FROM node:20-bullseye

# Install system dependencies for Prisma, canvas, and wkhtmltopdf
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    make \
    g++ \
    libcairo2-dev \
    libjpeg-dev \
    libpango1.0-dev \
    libgif-dev \
    librsvg2-dev \
    libssl-dev \
    openssl \
    fontconfig \
    libfreetype6 \
    libxrender1 \
    libxext6 \
    fonts-dejavu-core fonts-liberation \
    curl \
    ca-certificates \
    xz-utils \
 && rm -rf /var/lib/apt/lists/*

# Install wkhtmltopdf for Bullseye (0.12.6-1 is the latest stable for Bullseye)
RUN curl -fSL -o wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb && \
    apt-get update && apt-get install -y ./wkhtmltox.deb && \
    rm wkhtmltox.deb



# Set working directory
WORKDIR /app

# Copy package.json and lock file first for better cache
COPY package*.json ./
COPY setup-aliases.js install-wkhtmltopdf.js ./
# Install app dependencies
RUN npm ci

# (Optional) Install nodemon for development
# Comment this out if you're building a production image
RUN npm install --save-dev nodemon

# Copy rest of the app
COPY . .

# Prisma environment setup for code generation
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Run dev server
CMD ["npm", "run", "start"]
