// This file was auto-generated by prisma-generator-typescript-interfaces

export type TRANSACTION_TYPE = 'DEBIT' | 'CREDIT';

export type PAYMENT_METHOD = 'CARD' | 'CASH' | 'WALLET' | 'PLATFORM';

export type PAYMENT_STATUS = 'PENDING' | 'SUCCEEDED' | 'FAILED' | 'REFUNDED';

export type SPLIT_DESTINATION_TYPE = 'PLATFORM' | 'MERCHANT' | 'DRIVER';

export type SPLIT_STATUS = 'RESERVED' | 'TRANSFERED' | 'CANCELED' | 'REFUNDED';

export type SUBSCRIPTION_STATUS = 'AWAITING_PAYMENT' | 'ACTIVE' | 'CANCELED' | 'EXPIRED' | 'FAILED';

export type SUBSCRIPTION_TYPE = 'DATED' | 'RECURRING';

export type DAILY_MEAL_INSTANCE_STATUS = 'PLANNED' | 'CANCELED' | 'SKIPPED' | 'DELIVERED';

export type BLOG_POST_STATUS = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';

export type ACCOUNT_ACTIONS = 'SUSPEND' | 'UNSUSPEND' | 'BAN' | 'UNBAN' | 'DELETE' | 'CREATE';

export type ACCOUNT_ACTIONS_REASON =
	| 'SUSPICIOUS_BEHAVIOUR'
	| 'VIOLATION_OF_TERMS'
	| 'SPAMMING_OR_SCAMMING'
	| 'HATE_SPEECH_OR_ABUSE'
	| 'IMPERSONATION'
	| 'PAYMENT_FRAUD'
	| 'SELF_DISABLE'
	| 'APPEAL_APPROVED'
	| 'MANUAL_REVIEW_CLEAR'
	| 'SYSTEM_ERROR_CORRECTION'
	| 'USER_VERIFIED'
	| 'BUSINESS_VERIFIED'
	| 'TERMS_ACCEPTED'
	| 'TEMPORARY_BAN_EXPIRED';

export type CATEGORY_TYPE = 'MENU' | 'CUISINE';

export type PROMO_SERVICE_TYPES = 'TAXI' | 'DELIVERY';

export type USER_ROLES =
	| 'ADMIN'
	| 'BUSINESS_OWNER'
	| 'BUSINESS_MANAGER'
	| 'BUSINESS_CARETAKER'
	| 'BUSINESS_USER'
	| 'PERSONAL'
	| 'DRIVER'
	| 'DELIVERY_DRIVER'
	| 'DISPATCHER';

export type TokenType = 'EMAIL' | 'PHONE_VERIFICATION' | 'API' | 'PASSWORD_RESET';

export type BUSINESS_TYPE =
	| 'TRANSFER'
	| 'MERCHANT'
	| 'LOCAL'
	| 'RESTAURANT'
	| 'BUSINESS'
	| 'DISPATCHER'
	| 'RESERVATION';

export type MERCHANT_TYPE = 'RESTAURANT' | 'BAR' | 'MARKET' | 'STORE';

export type BUSINESS_CATEGORY = 'TAXI' | 'TRANSFER' | 'MERCHANT';

export type FILE_TYPE = 'IMAGE' | 'DOCUMENT';

export type DOCUMENT_TYPE =
	| 'NATIONAL_ID'
	| 'PASSPORT'
	| 'PROFILE_PICTURE'
	| 'LOGO'
	| 'BANNER'
	| 'DRIVING_LICENSE'
	| 'TAXI_LICENCE'
	| 'PASSENGER_TRANSFER_LICENSE'
	| 'BACKGROUND_CHECK_REPORT'
	| 'VEHICLE_REGISTRATION'
	| 'VEHICLE_INSURANCE'
	| 'VEHICLE_TECHNICAL_INSPECTION'
	| 'OPERATING_PERMIT'
	| 'HACCP_CERTIFICATION'
	| 'BUSINESS_LICENSE'
	| 'MENU_ITEM_IMAGE'
	| 'LOST_ITEM'
	| 'HEALTH_DECLARATION'
	| 'DAILY_MEALS_MENU'
	| 'WALLET_TOPUP';

export type TAXI_ORDER_STATUS =
	| 'PENDING'
	| 'TAXI_ACCEPTED'
	| 'TAXI_REJECTED'
	| 'TAXI_CANCELED'
	| 'TAXI_WAITING'
	| 'TAXI_DRIVING'
	| 'TAXI_ARRIVED'
	| 'TAXI_COMPLETED'
	| 'CUSTOMER_CANCELED'
	| 'TRANSFER_ACCEPTED'
	| 'TRANSFER_COMPLETED'
	| 'AWAITING_PAYMENT';

export type DELIVERY_ORDER_STATUS =
	| 'PENDING'
	| 'CUSTOMER_PAYMENT_FAILED'
	| 'CUSTOMER_PAYMENT_SUCCESSFUL'
	| 'CUSTOMER_PAYMENT_PENDING'
	| 'DISPATCHER_CANCELED'
	| 'ORDER_FINISHED_FAIL'
	| 'ORDER_FINISHED_SUCCESS'
	| 'AUTO_REJECTED'
	| 'DELIVERY_ACCEPTED'
	| 'DELIVERY_REJECTED'
	| 'DELIVERY_CANCELED'
	| 'DELIVERY_PICKED_UP'
	| 'DELIVERY_IN_DELIVERY'
	| 'DELIVERY_DELAYED'
	| 'DELIVERY_ARRIVED'
	| 'DELIVERY_DELIVERED'
	| 'DELIVERY_COMPLETED'
	| 'CUSTOMER_CANCELED'
	| 'MERCHANT_ACCEPTED'
	| 'MERCHANT_REJECTED'
	| 'MERCHANT_CANCELED'
	| 'MERCHANT_PREPARING'
	| 'MERCHANT_DELAYED'
	| 'MERCHANT_READY_FOR_PICKUP'
	| 'MERCHANT_REFUNDED'
	| 'MERCHANT_HIGH_DEMAND'
	| 'CUSTOMER_PICKED_UP';

export type VEHICLE_CATEGORY = 'STANDARD' | 'PREMIUM';

export type VEHICLE_CLASS =
	| 'SEDAN'
	| 'CARAVAN'
	| 'SUV'
	| 'MINIVAN'
	| 'VAN'
	| 'MINIBUS'
	| 'BUS'
	| 'CARGO_VAN'
	| 'PRIVATE_DRIVER';

export type GENDER = 'MALE' | 'FEMALE' | 'OTHER';

export type COMPANY_ROLE = 'DIRECTOR' | 'MANAGER' | 'REPRESENTATIVE_OF_SALES' | 'HEAD_OF_PROCUREMENT';

export type RESERVATION_STATUS =
	| 'PENDING'
	| 'TABLE_RESERVATION_ACCEPTED'
	| 'TABLE_RESERVATION_REJECTED'
	| 'TABLE_RESERVATION_CANCELED'
	| 'TABLE_RESERVATION_COMPLETED'
	| 'TABLE_RESERVATION_EXPIRED';

export type ORDER_TYPE =
	| 'TAXI'
	| 'TRANSFER_PRIVATE'
	| 'TRANSFER_SHUTTLE'
	| 'VEHICLE_TRANSFER'
	| 'VEHICLE_TRANSFER_COMBO';

export type ORDER_SUBTYPE = 'CREATED_BY_USER' | 'CREATED_BY_DISPATCHER' | 'CREATED_BY_BUSINESS';

export type SORTING_TYPE = 'AUTOMATIC' | 'MANUAL';

export type LOST_FOUND_STATUS = 'REPORTED' | 'RESOLVED';

export type CASHBACK_TYPE = 'TAXI' | 'DELIVERY' | 'TRANSFER';

export type CASHBACK_SOURCE = 'ORDER' | 'PROMOTIONAL' | 'SYSTEM_GRANT' | 'CONVERSION';

export type CASHBACK_STATUS = 'PENDING' | 'CONVERTED' | 'EXPIRED';

export type CREDIT_STATUS = 'ACTIVE' | 'USED' | 'EXPIRED';

export type FUNDS_TYPE = 'FUNDS' | 'CREDITS_ANY' | 'CREDITS_TAXI' | 'CREDITS_TRANSFER' | 'CREDITS_DELIVERY';

export type SCORING_POINTS_REASON =
	| 'IGNORED'
	| 'REJECTED'
	| 'CANCELED'
	| 'AUTO_REJECTED'
	| 'LATE'
	| 'LARGE_DELAY'
	| 'INSUFFICIENT_DATA';

export type ACTIVITY_TYPE = 'ONLINE' | 'OFFLINE' | 'LOCKED_OUT';

export type DAY_OF_WEEK = 'MON' | 'TUE' | 'WED' | 'THU' | 'FRI' | 'SAT' | 'SUN';

export type BOOKING_STATUS = 'reserved' | 'cancelled' | 'no_show';

export type SCHEDULE_SLOT_EXCEPTION_TYPE = 'vacation' | 'location_closed' | 'other' | 'health' | 'break' | 'lunch';

export type MODULE_TYPE = 'reservations' | 'delivery' | 'crm' | 'taxi';

export type PERMISSION_SCOPE = 'GLOBAL' | 'BUSINESS' | 'USER';

export type finances = {
	finance_id: string;
	bank_name: string;
	account_holder: string;
	account_number: string;
	payment_preferences: JsonValue;
	created_at: Date;
	updated_at: Date;
	business?: business[];
};

export type business = {
	business_id: string;
	address_id: string | null;
	delivery_address_id: string | null;
	finance_id: string | null;
	type: BUSINESS_TYPE;
	is_business_unit: boolean;
	business_group_name: string | null;
	name: string;
	description: string | null;
	tax_id: string;
	registration_id: string;
	email: string;
	telephone: string | null;
	telephone_code: string;
	telephone_number: string;
	website_url: string | null;
	working_hours: JsonValue | null;
	seats: number | null;
	minimum_order: number;
	offers_daily_meals: boolean;
	daily_meals_days: DAY_OF_WEEK[];
	daily_meals_delivery_mapping: JsonValue | null;
	maximum_daily_meals_subscribers: number | null;
	popular: boolean;
	new: boolean;
	created_at: Date;
	updated_at: Date;
	address?: addresses | null;
	delivery_address?: addresses | null;
	finances?: finances | null;
	business_users?: business_users[];
	documents?: documents[];
	parent_business_id: string | null;
	parent_business?: business | null;
	child_businesses?: business[];
	taxi_orders?: taxi_orders[];
	delivery_orders?: delivery_orders[];
	menus?: menus[];
	reviewable_id: string | null;
	reviewable?: reviewable | null;
	stripe_account_id: string | null;
	stripe_customer_id: string | null;
	word_buy_stripe_product_id: string | null;
	word_buy_stripe_product?: local_products | null;
	word_buy_stripe_subscription_id: string | null;
	word_buys?: word_buy[];
	reservations?: reservations[];
	daily_users_sorted: JsonValue | null;
	daily_users_sorting_type: SORTING_TYPE;
	restaurant_overwhelmed: boolean;
	promo_sections?: promo_sections_buy[];
	business_teams?: business_teams[];
	business_order_lobbies?: order_lobbies[];
	first_activated_at: Date | null;
	active: boolean;
	sales_representative_id: string | null;
	user_favorite_businesses?: user_favorite_businesses[];
	scoring_points?: scoring_points[];
	daily_meal_drivers?: delivery_drivers[];
	late_events?: late_events[];
	fiscal_device?: fiscal_devices | null;
	fiscal_devices_id: string | null;
	daily_meals_subscribers?: daily_meals_subscriptions[];
	account_actions?: account_actions[];
	business_clients?: business_clients[];
	purchase_order_limit_amount: number | null;
	drivers?: drivers[];
	daily_meal_categories?: daily_meal_categories[];
	daily_meal_subscriptions?: daily_meal_subscriptions[];
	business_local_locations?: business_local_locations[];
	business_money_flows?: business_money_flows[];
	reservation_module?: reservation_module | null;
};

export type local_locations = {
	local_location_id: string;
	address_id: string;
	created_at: Date;
	updated_at: Date;
	address?: addresses;
	business_local_locations?: business_local_locations[];
};

export type business_local_locations = {
	business_local_location_id: string;
	business_id: string;
	local_location_id: string;
	created_at: Date;
	updated_at: Date;
	time: Date;
	local_location?: local_locations;
	business?: business;
	orders?: delivery_orders[];
};

export type business_users = {
	business_users_id: string;
	online: boolean | null;
	company_role: COMPANY_ROLE;
	created_at: Date;
	updated_at: Date;
	user_id: string;
	users?: users | null;
	business_id: string;
	business?: business | null;
	operating_address_id: string | null;
	operating_address?: addresses | null;
	allowance?: allowances | null;
	taxi_orders?: taxi_orders[];
	employee?: employee | null;
};

export type business_clients = {
	business_clients_id: string;
	created_at: Date;
	updated_at: Date;
	business_id: string;
	business?: business | null;
	first_name: string | null;
	last_name: string | null;
	email: string | null;
	telephone: string;
	telephone_code: string;
	telephone_number: string;
	taxi_orders?: taxi_orders[];
};

export type cashback = {
	cashback_id: string;
	user_id: string;
	amount: number;
	type: CASHBACK_TYPE;
	source: CASHBACK_SOURCE;
	status: CASHBACK_STATUS;
	description: string | null;
	earned_at: Date;
	expires_at: Date | null;
	converted_at: Date | null;
	taxi_order_id: string | null;
	delivery_order_id: string | null;
	user?: users;
	taxi_order?: taxi_orders | null;
	delivery_order?: delivery_orders | null;
};

export type referrals = {
	referral_id: string;
	referral_code: string;
	referrer_user_id: string;
	referred_user_id: string;
	conditions_met: boolean;
	reward_claimed: boolean;
	created_at: Date;
	updated_at: Date;
	referrer?: users;
	referred?: users;
	credits?: wallet_funds[];
};

export type group_users = {
	group_user_id: string;
	parent_user_id: string;
	child_user_id: string;
	created_at: Date;
	updated_at: Date;
	parent_user?: users;
	child_user?: users;
	allowance?: allowances | null;
	enabled: boolean;
};

export type allowances = {
	allowance_id: string;
	group_user_id: string | null;
	business_users_id: string | null;
	amount_taxi_wallet: number;
	amount_transfer_wallet: number;
	amount_delivery_wallet: number;
	amount_any_wallet: number;
	amount_taxi_purchase_order: number | null;
	amount_transfer_purchase_order: number | null;
	amount_delivery_purchase_order: number | null;
	amount_any_purchase_order: number | null;
	created_at: Date;
	updated_at: Date;
	user?: group_users | null;
	business_user?: business_users | null;
};

export type documents = {
	document_id: string;
	document_type: DOCUMENT_TYPE;
	created_at: Date;
	updated_at: Date;
	expiration_date: Date | null;
	issue_date: Date | null;
	additional_info: JsonValue | null;
	public: boolean;
	files?: files[];
	driver_id: string | null;
	drivers?: drivers | null;
	delivery_driver_id: string | null;
	delivery_driver?: delivery_drivers | null;
	business_id: string | null;
	business?: business | null;
	user_id: string | null;
	user?: users | null;
	vehicle_id: string | null;
	vehicles?: vehicles | null;
	menu_item_id: string | null;
	menu_items?: menu_items | null;
	lost_item_id: string | null;
	lost_items?: lost_items | null;
	transaction_id: string | null;
	transactions?: transactions | null;
};

export type files = {
	file_id: string;
	url: string | null;
	file_type: FILE_TYPE;
	public: boolean;
	mime_type: string;
	created_at: Date;
	updated_at: Date;
	document_id: string | null;
	documents?: documents | null;
	categories?: categories[];
	blog_posts?: blog_posts[];
	promo_banners?: promo_banners[];
};

export type tokens = {
	token_id: string;
	user_id: string;
	type: TokenType;
	token: string;
	expires_at: Date;
	created_at: Date;
	updated_at: Date;
	active: boolean;
	users?: users;
};

export type addresses = {
	address_id: string;
	address: string;
	latitude: string;
	longitude: string;
	street: string | null;
	house_number: string | null;
	city: string | null;
	country: string | null;
	postal: string | null;
	users?: user_address[];
	businesses?: business[];
	businesses_delivery_address?: business[];
	business_users?: business_users[];
	daily_meals_subscriptions?: daily_meals_subscriptions[];
	daily_meal_subscriptions?: daily_meal_subscriptions[];
	local_locations?: local_locations | null;
};

export type user_address = {
	user_id: string;
	address_id: string;
	name: string | null;
	icon: string | null;
	primary: boolean;
	users?: users;
	address?: addresses;
};

export type driver_activity_settings = {
	driver_activity_settings_id: string;
	first_offline_lockout: number;
	second_offline_lockout: number;
	online_timeout: number;
	created_at: Date;
	updated_at: Date;
	active: boolean;
};

export type driver_activity_logs = {
	driver_activity_log_id: string;
	driver_id: string;
	activity_type: ACTIVITY_TYPE;
	started_at: Date;
	ended_at: Date | null;
	timeout_at: Date | null;
	lockout_until: Date | null;
	driver?: drivers;
};

export type delivery_drivers = {
	delivery_driver_id: string;
	online: boolean | null;
	on_order: boolean | null;
	delivers_daily_meals: boolean | null;
	working_hours: JsonValue | null;
	business_id: string | null;
	created_at: Date;
	updated_at: Date;
	user_id: string | null;
	user?: users | null;
	vehicles?: vehicles[];
	orders?: delivery_orders[];
	received_orders?: delivery_order_sent[];
	documents?: documents[];
	location: JsonValue | null;
	delivery_timeline: JsonValue | null;
	last_ping_at: Date;
	on_daily_meals: boolean | null;
	is_inactive: boolean | null;
	scheduled_meals_route: JsonValue | null;
	regions: string[];
	delivery_driver_history_locations?: delivery_driver_history_locations[];
	partner_cash_balance: number | null;
	daily_meal_business_id: string | null;
	daily_meal_business?: business | null;
	subscriptions?: daily_meal_subscriptions[];
};

export type drivers = {
	driver_id: string;
	business_id: string | null;
	online: boolean | null;
	on_order: boolean | null;
	working_hours: JsonValue | null;
	ride_requirements: JsonValue | null;
	created_at: Date;
	updated_at: Date;
	user_id: string | null;
	user?: users | null;
	vehicles?: vehicle_drivers[];
	current_vehicle_id: string | null;
	last_used_vehicle_id: string | null;
	orders?: taxi_orders[];
	received_orders?: taxi_order_sent[];
	delivery_orders?: delivery_orders[];
	received_delivery_orders?: delivery_order_sent[];
	documents?: documents[];
	location: JsonValue | null;
	delivery_timeline: JsonValue | null;
	last_ping_at: Date;
	is_inactive: boolean | null;
	transfer_requirements: JsonValue | null;
	regions: string[];
	driver_history_locations?: driver_history_locations[];
	handles_taxi_orders: boolean | null;
	handles_transfer_orders: boolean | null;
	handles_delivery_orders: boolean | null;
	taxi_orders_toggled: boolean | null;
	transfer_orders_toggled: boolean | null;
	delivery_orders_toggled: boolean | null;
	partner_cash_balance: number | null;
	come_to_work_last_sent_at: Date | null;
	driver_municipalities?: driver_municipalities[];
	current_vehicle?: vehicles | null;
	activity_logs?: driver_activity_logs[];
	business?: business | null;
};

export type vehicle_drivers = {
	vehicle_drivers_id: string;
	vehicle_id: string;
	driver_id: string;
	can_drive: boolean;
	created_at: Date;
	updated_at: Date;
	vehicle?: vehicles;
	driver?: drivers;
};

export type vehicles = {
	vehicle_id: string;
	business_id: string | null;
	active: boolean | null;
	class: VEHICLE_CLASS | null;
	category: VEHICLE_CATEGORY | null;
	make: string | null;
	model: string | null;
	color: string | null;
	license_plate: string | null;
	created_at: Date;
	updated_at: Date;
	documents?: documents[];
	drivers?: vehicle_drivers[];
	delivery_driver_id: string | null;
	delivery_driver?: delivery_drivers | null;
	vehicle_specification_id: string | null;
	vehicle_specification?: vehicle_specifications | null;
	taxi_orders?: taxi_orders[];
	delivery_orders?: delivery_orders[];
	current_driver?: drivers | null;
};

export type vehicle_specifications = {
	vehicle_specification_id: string;
	class: VEHICLE_CLASS;
	category: VEHICLE_CATEGORY;
	people: string;
	start_cost: string;
	per_kilometre: string;
	per_minute: string;
	vehicle_id: string | null;
	vehicle?: vehicles | null;
};

export type reviewable = {
	reviewable_id: string;
	reviews?: reviews[];
	user?: users[];
	business?: business[];
};

export type reviews = {
	review_id: string;
	reviewable_id: string;
	author_id: string;
	rating: number | null;
	comment: string | null;
	feedback: JsonValue | null;
	created_at: Date;
	updated_at: Date;
	reviewable?: reviewable;
	author?: users;
};

export type allergens = {
	allergen_id: string;
	name: string;
	description: string | null;
	code: number;
};

export type taxi_orders = {
	order_id: string;
	user_id: string;
	business_users_id: string | null;
	business_clients_id: string | null;
	driver_id: string | null;
	vehicle_id: string | null;
	route: JsonValue;
	pickup_location: JsonValue;
	delivery_location: JsonValue | null;
	payment: JsonValue | null;
	estimates: JsonValue | null;
	timeline: JsonValue;
	preferences: JsonValue | null;
	status: TAXI_ORDER_STATUS;
	last_sent_at: Date | null;
	created_at: Date;
	updated_at: Date;
	business_id: string | null;
	business?: business | null;
	driver?: drivers | null;
	vehicle?: vehicles | null;
	user?: users | null;
	business_users?: business_users | null;
	business_clients?: business_clients | null;
	history?: taxi_order_sent[];
	telephone: string | null;
	first_name: string | null;
	last_name: string | null;
	cancellation_reason: string | null;
	find_drivers_attempts: number | null;
	is_scheduled: boolean;
	parent_order_id: string | null;
	parent_order?: taxi_orders | null;
	grouped_orders?: taxi_orders[];
	type: ORDER_TYPE;
	subtype: ORDER_SUBTYPE;
	flags: JsonValue | null;
	cargo_preferences: JsonValue | null;
	driver_history_locations?: driver_history_locations[];
	wallet_transfer?: wallet_transfer_history[];
	transactions?: transactions[];
	customer_note: string | null;
	parent_user_type: string | null;
	creating_user_id: string | null;
	cashback?: cashback[];
	allow_credits_usage: boolean;
	order_number: number;
	scoring_points?: scoring_points[];
	late_events?: late_events[];
};

export type taxi_order_sent = {
	taxi_order_sent_id: string;
	order_id: string;
	driver_id: string;
	accepted: boolean;
	location: JsonValue | null;
	timeline: JsonValue;
	created_at: Date;
	updated_at: Date;
	order?: taxi_orders | null;
	driver?: drivers | null;
	rejected: boolean;
};

export type delivery_orders = {
	order_id: string;
	user_id: string | null;
	route: JsonValue;
	pickup_location: JsonValue;
	delivery_location: JsonValue;
	payment: JsonValue | null;
	estimates: JsonValue | null;
	items: JsonValue;
	details: JsonValue | null;
	courier_instructions: JsonValue | null;
	restaurant_message: JsonValue | null;
	scheduled: JsonValue | null;
	timeline: JsonValue;
	status: DELIVERY_ORDER_STATUS;
	last_sent_at: Date | null;
	created_at: Date;
	updated_at: Date;
	user?: users | null;
	history?: delivery_order_sent[];
	vehicle_id: string | null;
	vehicle?: vehicles | null;
	delivery_driver_id: string | null;
	delivery_driver?: delivery_drivers | null;
	driver_id: string | null;
	driver?: drivers | null;
	business_id: string | null;
	business?: business | null;
	payment_intent_id: string | null;
	transactions?: transactions[];
	find_drivers_attempts: number | null;
	is_daily_meal: boolean;
	flags: JsonValue | null;
	wallet_transfer?: wallet_transfer_history[];
	driver_history_locations?: driver_history_locations[];
	delivery_driver_history_locations?: delivery_driver_history_locations[];
	cashback?: cashback[];
	order_lobbies?: order_lobbies | null;
	allow_credits_usage: boolean;
	order_number: number;
	scoring_points?: scoring_points[];
	late_events?: late_events[];
	stock_movements?: menu_item_stock_change[];
	business_local_location_id: string | null;
	business_local_locations?: business_local_locations | null;
};

export type delivery_order_sent = {
	delivery_order_sent_id: string;
	order_id: string;
	accepted: boolean;
	location: JsonValue;
	timeline: JsonValue;
	created_at: Date;
	updated_at: Date;
	order?: delivery_orders | null;
	delivery_driver_id: string | null;
	delivery_driver?: delivery_drivers | null;
	driver_id: string | null;
	driver?: drivers | null;
};

export type menus = {
	menu_id: string;
	business_id: string;
	active: boolean;
	business?: business;
	categories?: menu_categories[];
	menu_categories_ordered: JsonValue | null;
	isDailyMeal: boolean;
	date: Date | null;
	daily_meal_subscribers?: daily_meals_subscriptions[];
};

export type menu_categories = {
	menu_category_id: string;
	names: JsonValue | null;
	description: JsonValue | null;
	categories: string[];
	business_id: string;
	menu_items?: menu_items[];
	menu_id: string | null;
	menu?: menus | null;
	order: number | null;
	price: number | null;
	menu_items_ordered: JsonValue | null;
	menu_categories_categories?: menu_categories_categories[];
	menu_order_index: number | null;
	daily_meal_subscribers?: daily_meals_subscriptions[];
	daily_meal_category_id: string | null;
	daily_meal_category_price_id: string | null;
	daily_meal_category?: daily_meal_categories | null;
	daily_meal_category_price?: daily_meal_category_prices | null;
	daily_meal_instances?: daily_meal_instances[];
};

export type menu_items = {
	menu_item_id: string;
	names: JsonValue;
	image: string | null;
	description: JsonValue;
	allergens: string[];
	spicy_level: number | null;
	unit_size: string | null;
	price: number;
	discount: number | null;
	sides: string[];
	extras: string[];
	ingredients: JsonValue;
	availability: string[];
	business_id: string;
	menu_category_id: string | null;
	daily_date: Date | null;
	menu_category?: menu_categories | null;
	documents?: documents[];
	requires_id_check: boolean;
	is_enabled: boolean;
	is_copy: boolean;
	menu_category_order_index: number | null;
	order_lobby_items?: order_lobby_items[];
	allergens_text: JsonValue | null;
	ingredients_text: JsonValue | null;
	usage_text: JsonValue | null;
	origin_text: JsonValue | null;
	is_weighted: boolean;
	weight_quantity: number | null;
	stock: number | null;
	stock_movements?: menu_item_stock_change[];
	tax_rates_id: string | null;
	tax_rate?: tax_rates | null;
};

export type transactions = {
	transaction_id: string;
	user_id: string;
	amount: number;
	type: TRANSACTION_TYPE;
	description: string | null;
	createdAt: Date;
	updatedAt: Date;
	delivery_order_id: string | null;
	taxi_order_id: string | null;
	wallet_fund_id: string | null;
	taxi_order?: taxi_orders | null;
	delivery_order?: delivery_orders | null;
	user?: users;
	documents?: documents[];
	wallet_funds?: wallet_funds | null;
};

export type user_money_flows = {
	balance_change_id: string;
	user_id: string;
	amount: number;
	stripe_fee: number;
	type: TRANSACTION_TYPE;
	payment_method: PAYMENT_METHOD | null;
	created_at: Date;
	user?: users;
};

export type business_money_flows = {
	balance_change_id: string;
	business_id: string;
	amount: number;
	stripe_fee: number;
	type: TRANSACTION_TYPE;
	payment_method: PAYMENT_METHOD | null;
	created_at: Date;
	business?: business;
};

export type payment_intent_logs = {
	payment_intent_logs_id: string;
	stripe_id: string;
	created_at: Date;
};

export type reservations = {
	reservation_id: string;
	seats: number;
	date: Date;
	time: string;
	datetime: Date;
	created_at: Date;
	updated_at: Date;
	business_id: string;
	business?: business;
	user_id: string;
	user?: users;
	status: RESERVATION_STATUS;
	table: number | null;
};

export type lost_items = {
	lost_item_id: string;
	user_id: string | null;
	status: LOST_FOUND_STATUS;
	description: string;
	documents?: documents[];
	found: boolean | null;
	created_at: Date;
	updated_at: Date;
	user?: users | null;
};

export type flags = {
	flag_id: string;
	name: string;
	status: boolean;
	created_at: Date;
	updated_at: Date;
	history?: flag_history[];
};

export type flag_history = {
	flag_history_id: string;
	flag_id: string;
	user_id: string;
	status: boolean;
	created_at: Date;
	updated_at: Date;
	flag?: flags;
	user?: users;
};

export type driver_history_locations = {
	driver_history_location_id: string;
	driver_id: string;
	taxi_order_id: string | null;
	delivery_order_id: string | null;
	status: string | null;
	location: JsonValue | null;
	driver?: drivers | null;
	order?: taxi_orders | null;
	delivery_order?: delivery_orders | null;
	created_at: Date;
	updated_at: Date;
};

export type delivery_driver_history_locations = {
	delivery_driver_history_location_id: string;
	delivery_driver_id: string;
	order_id: string | null;
	status: DELIVERY_ORDER_STATUS | null;
	location: JsonValue | null;
	delivery_driver?: delivery_drivers | null;
	order?: delivery_orders | null;
	created_at: Date;
	updated_at: Date;
};

export type wallet_transfer_history = {
	wallet_transfer_history_id: string;
	order_id: string;
	amount: number;
	created_at: Date;
	updated_at: Date;
	success: boolean;
	delivery_order?: delivery_orders | null;
	taxi_order?: taxi_orders | null;
};

export type wallet_funds = {
	wallet_funds_id: string;
	user_id: string;
	referral_id: string | null;
	charge_id: string | null;
	amount: number;
	reserved_order: string | null;
	reserved_daily_meals_subscription: string | null;
	reserved_business: string | null;
	created_at: Date;
	updated_at: Date;
	expires_at: Date | null;
	type: FUNDS_TYPE;
	status: CREDIT_STATUS | null;
	referral?: referrals | null;
	user?: users;
	transactions?: transactions[];
};

export type local_products = {
	local_product_id: string;
	name: string;
	description: string | null;
	prices?: local_prices[];
	currency: string;
	stripe_product_id: string;
	business_id: string;
	business?: business;
	created_at: Date;
	updated_at: Date;
};

export type local_prices = {
	local_prices_id: string;
	local_product_id: string;
	product?: local_products;
	currency: string;
	stripe_price_id: string;
	stripe_product_id: string;
	tier: string | null;
	created_at: Date;
	updated_at: Date;
};

export type categories = {
	categories_id: string;
	name: string;
	description: string | null;
	tag: string;
	icon_file_id: string | null;
	icon?: files | null;
	category_type: CATEGORY_TYPE;
	menu_categories?: menu_categories_categories[];
	promo_ads_category?: promo_ads_category[];
	parent_categories_id: string | null;
	parent_category?: categories | null;
	sub_categories?: categories[];
	translatable_id: string;
	translatable?: translatable;
	words?: words[];
	created_at: Date;
	updated_at: Date;
	deleted_at: Date | null;
	daily_meal_categories?: daily_meal_categories[];
};

export type menu_categories_categories = {
	menu_categories_id: string;
	categories_id: string;
	menu_category?: menu_categories;
	category?: categories;
};

export type promo_sections = {
	promo_sections_id: string;
	name: string;
	tag: string;
	active: boolean;
	description: string | null;
	prices: JsonValue | null;
	limits: JsonValue | null;
	stripe_product_id: string | null;
	canPurchase: boolean;
	t1price: number | null;
	t2price: number | null;
	t3price: number | null;
	order: number;
	service_type: PROMO_SERVICE_TYPES;
	promo_section_buy?: promo_sections_buy[];
	promo_duration_days: number;
	translatable_id: string;
	translatable?: translatable;
	display_cards_per_page: number | null;
};

export type promo_banners = {
	promo_banners_id: string;
	type: string;
	size: string | null;
	title: string;
	text: string;
	promo_section_buy_id: string | null;
	file_id: string;
	files?: files;
	promo_ads_id: string | null;
	promo_ads?: promo_ads | null;
};

export type promo_sections_buy = {
	promo_sections_buy_id: string;
	promo_sections_id: string;
	promo_section?: promo_sections;
	payment_intent_id: string | null;
	business_id: string;
	business?: business;
	user_id: string | null;
	bought_by?: users | null;
	paid: boolean;
	active_at: Date | null;
	expires_at: Date | null;
	tier: number;
};

export type promo_ads = {
	promo_ads_id: string;
	title: string;
	text: string;
	tag: string;
	service_type: PROMO_SERVICE_TYPES;
	discount: number;
	banner?: promo_banners[];
	categories?: promo_ads_category[];
	active: boolean;
	code: number | null;
	created_at: Date;
	active_at: Date | null;
	active_until: Date | null;
};

export type promo_ads_category = {
	promo_ads_category_id: string;
	promo_ads_id: string;
	categories_id: string;
	promo_ad?: promo_ads;
	category?: categories;
};

export type words = {
	word_id: string;
	word: string;
	popularity: number;
	categories_id: string | null;
	category?: categories | null;
	translatable_id: string;
	translatable?: translatable;
	subscriptions?: word_buy[];
	bundles?: word_bundles[];
	created_at: Date;
	updated_at: Date;
};

export type word_buy = {
	word_buy_id: string;
	word_id: string;
	word?: words;
	stripe_subscription_id: string | null;
	stripe_price_id: string | null;
	pending_stripe_price_id: string | null;
	price: number;
	pending_price: number | null;
	active_at: Date | null;
	expires_at: Date | null;
	paid: boolean;
	business_id: string;
	business?: business;
	created_at: Date;
	updated_at: Date;
	deleted_at: Date | null;
};

export type word_bundles = {
	id: string;
	name: string;
	description: string | null;
	words?: words[];
	created_at: Date;
};

export type order_lobbies = {
	order_lobbies_id: string;
	lobby_name: string;
	lobby_description: string;
	active: boolean;
	delivery_location: JsonValue | null;
	courier_note: string | null;
	restaurant_message: string | null;
	business_id: string;
	restaurant_id: string;
	creator_id: string;
	delivery_orders_id: string | null;
	created_at: Date;
	updated_at: Date;
	order_lobby_items?: order_lobby_items[];
	order_lobby_users?: order_lobby_users[];
	delivery_orders?: delivery_orders | null;
	business?: business | null;
};

export type order_lobby_items = {
	order_lobby_items_id: string;
	order_lobbies_id: string;
	menu_item_id: string;
	user_id: string | null;
	sides: string[];
	extras: string[];
	quantity: number;
	customer_note: string | null;
	created_at: Date;
	updated_at: Date;
	menu_items?: menu_items | null;
	order_lobbies?: order_lobbies;
};

export type order_lobby_users = {
	order_lobby_users_id: string;
	user_id: string;
	order_lobbies_id: string;
	limit: number;
	created_at: Date;
	updated_at: Date;
	order_lobbies?: order_lobbies;
	users?: users;
};

export type business_teams = {
	business_teams_id: string;
	team_name: string;
	business_id: string;
	limit_per_person: number;
	created_at: Date;
	updated_at: Date;
	users?: users[];
	business?: business;
};

export type translatable = {
	translatable_id: string;
	translations?: translations[];
	words?: words[];
	categories?: categories[];
	promo_sections?: promo_sections[];
};

export type translations = {
	translations_id: string;
	translatable_id: string;
	translatable?: translatable;
	field: string | null;
	language: string;
	translation: string;
	created_at: Date;
	updated_at: Date;
};

export type user_favorite_businesses = {
	user_favorite_businesses_id: string;
	user_id: string;
	business_id: string;
	business_type: BUSINESS_TYPE;
	created_at: Date;
	updated_at: Date;
	users?: users;
	businesses?: business;
};

export type scoring_points = {
	scoring_points_id: string;
	business_id: string;
	user_id: string | null;
	delivery_order_id: string | null;
	taxi_order_id: string | null;
	points: number;
	isPenalty: boolean;
	reason: SCORING_POINTS_REASON;
	expiration_date: Date | null;
	created_at: Date;
	updated_at: Date;
	users?: users | null;
	businesses?: business | null;
	delivery_orders?: delivery_orders | null;
	taxi_orders?: taxi_orders | null;
	late_events?: late_events[];
};

export type late_events = {
	late_events_id: string;
	business_id: string;
	user_id: string;
	delivery_order_id: string | null;
	taxi_order_id: string | null;
	scoring_points_id: string | null;
	seconds: number;
	created_at: Date;
	updated_at: Date;
	users?: users | null;
	businesses?: business;
	delivery_orders?: delivery_orders | null;
	taxi_orders?: taxi_orders | null;
	scoring_points?: scoring_points | null;
};

export type municipalities = {
	municipalities_id: string;
	name: string;
	geojson: JsonValue;
	requires_license: boolean;
	gis_sifra: string | null;
	eid_obcina: string | null;
	feature_id: string | null;
	created_at: Date;
	updated_at: Date;
	driver_municipalities?: driver_municipalities[];
	settlements?: settlements[];
	weather_data?: weather_data[];
};

export type fiscal_devices = {
	fiscal_devices_id: string;
	name: string;
	created_at: Date;
	updated_at: Date;
	businesses?: business[];
};

export type driver_municipalities = {
	driver_municipalities_id: string;
	driver_id: string;
	municipalities_id: string;
	created_at: Date;
	updated_at: Date;
	drivers?: drivers;
	municipalities?: municipalities;
};

export type settlements = {
	settlement_id: string;
	name: string;
	municipalities_id: string;
	eid_naselje: string | null;
	feature_id: string | null;
	geojson: JsonValue;
	created_at: Date;
	updated_at: Date;
	municipality?: municipalities;
	weather_data?: weather_data[];
};

export type weather_data = {
	weather_data_id: string;
	time_epoch: bigint;
	time: Date;
	temp_c: number;
	is_day: boolean;
	condition_text: string;
	condition_icon: string;
	condition_code: number;
	wind_kph: number;
	wind_degree: number;
	wind_dir: string;
	pressure_mb: number;
	precip_mm: number;
	snow_cm: number;
	humidity: number;
	cloud: number;
	feelslike_c: number;
	windchill_c: number;
	heatindex_c: number;
	dewpoint_c: number;
	will_it_rain: boolean;
	chance_of_rain: number;
	will_it_snow: boolean;
	chance_of_snow: number;
	vis_km: number;
	gust_kph: number;
	uv: number;
	icon: string;
	created_at: Date;
	updated_at: Date;
	municipalities_id: string | null;
	municipality?: municipalities | null;
	settlement_id: string | null;
	settlement?: settlements | null;
};

export type account_actions = {
	account_action_id: string;
	business_id: string | null;
	user_id: string | null;
	created_at: Date;
	action_creator_user_id: string;
	reason: ACCOUNT_ACTIONS_REASON;
	action: ACCOUNT_ACTIONS;
	business?: business | null;
	user?: users | null;
	action_creator?: users | null;
};

export type daily_meals_subscriptions = {
	daily_meals_subscriptions_id: string;
	grouped_id: string;
	user_id: string;
	business_id: string;
	menu_id: string;
	address_id: string;
	menu_categories_id: string;
	created_at: Date;
	updated_at: Date;
	date: Date;
	quantity: number;
	order_created: Date | null;
	restaurant_comment: string | null;
	courier_comment: string | null;
	menu_category?: menu_categories;
	user?: users;
	business?: business;
	menu?: menus;
	address?: addresses;
	status: SUBSCRIPTION_STATUS;
	payment?: payments | null;
};

export type daily_meal_subscriptions = {
	id: string;
	user_id: string;
	business_id: string;
	delivery_address_id: string;
	delivery_driver_id: string | null;
	start_date: Date;
	end_date: Date | null;
	type: SUBSCRIPTION_TYPE;
	status: SUBSCRIPTION_STATUS;
	courier_comment: string | null;
	created_at: Date;
	updated_at: Date;
	user?: users;
	delivery_driver?: delivery_drivers | null;
	delivery_address?: addresses;
	business?: business;
	customers?: daily_meal_subscription_customers[];
	days?: daily_meal_subscription_days[];
	weekdays?: daily_meal_subscription_weekdays[];
	daily_meal_instances?: daily_meal_instances[];
};

export type daily_meal_subscription_customers = {
	id: string;
	subscription_id: string;
	daily_meal_category_id: string;
	first_name: string;
	last_name: string;
	telephone: string;
	restaurant_comment: string | null;
	created_at: Date;
	updated_at: Date;
	subscription?: daily_meal_subscriptions;
	daily_meal_instances?: daily_meal_instances[];
	daily_meal_categories?: daily_meal_categories | null;
};

export type daily_meal_subscription_days = {
	id: string;
	subscription_id: string;
	intended_date: Date;
	delivery_date: Date;
	subscription?: daily_meal_subscriptions;
};

export type daily_meal_subscription_weekdays = {
	id: string;
	subscription_id: string;
	intended_weekday: number;
	delivery_weekday: number;
	subscription?: daily_meal_subscriptions;
};

export type daily_meal_instances = {
	id: string;
	subscription_id: string;
	subscription_customer_id: string;
	menu_category_id: string;
	status: DAILY_MEAL_INSTANCE_STATUS;
	intended_date: Date;
	delivery_date: Date;
	created_at: Date;
	updated_at: Date;
	subscription?: daily_meal_subscriptions;
	customer?: daily_meal_subscription_customers;
	menu_category?: menu_categories;
};

export type payments = {
	payment_id: string;
	amount: number;
	credits_amount: number;
	payment_method: PAYMENT_METHOD;
	payment_intent_id: string | null;
	status: PAYMENT_STATUS;
	created_at: Date;
	updated_at: Date;
	order_type: string | null;
	payment_type: string | null;
	subscription_grouped_id: string | null;
	subscriptions?: daily_meals_subscriptions[];
	user_id: string;
	user?: users;
	payment_splits?: payment_splits[];
};

export type payment_splits = {
	payment_split_id: string;
	status: SPLIT_STATUS;
	payment_id: string;
	destination_type: SPLIT_DESTINATION_TYPE;
	destination_id: string | null;
	amount_regular: number;
	amount_credits: number;
	metadata: JsonValue | null;
	created_at: Date;
	updated_at: Date;
	payment?: payments;
};

export type daily_meal_categories = {
	daily_meal_category_id: string;
	business_id: string;
	category_id: string;
	created_at: Date;
	start_date: Date;
	active: boolean;
	category?: categories;
	business?: business;
	menu_categories?: menu_categories[];
	daily_meal_subscription_customers?: daily_meal_subscription_customers[];
	daily_meal_category_prices?: daily_meal_category_prices[];
};

export type daily_meal_category_prices = {
	daily_meal_category_prices_id: string;
	daily_meal_category_id: string;
	price: number;
	valid_from: Date;
	created_at: Date;
	daily_meal_category?: daily_meal_categories;
	menu_categories?: menu_categories[];
};

export type blog_tags = {
	blog_tags_id: string;
	name: string;
	description: string | null;
	blog_posts?: blog_posts[];
};

export type blog_categories = {
	blog_categories_id: string;
	name: string;
	description: string | null;
	blog_posts?: blog_posts[];
};

export type blog_posts = {
	blog_posts_id: string;
	slug: string;
	title: string;
	short_content: string | null;
	image_file_id: string | null;
	image?: files | null;
	content: JsonValue;
	status: BLOG_POST_STATUS;
	author_id: string;
	category_id: string | null;
	publish_at: Date;
	created_at: Date;
	updated_at: Date;
	author?: users;
	category?: blog_categories | null;
	tags?: blog_tags[];
};

export type menu_item_stock_change = {
	id: string;
	menu_item_id: string;
	quantity: number;
	reason: string;
	menu_item?: menu_items;
	order_id: string | null;
	order?: delivery_orders | null;
	created_at: Date;
};

export type tax_rates = {
	tax_rates_id: string;
	name: string;
	description: string | null;
	country: string | null;
	rate: number;
	active: boolean;
	valid_from: Date;
	created_at: Date;
	updated_at: Date;
	menu_items?: menu_items[];
};

export type reservation_module = {
	reservation_module_id: string;
	business_id: string;
	subscription_id: string | null;
	subscription_active_until: Date | null;
	business?: business;
	subscription?: subscription | null;
	subscription_exires_at: Date | null;
	addons?: business_addon[];
	usages?: business_usage[];
	locations?: location[];
	services?: service[];
	employees?: employee[];
	bookings?: booking[];
	customers?: customers[];
	service_categories?: service_category[];
	user_roles?: user_role[];
	user_permissions?: user_permission[];
};

export type location = {
	location_id: string;
	reservation_module_id: string;
	name: string;
	address: string;
	phone: string | null;
	color: string | null;
	accepts_online: boolean;
	closed_on_holidays: boolean;
	working_days: JsonValue;
	reservation_module?: reservation_module;
	schedules?: schedule[];
	bookings?: booking[];
};

export type service_category = {
	service_category_id: string;
	reservation_module_id: string;
	name: JsonValue;
	parent_id: string | null;
	color: string | null;
	parent?: service_category | null;
	children?: service_category[];
	services?: service[];
	reservation_module?: reservation_module;
};

export type service = {
	service_id: string;
	reservation_module_id: string;
	service_category_id: string | null;
	name: JsonValue;
	description: JsonValue | null;
	image_url: string | null;
	price_cents: number;
	discount_percent: number | null;
	discount_amount: number | null;
	duration_minutes: number;
	available_online: boolean;
	skd_codes: string[];
	created_at: Date;
	reservation_module?: reservation_module;
	service_category?: service_category | null;
	assigned_employees?: service_assignment[];
	bookings?: booking[];
};

export type employee = {
	employee_id: string;
	reservation_module_id: string;
	reservation_module?: reservation_module;
	assignments?: service_assignment[];
	schedules?: schedule_employee[];
	bookings?: booking[];
	business_users_id: string | null;
	business_user?: business_users | null;
	created_at: Date;
	deleted_at: Date | null;
};

export type customers = {
	customer_id: string;
	reservation_module_id: string;
	first_name: string;
	last_name: string;
	email: string | null;
	telephone: string | null;
	created_at: Date;
	updated_at: Date;
	reservation_module?: reservation_module;
	bookings?: booking[];
	user_id: string | null;
	user?: users | null;
};

export type service_assignment = {
	employee_id: string;
	service_id: string;
	employee?: employee;
	service?: service;
};

export type schedule = {
	schedule_id: string;
	location_id: string;
	name: string;
	color: string | null;
	start_date: Date;
	end_date: Date;
	location?: location;
	schedule_employees?: schedule_employee[];
	schedule_slots?: schedule_slot[];
};

export type schedule_employee = {
	schedule_employee_id: string;
	schedule_id: string;
	employee_id: string;
	schedule?: schedule;
	employee?: employee;
	schedule_slots?: schedule_slot[];
};

export type schedule_slot = {
	schedule_slot_id: string;
	schedule_id: string;
	schedule_employee_id: string;
	date: Date;
	start_time: Date;
	end_time: Date;
	booking_slots?: booking_slots[];
	schedule?: schedule;
	schedule_employee?: schedule_employee;
	schedule_slot_exceptions?: schedule_slot_exceptions[];
};

export type schedule_slot_exceptions = {
	schedule_slot_exception_id: string;
	schedule_slot_id: string;
	date: Date;
	start_time: Date;
	end_time: Date;
	reason: string | null;
	type: SCHEDULE_SLOT_EXCEPTION_TYPE;
	schedule_slot?: schedule_slot;
};

export type booking_slots = {
	booking_slot_id: string;
	schedule_slot_id: string;
	schedule_slot?: schedule_slot;
	start_time: Date;
	end_time: Date;
};

export type booking = {
	booking_id: string;
	customer_id: string;
	reservation_module_id: string;
	location_id: string | null;
	status: BOOKING_STATUS;
	service_id: string;
	comment: string | null;
	created_at: Date;
	updated_at: Date;
	price_cents: number | null;
	start_time: Date | null;
	end_time: Date | null;
	assigned_employee_id: string | null;
	parent_booking_id: string | null;
	parent_booking?: booking | null;
	child_bookings?: booking[];
	reservation_module?: reservation_module;
	location?: location | null;
	employee?: employee | null;
	service?: service | null;
	customer?: customers;
	booking_history_log?: booking_history_log[];
};

export type booking_history_log = {
	booking_history_id: string;
	booking_id: string;
	status: BOOKING_STATUS;
	comment: string | null;
	type: string | null;
	title: string | null;
	description: string | null;
	created_at: Date;
	updated_at: Date;
	user_id: string | null;
	user?: users | null;
	booking?: booking;
};

export type subscription = {
	subscription_id: string;
	module: MODULE_TYPE;
	name: string;
	price_cents: number;
	stripe_price_id: string;
	actions?: subscription_action[];
	business_modules?: reservation_module[];
};

export type addon = {
	addon_id: string;
	module: MODULE_TYPE;
	name: string;
	price_cents: number;
	stripe_price_id: string;
	actions?: addon_action[];
	business_addons?: business_addon[];
};

export type action = {
	action_id: string;
	module: MODULE_TYPE;
	name: string;
	subscription_actions?: subscription_action[];
	addon_actions?: addon_action[];
	business_usages?: business_usage[];
	permissions?: permission[];
	user_permissions?: user_permission[];
};

export type subscription_action = {
	subscription_action_id: string;
	subscription_id: string;
	action_id: string;
	module: MODULE_TYPE;
	limit: number | null;
	subscription?: subscription;
	action?: action;
};

export type addon_action = {
	addon_action_id: string;
	addon_id: string;
	action_id: string;
	module: MODULE_TYPE;
	limit: number | null;
	addon?: addon;
	action?: action;
};

export type business_addon = {
	business_addon_id: string;
	addon_id: string;
	reservation_module_id: string | null;
	sms_module_id: string | null;
	ads_module_id: string | null;
	addon?: addon;
	reservation_module?: reservation_module | null;
};

export type business_usage = {
	business_usage_id: string;
	action_id: string;
	used: number;
	reset_date: Date | null;
	reservation_module_id: string | null;
	action?: action;
	reservation_module?: reservation_module | null;
};

export type users = {
	user_id: string;
	first_name: string | null;
	last_name: string | null;
	password: string;
	gender: GENDER | null;
	email: string | null;
	telephone: string;
	telephone_code: string;
	telephone_number: string;
	date_of_birth: Date;
	created_at: Date;
	updated_at: Date;
	user_role: USER_ROLES;
	user_roles?: user_roles[];
	addresses?: user_address[];
	tokens?: tokens[];
	phone_verified: boolean;
	notification_preferences: JsonValue | null;
	taxi_preferences: JsonValue | null;
	business_users?: business_users[];
	driver?: drivers | null;
	orders?: taxi_orders[];
	documents?: documents[];
	delivery_driver?: delivery_drivers | null;
	delivery_orders?: delivery_orders[];
	reviewable_id: string | null;
	reviewable?: reviewable | null;
	reviews?: reviews[];
	review_complete: boolean;
	one_signal_id: string | null;
	stripe_customer_id: string | null;
	wallet_balance: number;
	transactions?: transactions[];
	reservations?: reservations[];
	transfer_preferences: JsonValue | null;
	allergies_preferences: JsonValue | null;
	spicy_preferences: JsonValue | null;
	radio_preferences: JsonValue | null;
	subscribed_to_daily_meals: boolean;
	daily_meal_preferences: JsonValue | null;
	details: JsonValue | null;
	flag_changes?: flag_history[];
	taxi_push_notification_preferences: JsonValue | null;
	transfer_push_notification_preferences: JsonValue | null;
	delivery_push_notification_preferences: JsonValue | null;
	spoken_languages: JsonValue | null;
	lost_items?: lost_items[];
	daily_meal_day_preferences: JsonValue | null;
	disabled: boolean;
	active: boolean;
	child_users?: group_users[];
	parent_user?: group_users | null;
	language: string | null;
	wallet_funds?: wallet_funds[];
	apple_id: string | null;
	google_id: string | null;
	referral_code: string | null;
	referrals_made?: referrals[];
	referral?: referrals | null;
	cashback?: cashback[];
	activated_at: Date | null;
	business_teams_id: string | null;
	business_teams?: business_teams | null;
	order_lobby_users?: order_lobby_users[];
	promo_section_buys?: promo_sections_buy[];
	allow_marketing_push_notifications: boolean | null;
	allow_ads_personalization: boolean | null;
	allow_newsletter: boolean | null;
	user_favorite_businesses?: user_favorite_businesses[];
	scoring_points?: scoring_points[];
	daily_meals_subscriptions?: daily_meals_subscriptions[];
	late_events?: late_events[];
	account_actions?: account_actions[];
	created_account_actions?: account_actions[];
	blog_posts?: blog_posts[];
	payments?: payments[];
	daily_meal_subscriptions?: daily_meal_subscriptions[];
	user_money_flows?: user_money_flows[];
	customer?: customers[];
	booking_history_log?: booking_history_log[];
	roles?: user_role[];
	user_permissions?: user_permission[];
};

export type user_roles = {
	user_roles_id: string;
	user_id: string;
	user?: users;
	role: USER_ROLES;
	primary: boolean | null;
};

export type role = {
	role_id: string;
	name: string;
	module: MODULE_TYPE;
	business_id: string | null;
	permissions?: permission[];
	users?: user_role[];
};

export type user_role = {
	user_id: string;
	role_id: string;
	reservation_module_id: string | null;
	user?: users;
	role?: role;
	reservation_module?: reservation_module | null;
};

export type permission = {
	permission_id: string;
	role_id: string;
	action_id: string | null;
	name: string | null;
	module: MODULE_TYPE;
	limit: number | null;
	scope: PERMISSION_SCOPE;
	role?: role;
	action?: action | null;
};

export type user_permission = {
	user_permission_id: string;
	user_id: string;
	reservation_module_id: string | null;
	action_id: string | null;
	name: string | null;
	module: MODULE_TYPE;
	limit: number | null;
	scope: PERMISSION_SCOPE;
	user?: users;
	action?: action | null;
	reservation_module?: reservation_module | null;
};

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
