import { DELIVERY_ORDER_STATUS } from '@prisma/client';

import type { LineItem } from '../menuItems/LineItem.js';
import type { User } from '../users/User.js';
import type { Vehicle } from '../vehicles/Vehicle.js';
import type { Driver } from '../drivers/Driver.js';
import type { TransportModule } from '../transport/TransportModule.js';
import type { Transaction } from '../payments/Transaction.js';
import type { DriverHistoryLocation } from '../drivers/DriverHistoryLocation.js';
import type { Cashback } from '../cashback/Cashback.js';
import type { OrderLobby } from '../orderLobbies/OrderLobby.js';
import type { ScoringPoint } from '../general/ScoringPoint.js';
import type { LateEvent } from '../general/LateEvent.js';
import type { BusinessLocalLocation } from '../stores/BusinessLocalLocation.js';
import type { PromoAnalytic } from '../promoAnalytics/PromoAnalytic.js';
import type { Invoice } from '../invoices/Invoice.js';
import type { Review } from '../reviews/Review.js';
import type { StoresModule } from '../stores/StoresModule.js';
import type { FoodDrinksModule } from '../foodDrinks/FoodDrinksModule.js';
import type { File } from '../files/File.js';
import type { DeliveryOrderSent } from './DeliveryOrderSent.js';
import type { WalletTransferHistory } from '../wallet/WalletTransferHistory.js';
import type { MenuItemStockChange } from '../menuItems/MenuItemStockChange.js';

// Auto-generated shape by scripts/generate-dtos.js (mode: map). Do not edit manually.

export type DeliveryOrder = {
	order_id: string;
	user_id?: string | null;
	route: unknown;
	pickup_location: unknown;
	delivery_location: unknown;
	payment?: unknown | null;
	estimates?: unknown | null;
	items: LineItem[];
	details?: unknown | null;
	courier_instructions?: string | null;
	restaurant_message?: string | null;
	rejection_reason?: string | null;
	scheduled_at?: string | null;
	timeline: unknown;
	status: DELIVERY_ORDER_STATUS;
	last_sent_at?: string | null;
	created_at: string;
	updated_at: string;
	customer?: User | null;
	history: DeliveryOrderSent[];
	vehicle_id?: string | null;
	vehicle?: Vehicle | null;
	driver_id?: string | null;
	driver?: Driver | null;
	transport_module_id?: string | null;
	transport_module?: TransportModule | null;
	payment_intent_id?: string | null;
	transactions: Transaction[];
	find_drivers_attempts?: number | null;
	is_daily_meal: boolean;
	wallet_transfer: WalletTransferHistory[];
	driver_history_locations: DriverHistoryLocation[];
	cashback: Cashback[];
	order_lobbies?: OrderLobby | null;
	allow_credits_usage: boolean;
	order_number: number;
	scoring_points: ScoringPoint[];
	late_events: LateEvent[];
	stock_movements: MenuItemStockChange[];
	business_local_location_id?: string | null;
	business_local_location?: BusinessLocalLocation | null;
	promo_analytics: PromoAnalytic[];
	invoice?: Invoice | null;
	review_id?: string | null;
	review?: Review | null;
	stores_id?: string | null;
	stores_module?: StoresModule | null;
	food_drinks_id?: string | null;
	food_drinks_module?: FoodDrinksModule | null;
	file_id?: string | null;
	picture_of_delivery?: File | null;
};
