#!/usr/bin/env node
/*
  Simple Prisma model -> DTO generator
  - Parses prisma/schemas/*.prisma
  - Generates types/dtos/<Model>DTO.ts with:
	- <Model>DTO (response)
	- <Model>CreateDTO (input)
	- <Model>UpdateDTO (input, all optional)
	- picker helpers for create/update

  Usage:
	node scripts/generate-dtos.js users
	node scripts/generate-dtos.js all
*/

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { generateModelTypeFromSchemas, modelNameToTypeName } from './utils/schemaMapper.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(path.join(__dirname, '..'));
const PRISMA_SCHEMAS_DIR = path.join(ROOT, 'prisma', 'schemas');
const OUTPUT_DIR = path.join(ROOT, 'types', 'dtos');

const SCALARS = new Set(['String', 'Int', 'BigInt', 'Float', 'Decimal', 'DateTime', 'Boolean', 'Json', 'Bytes']);

function readSchemas() {
	const files = fs.readdirSync(PRISMA_SCHEMAS_DIR).filter((f) => f.endsWith('.prisma'));
	return files.map((f) => ({ file: f, content: fs.readFileSync(path.join(PRISMA_SCHEMAS_DIR, f), 'utf8') }));
}

function stripComments(str) {
	// remove /* ... */ and /// doc and // comments
	return str
		.replace(/\/\*[\s\S]*?\*\//g, '')
		.replace(/^\s*\/\/.*$/gm, '')
		.replace(/^\s*\/\/\/.*$/gm, '');
}

function parseModels(schemas) {
	const enums = new Set();
	const models = new Map();

	for (const { content } of schemas) {
		const src = stripComments(content);
		// enums
		const enumRx = /enum\s+(\w+)\s*{([\s\S]*?)}/g;
		let em;
		while ((em = enumRx.exec(src))) {
			enums.add(em[1]);
		}
		// models
		const modelRx = /model\s+(\w+)\s*{([\s\S]*?)}/g;
		let mm;
		while ((mm = modelRx.exec(src))) {
			const name = mm[1];
			const body = mm[2];
			const lines = body
				.split(/\n/)
				.map((l) => l.trim())
				.filter((l) => l && !l.startsWith('@@') && !l.startsWith('}'));
			const fields = [];
			for (const line of lines) {
				const m = /^(\w+)\s+(\S+)(?:\s+([\s\S]*))?$/.exec(line);
				if (!m) continue;
				const [, fieldName, typeToken, attrStrRaw] = m;
				const isOptional = typeToken.endsWith('?');
				const isArray = typeToken.endsWith('[]');
				let baseType = typeToken.replace(/\?/g, '').replace(/\[/g, '').replace(/\]/g, '');
				const attrStr = attrStrRaw || '';
				fields.push({ name: fieldName, baseType, isOptional, isArray, attrs: attrStr });
			}
			models.set(name, { name, fields });
		}
	}
	return { enums, models };
}

function computeCreateKeys(model) {
	// find relation-bound foreign key fields referenced by @relation(fields: [...]) on relation object fields
	const fkReferenced = new Set();
	for (const f of model.fields) {
		if (f.attrs && /@relation\s*\(/.test(f.attrs)) {
			const m = /fields\s*:\s*\[([^\]]*)\]/.exec(f.attrs);
			if (m) {
				m[1]
					.split(',')
					.map((s) => s.trim())
					.filter(Boolean)
					.forEach((n) => fkReferenced.add(n));
			}
		}
	}

	const omitByAttr = new Set(['created_at', 'updated_at']);
	const createKeys = [];

	for (const f of model.fields) {
		// skip block attributes or computed
		if (f.name.startsWith('@@')) continue;
		// skip relation object fields or arrays
		const isRelationObject =
			!SCALARS.has(f.baseType) &&
			!f.baseType.match(/^Bytes|Json$/) &&
			!f.baseType.match(/^[A-Z0-9_]+$/) &&
			/@relation/.test(f.attrs);
		if (isRelationObject || f.isArray) continue;
		// skip id or timestamps
		if (/@id\b/.test(f.attrs)) continue;
		if (omitByAttr.has(f.name)) continue;
		// skip referenced foreign keys
		if (fkReferenced.has(f.name)) continue;
		createKeys.push(f.name);
	}
	return createKeys;
}

function generateDtoFile(modelName, model) {
	const createKeys = computeCreateKeys(model);
	const keysUnion = createKeys.map((k) => `'${k}'`).join(' | ');
	const keysArray = createKeys.map((k) => `\t'${k}'`).join(',\n');

	const out = [
		`// Auto-generated by scripts/generate-dtos.js. Do not edit manually.\n`,
		`// Source model: ${modelName}\n\n`,
		`import type { ${modelName} as ${modelName}Model } from '@prisma/client';\n\n`,
		`export type ${modelName}DTO = ${modelName}Model;\n\n`,
		`export type ${modelName}CreateDTO = Pick<${modelName}Model, ${createKeys.length ? keysUnion : 'never'}>;\n`,
		`export type ${modelName}UpdateDTO = Partial<${modelName}CreateDTO>;\n\n`,
		`export const ${modelName.charAt(0).toLowerCase() + modelName.slice(1)}CreateKeys = [\n${keysArray}\n] as const;\n`,
		`export type ${modelName}CreateKey = typeof ${modelName.charAt(0).toLowerCase() + modelName.slice(1)}CreateKeys[number];\n\n`,
		`export function pick${modelName}Create(input: Record<string, any>): ${modelName}CreateDTO {\n`,
		`\tconst out: any = {};\n`,
		`\tfor (const k of ${modelName.charAt(0).toLowerCase() + modelName.slice(1)}CreateKeys) { if (input[k] !== undefined) out[k] = input[k]; }\n`,
		`\treturn out as ${modelName}CreateDTO;\n`,
		`}\n\n`,
		`export function pick${modelName}Update(input: Record<string, any>): ${modelName}UpdateDTO {\n`,
		`\tconst out: any = {};\n`,
		`\tfor (const k of ${modelName.charAt(0).toLowerCase() + modelName.slice(1)}CreateKeys) { if (k in input) out[k] = input[k]; }\n`,
		`\treturn out as ${modelName}UpdateDTO;\n`,
		`}\n\n`,
		`export function to${modelName}DTO(entity: ${modelName}Model): ${modelName}DTO {\n`,
		`\treturn entity as ${modelName}DTO;\n`,
		`}\n`,
	].join('');

	if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
	const outPath = path.join(OUTPUT_DIR, `${modelName}DTO.ts`);
	fs.writeFileSync(outPath, out);
	return outPath;
}

function main() {
	const target = process.argv[2] || 'users';
	const mode = process.argv[3] || 'shape'; // 'dto' | 'shape'
	const schemas = readSchemas();
	const { models } = parseModels(schemas);
	const list = target === 'all' ? Array.from(models.keys()) : [target];
	for (const name of list) {
		const model = models.get(name);
		if (!model) {
			console.error(`Model not found: ${name}`);
			continue;
		}
		if (mode === 'shape') {
			const typeCode = generateModelTypeFromSchemas({ rootDir: ROOT, modelName: name });
			if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });
			const typeName = modelNameToTypeName(name);
			const outPath = path.join(OUTPUT_DIR, `${typeName}.ts`);
			const header = `// Auto-generated shape by scripts/generate-dtos.js (mode: shape). Do not edit manually.\n`;
			fs.writeFileSync(outPath, `${header}\n${typeCode}`);
			console.log(`Generated shape ${outPath}`);
			continue;
		}

		const outPath = generateDtoFile(name, model);
		console.log(`Generated ${outPath}`);
	}
}

main();
